apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-deployment
  namespace: mullvad
  labels:
    app: base-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: base-deployment
  template:
    metadata:
      name: base-deployment
      labels:
        app: base-deployment
    spec:
      restartPolicy: Always
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop: [ "ALL" ]
              add: [ "NET_ADMIN" ]
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: mullvad-secret
                  key: WIREGUARD_PRIVATE_KEY
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: mullvad-secret
                  key: WIREGUARD_ADDRESSES
            - name: SERVER_CITIES
              value: "Paris"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8,172.198.1.0/24,192.168.101.0/24"
          resources:
            limits:
              squat.ai/tun: "1"
          volumeMounts:
            - name: gluetun-config
              mountPath: /gluetun
        - name: base
          image: tailscale/tailscale:latest
          imagePullPolicy: Always
          env:
            - name: TS_KUBE_SECRET
              value: ""
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: mullvad-secret
                  key: TAILSCALE_AUTHKEY
            - name: TS_HOSTNAME
              value: "base"
            - name: TS_EXTRA_ARGS
              valueFrom:
                secretKeyRef:
                  name: mullvad-secret
                  key: TS_EXTRA_ARGS
            - name: TS_NO_LOGS_NO_SUPPORT
              value: "true"
            - name: TS_STATE_DIR
              value: "/state"
          volumeMounts:
            - name: base-config
              mountPath: /var/lib
            - name: base-state
              mountPath: /state
      volumes:
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-data
        - name: base-config
          persistentVolumeClaim:
            claimName: base-data
        - name: base-state
          persistentVolumeClaim:
            claimName: base-state
