apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backends.yaml
  - backendtrafficpolicies.yaml
  - clienttrafficpolicies.yaml
  - envoyextensionpolicies.yaml
  - envoypatchpolicies.yaml
  - envoyproxies.yaml
  - httproutefilters.yaml
  - securitypolicies.yaml
