apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readable-data
  namespace: readable
spec:
  storageClassName: app-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
