apiVersion: v1
kind: Secret
metadata:
    name: readable-secret
    namespace: readable
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:9aWdBgU7htwCKUSQJTNOAFq3XpBpsNu6IqOPd/gXOgfmz0DmzBtxwxPjGUU=,iv:4BdXWwGPPoc6DeRlaS6jpGqH7ZsaibgBZ3Hq1zjga7Y=,tag:OG2pamt4kD56KeBHK3HXPA==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:AdApnQVdAw2RWhjAFAwQUfk/UxeqmD+FmQ==,iv:veaI1CpVMpegmPzmzISpr3ccqGrLnuli5T5bhO2l6iA=,tag:SrMVopNJAZMHdYL6+sJxIQ==,type:str]
    VOX_API_KEY: ENC[AES256_GCM,data:ri3a4K9eg+LjNe2OOHtQk3+q5cqE02LvAB0wVmwQbW4B7+rpYNLzszDE8F/lfvYFx4J6JlgYiRhW4qDNk6ND3w==,iv:AZgyv6Rxk452lLxz3ZgBxlROAIrkm7Nu7p9fvUbCtYU=,tag:4a6DU25P7+P8kcgWqNb0+A==,type:str]
    DSTREAMS_TOKEN: ENC[AES256_GCM,data:U4FoxsrhVL4noH59S4eTXMldvZF2wGMot+PadzdPY7u6Y/CluY6S6XDNzhvjKDEstztCtKDFsY4svM1t4pRlpw==,iv:wKZ6kF9B1my0TwutXe8ULSsYeZF4rGacMTSp8rqaXDI=,tag:3ApUI8QnWx81Ynu0+C5Lug==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRjBSZE8wZ1JFdDd5ZzRG
            UnV3NHFjMFZ6UHBCVmF2c2Z2amwzUDRrSGhBCi9IdXdwK242aEszN1drRndWQ3lM
            ZVhsemhKTTdtWXNXcGdVMGlTWkVVZjAKLS0tIFMxa0htcHBwZG1Xbm0zQnUzZk5I
            RjZlRzVvbHVzQUxldUk0TURJa2tiSmMKDhPJXqA0jX9IB8Q1RtIv2zWBkxhnPemF
            wXR3mKq7Pl0uyl0wyPgTKdHAG21oA8utG9VMz2pECEYnSvSAkPbzOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T14:59:04Z"
    mac: ENC[AES256_GCM,data:yLSuBsWez1rdJ1vcMO6xh4AztMAiaW6XUdyDkKTzOsMj7ExlA0hMpYFHFjHXhD2UVbyA420LMKJFGfoTa/fxvv/iboxJ3z90zcxcvduSs+KDyomRflqUp/mpoAgtuAMI89Rxfnnt5aP9+gkEtEqzD5GLIc49tiOtWQRqZXtdNeM=,iv:WVNLvs9Ltyhl/mw4yJlUcMGuBOXLAid7VW9oxdl1Ong=,tag:qMJfe0FzdUFcI/6XBv7nWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
