apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cloudflare-gateway
  namespace: cloudflare-gateway
spec:
  gatewayClassName: cloudflare
  listeners:
    - protocol: HTTPS
      port: 443
      name: https
      hostname: "*.maix.ovh"
