apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudflare-gateway
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/pl4nty/cloudflare-kubernetes-gateway
  ref:
    tag: v0.7.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-gateway
  namespace: flux-system
spec:
  interval: 1h
  path: ./config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudflare-gateway
