apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: njord-deployment
      - op: replace
        path: /metadata/labels/app
        value: njord-deployment
      - op: replace
        path: /spec/template/metadata/labels/app
        value: njord-deployment
      - op: replace
        path: /spec/template/metadata/name
        value: njord-deployment
      - op: replace
        path: /spec/selector/matchLabels/app
        value: njord-deployment
      - op: replace
        path: /spec/template/spec/volumes/1/persistentVolumeClaim/claimName
        value: njord-data
      - op: replace
        path: /spec/template/spec/volumes/2/persistentVolumeClaim/claimName
        value: njord-state
      - op: replace
        path: /spec/template/spec/containers/1/env/2/value
        value: njord
      - op: replace
        path: /spec/template/spec/containers/1/name
        value: njord-tailscale
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "Europe/Amsterdam"
      - op: replace
        path: /spec/template/spec/containers/0/env/5/value
        value: "Amsterdam"
  - target:
      kind: PersistentVolumeClaim
      name: base-data
    patch: |-
      - op: replace
        path: /metadata/name
        value: njord-data
  - target:
      kind: PersistentVolumeClaim
      name: base-state
    patch: |-
      - op: replace
        path: /metadata/name
        value: njord-state