apiVersion: v1
kind: Secret
metadata:
    name: io-secret
    namespace: io
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:47Y=,iv:CP1qr/mnSofBJujPV0N3+kejwc22EQnFJmtqKR0hPXk=,tag:r6gB4pnM2hOwWe0shT/UWw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:hE0lnYttBd3AFuWrw+DhCW+g1jrH/wQp4GiEV6jNocc=,iv:5XMeSi9SnED3xixUlBB02/McG8qu2XxJOSq/9Snpwtw=,tag:pwAx+AHH7n5WwqAqym1Siw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:+0g=,iv:WP6ETGs+ll3eTblT5zZ+PfktwDeSNeBNqPZxHavcxkQ=,tag:XiMHY5TCoWbD92P6ARYXiQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:tyaM9scU4A4R7+721QXanZSudkE3K8n74121THtFsj4/ScNLn3UJBThhZ8c=,iv:Xh6EATAeT2pdQq/blpBCFWf7wSSHrQ6bql18vw1VzLc=,tag:buYFE5Ivy0oL7BfUGxMleA==,type:str]
    SESSION_TOKEN_SECRET: ENC[AES256_GCM,data:nBW8a76tsrsxZCWK0LZy1s3n2UiIR/Zxi/B1TuGJD6RJFpUhY8mjB6rq1qE=,iv:77C/xOSzWJ/QxzuxPk10YsfyDaJXX+wlswDliniLxa0=,tag:kSvGkhVurqt9+TBedxiiuQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb2dPdm10U0F3bGxYY0Ri
            ODdEbWZBQ2p0bDdJWVo4YVVlZTFhV3BYL2xvCjIxOFliZm5KcFZxaFdGRnFFeFg2
            aG1NaERnOStDRW9waWRxOElrVFJxcGMKLS0tIDhJbHc2L29BQ1VPNm0zNVZiUEdN
            REpwd0diM0hhU1RWaEFlY0U3Nko3VjAKuoyoYfibHCa73GrfXAYj5RcwEqF0jDea
            uStedzb4QhNuo0sDJnnA4cCbuqCAYh4ng0S7dGr2fI+Hcu/CiwiJJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T01:31:17Z"
    mac: ENC[AES256_GCM,data:JiD04si9Va0acVlWbiIbZtqQcIQrto1xY02j+ZZM9XU0l+mIfQr8o1Zh5OgAZPoPTrwOGobLfLw+kvxRXIe7P2gDaOa8DYEpBBzFLr0krsaS/wJU9WI0qO98tbBYCgY61ruZn8AN3Dz1+PwsBkOyKkZmEzuBtJkFFXQGNSpIC4o=,iv:U+bSkaoRDOi1Bnsefy2ZLkwVr1FhprYQaexWAKR2H6U=,tag:TTwOGkTOcLND9YLANVddRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
