apiVersion: v1
kind: Secret
metadata:
    name: io-secret
    namespace: io
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:efk=,iv:N6nfgsMiAqCFaGV0bjyKNwxE65u6V2elY8V36whmH60=,tag:GhBMK5bH6c62YEsQGt0i9Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:XWtZtdAFtb86sBquWlK/T3KUqKpNkAPNoQdgZFzK9Xs=,iv:007RAbqEd8jh1y/HKFxrsysw+C02TVRdC4k6DPMsB00=,tag:OMzJ5QbTwFNZEaHMXNKG6A==,type:str]
    DB_NAME: ENC[AES256_GCM,data:AQQ=,iv:nELClp40CTWrTEfGAfuto/Rd+ANMta1c8UYAr6gHPQA=,tag:JdwB0Dktl3X9I9w09cYPuw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:01eq3JW0MrCYUtqeX0rk2xMSqSFO2kyWBgEI7bD7aZX+JA8YnKXh8qjDz09Sp8+ziS1LbF8HEsJfwxlikkbSzhtvo7B6JUzIeNpxsXAQnUiT0H5zsDH97qqRfojDE/U1Wu0ox25ADWyV/svDOAuU4W9I,iv:k7+jP3tw32NCzKn4h44xPOGxUu8GHer7Ngnn85qr6do=,tag:auwXH1MEC8pbJJkcy68P3g==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:2WDEbW7I8TM3cWTthm6oVrD340u9luQEbcCe4dqCfWi6jzXabXM1QoZS7po=,iv:m4IMgJ+cAV+VYOFgdyfqTfmOPosSf85bhR39ZA31x0Q=,tag:+y8CtJVZ21zfvoBFkNr64Q==,type:str]
    SESSION_TOKEN_SECRET: ENC[AES256_GCM,data:2YG1EQOM4WGFRvtnTu6Da3/h4EiPMineyXpLWMdpGXcGq28c76wILiYQbB4=,iv:+Zmp/LP/3t0GWUmbCNHSvw27s8Vl2Ue6ygu7s9bW6o8=,tag:+Wn1x7LqtdVrAVT/lujT6A==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMnczbjBvS0hrZmtxN21t
            d3VlR1RTckZPdTJaUG5OeDA0aGhqVmpGYW0wCk1SMExFQjROVEhTVHNTS3JBOEpx
            bFEzN1U1ZGM1RzdLNFdBOVpDNVgwUWMKLS0tIHJ2U0p4cHVBQVVCcnFVVUUraU1I
            SGNwdHErRFY1RklnMG5wU2hIWDRWMU0KABrxu51ZqjsJYwoL8zAi2c4GcALh42Jh
            bNIXs8CQ8u3UpQSNYoefcPzi9ENYHB6eE4Js8Yf7KnkhJgj4/AKltA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T12:08:48Z"
    mac: ENC[AES256_GCM,data:VIVvdRzqCVvZcvDFpUEMmSzazXzVlVE6KIlPdelS/kcSBX0Gg1SLFeCaldyuqklOR5Ner5BPwnt2Xq9050nfOd4/TVjvjW/U+aLlXPztGWtR+pHiOk/dhbifDWMWMCkSGNBwHtcB+2gDCSTW5x4sti2kyumH4VfcSEQ1qWJYV58=,iv:2xaFdY3xwUm4EzdrjCf+gdp5y3ypiXrX1qPVNa+vWls=,tag:gZX2rmCXXMIqYW1l7Xy4cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
