apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hu-model-cache
  namespace: hu
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: blizzard-storage
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hu-gateway-data
  namespace: hu
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 1Gi
