apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: convex-base-data
  namespace: convex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: app-storage
  resources:
    requests:
      storage: 10Gi
