apiVersion: v1
kind: Secret
metadata:
    name: billing-secret
    namespace: postgres
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ada,flow,io
type: Opaque
stringData:
    BILLING_DB_USER: ENC[AES256_GCM,data:MqL5QPaqHg==,iv:KEzaD/+9Jmya3HOQ7JWhqkDsNYcLieBaAZKwlmWTnIo=,tag:20CBuSIM3chBrR6H71ZSsg==,type:str]
    BILLING_DB_PASSWORD: ENC[AES256_GCM,data:7uPDO8M6BGjK1cpnwUcVwpUruxc5eRVGAAIsVxPF8lrLeAxGHwYkvfTtV8M=,iv:mNZHsOLM6buGDnEW98rCtT8+7gP7zwOI9Wsi4gB1lXk=,tag:BMimbEqcwLKOZd5bgUDRJg==,type:str]
    BILLING_DB_NAME: ENC[AES256_GCM,data:GXnhwFAHkw==,iv:y5jjZ9TyIeKBR8mEIqhFbGuMZSLtuNea//rVSGcSm8A=,tag:JsPvSJKUUCLspY4XB9gvvg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjb1BZQlVBVkdnOVAyTEJq
            U1V1NGJwSHpxejR4UlA0R0dBK3JEb0UvWXdVCmZEWGdmYXRkQ1hJVlJBUVBaNFJj
            Q1g5L1hDVFg5eEZwQnRxRTlUSVU5OXMKLS0tIERLajVyMWlqbHA4VGZkSW9IRDVJ
            ZUFvcFE2T1dqYnZDd21QWFNmUUE3MTQKJm6FcYdlwD4/CNuTS3k5X+BTD900MneO
            ZhbXNOSzJGX+ycc0NmpHgp1g82e1+1rakbLyIwHz3Sr97LK1jz5cBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T01:31:20Z"
    mac: ENC[AES256_GCM,data:GOK9j58YSW+hxDKSp9pzWmbsIQiM7Kb8H6pno2ygDBKYGo2/tu++K9NqzPImnTqhA8PoTFB/0DNbWjU2lrsiaCS7e/mmREHNqo7+WJwAMRRu8c4zdIu4gD83H1ubaMbGendIJ1niJgaG/gVOyqCk1QIDTkxz5SSs6EBFrLKazlc=,iv:gcYwTivmH1LYrZ2v5MvTnNSHrgSAr1qdB7v3nD6jLpg=,tag:TsU51zMLsr9NzSJ7eBdMGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
