apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres
  labels:
    app: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      name: postgres-deployment
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: postgres-deployment
          image: ankane/pgvector:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: postgres
  labels:
    app: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:latest
          ports:
            - containerPort: 5432
          env:
            # Connection to PostgreSQL
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: "*"
            - name: POOL_MODE
              value: "transaction"
            - name: MAX_CLIENT_CONN
              value: "1000"
            - name: DEFAULT_POOL_SIZE
              value: "10"
            - name: MIN_POOL_SIZE
              value: "5"
            - name: RESERVE_POOL_SIZE
              value: "5"
            - name: RESERVE_POOL_TIMEOUT
              value: "5"
            - name: SERVER_RESET_QUERY
              value: "DISCARD ALL"
            - name: SERVER_RESET_QUERY_ALWAYS
              value: "0"
            - name: IGNORE_STARTUP_PARAMETERS
              value: "extra_float_digits"
            - name: LOG_CONNECTIONS
              value: "1"
            - name: LOG_DISCONNECTIONS
              value: "1"
            - name: LOG_POOLER_ERRORS
              value: "1"
            - name: STATS_PERIOD
              value: "60"
            - name: ADMIN_USERS
              value: "postgres"
            - name: STATS_USERS
              value: "postgres"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - 127.0.0.1
                - -p
                - "5432"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - 127.0.0.1
                - -p
                - "5432"
            initialDelaySeconds: 5
            periodSeconds: 5

