apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres
spec:
  selector:
    app: postgres-deployment
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
      protocol: TCP
  type: LoadBalancer
