# Create a HelmRepository resource for the NFS CSI Helm chart
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfs-csi
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
# Create a HelmRelease resource for the NFS CSI Helm chart
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-csi-release
  namespace: kube-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: nfs-csi
      version: 4.7.0
  values:
    externalSnapshotter:
      enabled: true
    controller:
      runOnControlPlane: true
      replicas: 3
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          effect: NoSchedule
          operator: Exists
---
# Create a Delete StorageClass resource for the NFS CSI driver
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-delete
provisioner: nfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  server: "192.168.101.100"
  share: "/mnt/snow"
---
# Create a Retain StorageClass resource for the NFS CSI driver
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-retain
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  server: "192.168.101.100"
  share: "/mnt/snow"
