---
# Create a namespace for the Metal LB Helm chart
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
# Create a HelmRepository resource for the Metal LB Helm chart
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1m0s
  url: https://metallb.github.io/metallb
---
# Create a HelmRelease resource for the Metal LB Helm chart
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb-release
  namespace: metallb-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
---
# Create a IP Address Pool resource for the Metal LB Helm chart
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: talos-cluster-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.101.8/32
---
# Create a L2 Configuration resource for the Metal LB Helm chart
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: layer2
  namespace: metallb-system
spec:
  ipAddressPools:
    - talos-cluster-ip-pool
