---
# Create a namespace for the Tailscale Helm chart
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
# Create a HelmRepository resource for the Tailscale Helm chart
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 1m0s
  url: https://pkgs.tailscale.com/helmcharts
---
# Create a HelmRelease resource for the Tailscale Helm chart
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tailscale-release
  namespace: tailscale
spec:
  interval: 1m0s
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
      version: 1.64.2
  valuesFrom:
    - kind: Secret
      name: tailscale-secret
      valuesKey: config.yaml
