---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:latest
          ports:
            - containerPort: 7233
              name: grpc
          env:
            - name: DB
              value: "postgres12"
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: temporal-db-secret
                  key: DB_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: temporal-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: temporal-db-secret
                  key: POSTGRES_PWD
            - name: POSTGRES_SEEDS
              valueFrom:
                secretKeyRef:
                  name: temporal-db-secret
                  key: POSTGRES_SEEDS
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: "/etc/temporal/config/dynamicconfig/development-sql.yaml"
            - name: TEMPORAL_ADDRESS
              value: "temporal-service.temporal.svc.cluster.local:7233"
            - name: TEMPORAL_CLI_ADDRESS
              value: "temporal-service.temporal.svc.cluster.local:7233"
          volumeMounts:
            - name: dynamicconfig
              mountPath: /etc/temporal/config/dynamicconfig
      volumes:
        - name: dynamicconfig
          configMap:
            name: temporal-dynamicconfig
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/ui:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: TEMPORAL_ADDRESS
              value: "temporal-service.temporal.svc.cluster.local:7233"
            - name: TEMPORAL_CORS_ORIGINS
              value: "https://temporal.horus.maix.ovh"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-admin-tools
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-admin-tools
  template:
    metadata:
      labels:
        app: temporal-admin-tools
    spec:
      containers:
        - name: temporal-admin-tools
          image: temporalio/admin-tools:latest
          env:
            - name: TEMPORAL_ADDRESS
              value: "temporal-service.temporal.svc.cluster.local:7233"
            - name: TEMPORAL_CLI_ADDRESS
              value: "temporal-service.temporal.svc.cluster.local:7233"
          stdin: true
          tty: true
          command: ["/bin/bash"]
          args: ["-c", "while true; do sleep 30; done;"]