apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: temporal-ui-route
  namespace: temporal
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - "temporal-grpc.horus.maix.ovh"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: temporal-service
          port: 7233