apiVersion: v1
kind: Secret
metadata:
    name: temporal-postgres-secret
    namespace: temporal
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:nhvFI7puHsc=,iv:ds/1eJAlxigD3zbWBF1xT8IrUnxtm1zE82qDPzs9CdU=,tag:iyE34+XtDq/CEQ9fhFo2BQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2kV8PZMRYQFpXxwoU5ZyP/y3YG5g4AnNq6HD64E22KrSwYT0YiS2BiZHvY4=,iv:J25mPmCaiv0EYBSosU2PBtfwWeXykTdewUU8dfkT6OQ=,tag:NhtUx6rUe4gkT0AjNgvFiQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:SXbIQK4dc14=,iv:PdRfKQ26jWfwnUG94Vr+aHVYSbaQYSJPMMUETwmnDfU=,tag:trA+eQno3xLa609e8FvnHg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VGFETUZUTUU0RlozbUVy
            em5iRVVJbXJiMDBoVTJtVmxYMjRBaENyMXhzClF5MzZPejJFckpWa0dZUkh2L0lJ
            K3hzdDVDUUJIb0N1VTFZYktPckYydFkKLS0tIC90MmMvZWJUM0F1MlhRWGNzbnRl
            VFcwcnh3amd4UndxQU53cXdGOTJaeHMKWxfPvO0WvZPFqPUAlWD8Eud2vtbEMGyJ
            2Zgq56OGCo9bJGbNrqSv/3HFShrB6iE5g0IJSXKj4DaMdRvFotYaMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T16:17:33Z"
    mac: ENC[AES256_GCM,data:9REwmZpyVxBlWcIx1FF9+UFfhjLTz9fz1ErkHb+Bdx6Jzlm/YTfEXFpJNabzQP+EILXaYA0GWddedaPSsZyxr/ytMa671NHFHUE1VDnExN986yAAmaWOdKD1BRCTBzI62CVUU6ULmJUjs0XPkWDxMm+3+tvNunJhUHh+PdF0tSE=,iv:D7TUAc0i2zSIBLbup3T5+WGbLpg4ZxrVzfppEtYPePw=,tag:zWmZGMhZx5dAZuM5+ajMXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
