apiVersion: v1
kind: Secret
metadata:
    name: ankou-secret
    namespace: mullvad
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:A4wtMJ8QjxGSi2vixDFPA9ypA3gjEn1YyRdNszzxBukxbuuJyCylIH1iLyM=,iv:nyn1vgEQQZbU8n/gJA8ceLECEhQ8yGd99nPFOMuBUDc=,tag:tbnc4BmOr8XnPwCskkiQ0g==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:GxvPxllH0bc88xEItgYz,iv:iGuTgJU/vHWdzhnx/XhaODr9SvDY8nPCpIzbJmeNW3Y=,tag:DoJBv5OL96bPqP35G4OhWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WXRBd2NsdXlQNFMwSnJ2
            ajVPZVBnMUg3NkZsWlVNMlpKZWFhWFhvU2pFCndENVN0ajBPa2pTbmNUTUgvT2Vl
            Ris4cFM4b2dZMytJa2hYRURPRGJRbWcKLS0tIEIzTldiL2lMbUprWUxpclNrMlpK
            SzE0RjRiS0p2ZS9ucTZjb3NqV1lQeUUK6DkvJ4x6U3n/B1ltEDzw2+wW/Fba7dn9
            QEoZUbZgTLCQ210xTLbKaWcUVZKakFWVIl0spxornJpOhQVu5L/LYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T09:34:56Z"
    mac: ENC[AES256_GCM,data:RddNwIcWCzvpRc9MhHtRJzjKe00NbGv0JQJa5T5pFkPxnuWpru9Qyyb+yWl6jqiWwKE56HIgAK3Jy+hpeEOCEs3WLgXQYA/WJGTx3sxCxfYE6JUco1Y/6w48z6gBIW8kZFx+vsv/VBVah8DYHjoXcOI/h2f6aDobnCB9wu+JjwM=,iv:ySFbqUFYafJwrTYDBg2KHbK9nGI7T7+6H/5TorPCo7Q=,tag:82CfUgWejy2vI1qleEByGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
