apiVersion: apps/v1
kind: Deployment
metadata:
  name: megane
  namespace: megane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: megane
  template:
    metadata:
      labels:
        app: megane
    spec:
      containers:
        - name: megane
          image: elevenam/megane:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DOMAIN_NAME
              value: "megane.maix.ovh"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: megane-secret
                  key: ADMIN_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /app/uploads
            - name: database
              mountPath: /database.db
              subPath: database.db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: megane-data
        - name: database
          persistentVolumeClaim:
            claimName: megane-db
