apiVersion: v1
kind: Secret
metadata:
    name: megane-secret
    namespace: megane
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:6pK4/Ciftiz00AVu8t3awKd90dA=,iv:Al25tFK02igF65MPZQB7Fq+t1lcwzUjVvS+zdO84dqs=,tag:q/5IZqfnrRr9MKFaZFDH8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSXIvdGp1bXZDSWUwMHYy
            VmR4UmttZ0lyTkEvR2wvVHI2SUJ5MEdpTWlzCjcrU1dVM0lvKzRhaXI1UnlGSjFU
            YmJVdUlxQ0YzZ0d3WlBHYjBDekh0NVkKLS0tIGZRbHF4L2VHS3BaSVlIT2tpMzRx
            bFBuK2JXREZWNlpEZm4wUmd2bnI2cUEKOrooq41lGXIr5u8YGcDSYLdZOc7+guu0
            fx2HbkpAniCf+kBpS7p/BvZyyTEzut252fWgJKFXANc1wPAcpZuzdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T00:35:24Z"
    mac: ENC[AES256_GCM,data:/yZXFkH7Vkct6Q9tG/yT65wEwvC1bazvVsHaSWaje7c/w6SJPuMVWbFawsnlGtja5Ba/XNv2DbVO2W0U8J4Q3ZWvNNSsgdn0Pu1CDVC7tT3SQQ8uLDOc1YGGSgdDqXhXjOnMAwMfl6RmFnijZIRAggyYqu3ohA+u4zPFsTYy2BY=,iv:r4a/m0VcW04rMtUAaLcN3dk35Hp2VxzgFhIxLEUlzkA=,tag:dGR6wLU9UlZCyCS3VJwXvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
