apiVersion: v1
kind: Secret
metadata:
    name: vela-secret
    namespace: vela
type: Opaque
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:HOLjHJdgbr25eQDQ29aUcJBszVr1EcOatw==,iv:gTeXPFec01bZAC+0dxxGjkHOLLv9sXhGkLw4WVFSDWg=,tag:FXnLDYBqU01PHGOsrBmgUA==,type:str]
    VELA_ADMIN_PASS: ENC[AES256_GCM,data:qC7yfc3JMoawDt6e1ysSfV+g+Hs=,iv:LUPf2TA4o5lN06dwc5BDvbPTj+sw/WjJzHrygM/w9Nk=,tag:2tNmkqYoe4YXAWlj6VMyTQ==,type:str]
    VELA_ADMIN_USER: ENC[AES256_GCM,data:6KWIkkuco8qx,iv:iILFlAQdAgGe9LZV341yyfXKGngGHKvU34fKB3STQ7Q=,tag:/kLY565CVCrlGO2h1xdTvQ==,type:str]
    VELA_JWT_SECRET: ENC[AES256_GCM,data:TLQWXjfPsbQH02tYQaoSkiC6XyQ++cMtTNcbLE+CzOlT0AMxEwOB2O5k764=,iv:oT5K3pcITwXU/jd1W/wyQ0sOcCTrdqHkoWU99wGcjzY=,tag:LOqMgPRk+oNBPTNXPwuYAw==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRlNuTmUzZzUxQzVkNDBB
            MUF0MEE1ZDFOckVpd012dnVoRU8yL0s2WUIwCjRkT2pRRUdZOWcyeDRJODFaYlRE
            cGNRUlRzZGh1RjQrL2hBdFoxbW4vbXMKLS0tIGJva3JNL0sxM2s1RjlkblNOUWNE
            MXBvMnB6SU9uN0ZZbG1KTlZKYm53NnMKGWMpRr1Sjcbocla1IXrExTZle1fXO3GW
            0h2xSPEMEFYSX56gE5FIgRiIXSwbKQvVzO7j953dvqJZTWxRB3Fufg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T08:04:09Z"
    mac: ENC[AES256_GCM,data:hQAPOAJlPckJtqGEWOIu80o7h3E3WIa1dDPZh6EKLScvXpoampBkqk1Q6CwaqCtVsL3BnuJdz7Yr7sqA58buTJHV6/xjZvkKUD5l77+chfAvwFk/X66/5d9wdnsX0cPPhdjf8nV9R9sMq3EFVahxTe/RD+MHPfdXHvQj9SvWlG8=,iv:jL1NgsXImOmfViuvvRvn4g/VKM/h4HgxsXYeo5Gvr2w=,tag:BcgtrpElWKZsZ9VlO07fFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
