apiVersion: v1
kind: Secret
metadata:
    name: vela-secret
    namespace: vela
type: Opaque
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:HOLjHJdgbr25eQDQ29aUcJBszVr1EcOatw==,iv:gTeXPFec01bZAC+0dxxGjkHOLLv9sXhGkLw4WVFSDWg=,tag:FXnLDYBqU01PHGOsrBmgUA==,type:str]
    VELA_ADMIN_PASS: ENC[AES256_GCM,data:qC7yfc3JMoawDt6e1ysSfV+g+Hs=,iv:LUPf2TA4o5lN06dwc5BDvbPTj+sw/WjJzHrygM/w9Nk=,tag:2tNmkqYoe4YXAWlj6VMyTQ==,type:str]
    VELA_ADMIN_USER: ENC[AES256_GCM,data:6KWIkkuco8qx,iv:iILFlAQdAgGe9LZV341yyfXKGngGHKvU34fKB3STQ7Q=,tag:/kLY565CVCrlGO2h1xdTvQ==,type:str]
    VELA_JWT_SECRET: ENC[AES256_GCM,data:TLQWXjfPsbQH02tYQaoSkiC6XyQ++cMtTNcbLE+CzOlT0AMxEwOB2O5k764=,iv:oT5K3pcITwXU/jd1W/wyQ0sOcCTrdqHkoWU99wGcjzY=,tag:LOqMgPRk+oNBPTNXPwuYAw==,type:str]
    VOX_API_KEY: ENC[AES256_GCM,data:T8Kfm1s4/ApJD71sbud/VxbeAAt+dIMMUulYDkH0Yw7KY25pOd6rIoM855qUDAW016HJqA4g0iWqIduxq8l62Q==,iv:bgnWSkomAVbLhSosPKl93/FoBSJ+20uxffqUCskN5Fk=,tag:NiZqkU5xRVPQ+8fhRvoSHA==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRlNuTmUzZzUxQzVkNDBB
            MUF0MEE1ZDFOckVpd012dnVoRU8yL0s2WUIwCjRkT2pRRUdZOWcyeDRJODFaYlRE
            cGNRUlRzZGh1RjQrL2hBdFoxbW4vbXMKLS0tIGJva3JNL0sxM2s1RjlkblNOUWNE
            MXBvMnB6SU9uN0ZZbG1KTlZKYm53NnMKGWMpRr1Sjcbocla1IXrExTZle1fXO3GW
            0h2xSPEMEFYSX56gE5FIgRiIXSwbKQvVzO7j953dvqJZTWxRB3Fufg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T10:12:18Z"
    mac: ENC[AES256_GCM,data:c4RMgZLqTISRqA6oY8VyTDYJTDVC+Q9Nu3rRq1EVg7CrKKYEqS/0Eie5DCcERpeWy/Yrrv8Mi1MNh4duCiWi9Exvp72G4rx+dVW4geu125c951yhg+8mhGj6v3Q/xSobaghkjgM5Ma7KZhoHAGYZ+AMZIdhxYRvxgh5+TYggxo4=,iv:yUOHxQ+UetADqNt+wsJ823edFWHR1qywjp0B2GRYjL4=,tag:aL/sRIICXrdrs0kRLa2/8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
