apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-config
  namespace: authentik
data:
  AUTHENTIK_REDIS__HOST: "redis-service.redis.svc.cluster.local"
  AUTHENTIK_POSTGRESQL__HOST: "postgres-service.postgres.svc.cluster.local"
  AUTHENTIK_POSTGRESQL__USER: "postgres"
  AUTHENTIK_POSTGRESQL__NAME: "authentik"
