apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-release
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2024.6.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: authentik
  values:
    authentik:
      error_reporting:
        enabled: true
      secret_key:
        valueFrom:
          secretKeyRef:
            key: SECRET_KEY
            name: postgres-secret

      postgresql:
        host: postgres-service.postgres.svc.cluster.local
        port: 5432
        name: authentik
        user:
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: postgres-secret
        password:
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-secret

      redis:
        host: redis-service.redis.svc.cluster.local
        port: 6379


