apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-release
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2024.6.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: authentik
  values:
    authentik:
      secret_key: "PleaseGenerateA50CharKey"
      error_reporting:
        enabled: true
      postgresql:
        host: postgres-service.postgres.svc.cluster.local
        password:
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-secret
        user:
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: postgres-secret
      redis:
        host: redis-service.redis.svc.cluster.local

    postgresql:
      host: postgres-service.postgres.svc.cluster.local
      password:
        valueFrom:
          secretKeyRef:
            key: POSTGRES_PASSWORD
            name: postgres-secret
      user:
        valueFrom:
          secretKeyRef:
            key: POSTGRES_USER
            name: postgres-secret

    redis:
      host: redis-service.redis.svc.cluster.local

