apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:iOsu8gPV3WgT1g==,iv:tWKHcDvwTCundntCOSU5ilMW5kjVNUhwYnbFsoesMkY=,tag:PNWK9OahUOWMO5qFevFAtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUTA2eU9relI4Sk90ZXpv
            QWthdmlsWFRhYXd0em9EVWZRdURCWS9FV2w4CmZYZHhudkQzcnhsdjlISUEvNW54
            YlZFb3doYXJiOFBqOVRyVUFiQmtmb2MKLS0tIEczcTlBQmJGemtIL1k3SlJoZ0Fr
            MjZHUkREU2JrbW10aS9uZ1VHYUVtd2sKxMMohyCvZp9KXnyGIwE2dCPEzz7HTV4O
            GLx6Sx1FxeqbisF6EX8YZDvYcakjTgEJdlvhqDKKe5XpyCfx3O452Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-08T07:43:57Z"
    mac: ENC[AES256_GCM,data:4dGbdzHAcON49XIGHATF910C5lnIkcoTYzdn+8U4XGKCVaDSlhndhQwmnEO6cpP/2yj7v5QABdkL2UslDfTg/cOJ1g5nl/ilUzf5kJBqUW0Z9In0mPjukorf0cSsGEctbUSTyzaYiiR+uh5jWOEkWCPV4mMhZVwOpTx121iKn1c=,iv:z13haFv8YdRDPtbvFB4lM5HX64vfq1T2zjxhiwlnrzg=,tag:A/vT0PKN+IPZzSQmhAucUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
