apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:hH4ueolE7SrAPA==,iv:sjUzOL7UoUQEvUdU/8gisXbzD9W38m22M5AMgSgde+U=,tag:bAzPMcmlaDALgs9oof9nNg==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:0qS/nFmpenJFFcpat1wm+82azmsRNVHZfr2l6S7zR8Zf5ADx,iv:LCRokXpNQ3AHdTVxdNCjqzPCEtyrghQGCYEBL4C+b+I=,tag:vLBchHEYnIC8ux2PFcZGIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaGZZVTNmQVpLdlcrUTlw
            L0hjdVRvcjZjNTJpaGlyaE5CbktpR2pnS2pZCnBWdXBNWjlLT0tHNkdqSDdKbURC
            OE85QXFOSU1KMU81dWI4WGppMTV2MmMKLS0tIG5lNWpvRTI5WEVvNm43WkhVenZw
            L0Y1R1Vnbko5MmsreTdwMHNZS1NEQTQKqpRq3hHFsmN4o/PqgtVgDQtiqegV6lkh
            cy+WVZNsUq4bSVjJtyqImSt2vCBNkDPFuSp6Hu26NFQeMsmFIlL+kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-08T08:15:47Z"
    mac: ENC[AES256_GCM,data:BF1hiSGInzyWVSWiuOQBr40qXkg4mj2EjP6vIjA6pCx1QUGW2cyl15bZ1anA9dW5V6iXfM+jkHI6pQEQi6fMa9mg7o6gCv1iTfne5RllahUMAoRUecNgv5xlD1SV8vY6DcNOKac4K8J9fVsFDbFZ5MltsL9zyfKkhFqHqTuZbmI=,iv:Ub96v66q9VoBajBMYxdlvJXgzwgudOqy3d8K6F7/IIo=,tag:udpzEijPcuw7HCbIKZu8pQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
