apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dia-model-cache
  namespace: dia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blizzard-storage
  resources:
    requests:
      storage: 20Gi
