apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: ddns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Z5kf5qZ2yYn3TycHvPe2MCssqrTFllNqEUoqv3MfNh6kBX9nWm8+LA==,iv:b92PcHvW0YbCK99E05PEZ6hNuG4m1uS0aU4sWsk3YOM=,tag:650m1F4QWNrklKqZa0oOiQ==,type:str]
    zone-id: ENC[AES256_GCM,data:SKkEDWEn8O4Fp548U1QpuE9F8yOrU+gdcdj2yibXRsA=,iv:fudyL/fsTwSSh/uPZKgD4TqFHTS7jP8TjyojCvKAn7c=,tag:QYSUC5PUvC0aDoHkZJvW2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcXRMSzF1MVZ5R1RZRlRW
            SDdMamRicFV0ZUVaR2VGbktBdENrWnN6bjM4ClpZL0FYcWowUnZYenYvMFJmaWI5
            ZHZYbC9STU02RzFuNkkyY1JiWWtUNUUKLS0tIEtpOHV6R2dNS2dHQWxxa3ZJa2tQ
            eWhDYVlIaWI3dTBZM0dWZWt1RUR0RmcKBiM4es46mwwPLZS27jlQoRnHWD+i7e/h
            SuhlkCSERlyvuLGzq62l+CfSgjkfLIxAqRGrUIjFnn4W3raYtfCqZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T12:25:13Z"
    mac: ENC[AES256_GCM,data:BPTNa5BzSKU5MTjdftiTuP8RiJi6a5UeQjvuyvo1xmzPin/EMv0oqS2c9aVrl/EoAqokwFbMZlDgAeaRohxsS618JnBcRqqQ4nja1coDR6QXKGZyLT2SeppucejmYiUfdig7c3g3NjfNtvPbX24FTFd01icNZN1Tk+S+iBmiJlo=,iv:kS+dETxJiQigjxbbjjWZAoZ3uS46tOUrUxObZYYANgY=,tag:rZRnMnrtoJLz9+G+9g7Lww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
