apiVersion: v1
kind: Secret
metadata:
    name: flow-secrets
    namespace: flow-system
    labels:
        app.kubernetes.io/name: flow
        app.kubernetes.io/component: webhook-router
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:mz3nBReQAH4lIIXtnKmSOxXmLl7Wk2EaTwyodgdFCHCu5mn3i3O03iWhN20lpljwfTFV3GQDjWAW2WfEc7xdD0xwnKfI/8WNzdqeY5TMzXhdK1A3ul0vDiLg49Qp+RQ99ZxcX6avNA==,iv:5JWIaEF4gb86Np4a7/4dsOEYirvyozJ3GieYBbsS7ec=,tag:Kryb1q4yDVf+nPomBAus1Q==,type:str]
    TEMPORAL_HOST: ENC[AES256_GCM,data:pRDua9TvNrJerxKZ2KcgDcwre6FY+W2a5xZK17zArWROQwsjT5bcfvLK6ekWC8fH,iv:bizj4pbDZkqbmf3xO/lt5kYlGyFC+f2TuS6VIZZcqzs=,tag:JBMsar7L6YWbsfOLhiAJLQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:yybXdSmSShkI0bk5YNNis9vVKHoM7d9Zk/fLNw7fuJ5iAa8yVIwXqPmaTNg=,iv:Yt14N+oD52rkYsTAA151H0qdEf47IFsXDLkt5Ng9FLE=,tag:lxDyWJfk07mwcA0Ds9zKqw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:gWxNeyxjLcIvZpJS/rOsmFXi426xBCUe8dJCme/wfPmVvBcoCn+c6ovUUuCL8X3tVQXt4wJsvG4LqWGeCkWkHqvqz5hNNKcdUmmfmcooGRQzBFOLnZUSuQ==,iv:vNJyXEuomUl7weYvmd28xuA2b9KQb/SP3jdvpJDkoXU=,tag:yX81pvtdB6Q/4A26f76I+A==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzclVQdWdKQ1hTZG85SGF3
            TlpsRnluQmZNN0FRL091RGtkdDRyTUdzakRVCm9IYVROQ0ZSdVM3Rjc5UVVBWXBM
            ejNPTTQyTGE4RW82NzRtcFR6ZUhjN2sKLS0tIHNDQkY4a0JIeDRnTXMvZlhtdDMr
            Q3NoYURkWVdLYVBjbHAvM1hUUEtHbGMKRQFs7JvCt5SV6sRjeITEwWCLtTHqCdjc
            NN4EbUGNBLxvnCGNDPh7pSwRVQmzKRpmjhvlrGl6HhiTB+N79686mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T19:15:54Z"
    mac: ENC[AES256_GCM,data:GjTDpcQCWAkqv3+VHc2izMBJH/1veS39P8MV691jENmemHdh+MrrhggWzeSOqYL3VxwJ927+Zt8qmGlotbWogawMW8/vcRQro8fZwYr5aC/mYhQKkVuHm9rWfklIErupmFqLCmtRCwZN3lMCiB0zm9NH+OM7Or7klNTgFz9FSYs=,iv:yaZ4TJQ8zsF25/Lw90jwMQOLO4+him1xOTfqDf72NcM=,tag:D0WBHPvRf+T+VES4ZUzDbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
