apiVersion: v1
kind: Secret
metadata:
    name: flow-secrets
    namespace: flow-system
    labels:
        app.kubernetes.io/name: flow
        app.kubernetes.io/component: webhook-router
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:q3ngWPkkGvlrkpx0S/YN7bqwt8o1scPbsw+ADBB6hKEGNR5VOG9buFqT53bl6NACRER3jXXMtLoRFY7NIxpB+0dT0vXiLALCOsUW9JlbDKhA18E+y67pRBdBCju+FITwzk6z6XUEPe8=,iv:4zUhcYb9bAafv7bjuaT4j5QRkQJaZ2IHT2RiBSdskZo=,tag:RrIPoa1eMyHeHmNZ9QiIsg==,type:str]
    TEMPORAL_HOST: ENC[AES256_GCM,data:8eMxg+TVRjFDVNywbrNOhhEng9VTC70xUrFibyppkfih/pxkolKSc2qKvl96yOcK,iv:HyaizmzaXDNCTXtoJc+g7B0XHY3POvW6OxBlm4RJ6B0=,tag:x7/geqiVEQghnjM6HmP0Xg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:zRmjlPwCjkafZ07r6Y4xTdwyEL+s933IDTrg7hVPhCc4Fb8Wo8YCmHExmvU=,iv:jxKIP0sEO7B8iuQDtaioL0DXdVfNJolwKjFKBS9Psa0=,tag:sIUEnUboMsdI3/IiVA5SVQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:SZSZII6RRR8VJSUYX9wpdKZlTFOw47J6zw4DOdgDuT/b6lqAZzwRtiNQjORkT0Mze3fP8cWRGcv4A+brZXOS3Ess/F1T54G37sWDGl7tWEBTfk9WIIDtfg==,iv:OPwSni8fbx6N5hvDDOSH7aMB3i1iygoSLReTNXFWDoM=,tag:SEeP8vghY3RuPo9rhspsiQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6K3hrTEJ5bkZzY1hkSlpF
            c1psSWJVdGExUEkrbmhhL0JiZzJwWFV6ZWpvCm94OTduSHhaOU5tNVRyUDNzSHEy
            TENyRWRTZjBKbTZ4NHZsYmZxU0NQOEkKLS0tIERTSHl4b05RR3NXcHlKNVVJSG1Z
            VmZuQ1l1SmhLU0dIdHhNalJBUVdpMlkKxzV7+SktTTiH/nFUGtCmQTv4LUgnhe6Z
            wn54ckVx2R76p5MwVCLoRnwigKhTOw1ejXCVkpYTX6P1nJyDWpHAmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T18:11:14Z"
    mac: ENC[AES256_GCM,data:C3g/IMppIS6ZM6/UYyEB7VMq6Y4yTP4kd5q3L0AiOrTse+9X5Sl5mX+pr7SG8XcgCZx6vHbibuY4Q3OVKXuDBYW0mrHyTqt5PlMGDk84HykizTfHQZEMJA0ekBTu5um+aiNzBJdM/b4/whcvquF8Y37aW/kmIWJoE7FNvg3za6Q=,iv:uC3DKOx0CF5rZWglO6CNelUJMgLRYdZRhSTLQ6ePJXw=,tag:JsNtTO8AL8lrtFd85IWFeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
