apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flow-webhook-router
  namespace: flow-system
spec:
  serviceName: flow-webhook-router-headless
  replicas: 3
  selector:
    matchLabels:
      app: flow-webhook-router
  template:
    metadata:
      labels:
        app: flow-webhook-router
    spec:
      securityContext:
        fsGroup: 65532
      containers:
        - name: webhook-router
          image: zot.maix.ovh/flow/webhook-router:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8300
              name: raft
          envFrom:
            - configMapRef:
                name: flow-config
            - secretRef:
                name: flow-secrets
          env:
            - name: RAFT_ENABLED
              value: "true"
            - name: RAFT_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RAFT_BIND_ADDR
              value: "$(POD_IP):8300"
            - name: RAFT_DATA_DIR
              value: "/data/raft"
          command:
            - /usr/local/bin/api
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
          volumeMounts:
            - name: raft-data
              mountPath: /data/raft
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: raft-data
          emptyDir: {}
      imagePullSecrets:
        - name: zot-registry-secret