apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speaches-model-cache
  namespace: speaches
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blizzard-storage
  resources:
    requests:
      storage: 30Gi
