apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flow-data
  namespace: flow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: app-storage
  resources:
    requests:
      storage: 2Gi
