apiVersion: v1
kind: Secret
metadata:
    name: flow-secret
    namespace: flow
type: Opaque
stringData:
    DB_NAME: ENC[AES256_GCM,data:bCbqdQ==,iv:gawQKOS6a2rWj2nB/QiYN6wyXevRNvXnw/wNknW3+y8=,tag:M9E5HpupHVMW9Zbwq1AybA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:hM4pHM9GEqVmJixfhkS3lJG1zK6mKnKumwEpHhZ8FA==,iv:1pjH6c5VE+92Eh52iT+wJGQ7uBr+plcPiO+Hv2zBC4I=,tag:hMAnswzhS1FwW5zKT8lgwg==,type:str]
    DB_USER: ENC[AES256_GCM,data:xkZ8gA==,iv:V3jUWNLVqY+nwc3eaKUM43II9VcwtVc0tHK1mad4y2g=,tag:q0PdSwGy8BdjnFxvPgR69g==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:PABXPAaUh1g2ai3lhtMycoLxUwOh+76064la0wWrtJQ=,iv:dJLakjsuk0gE+li6dvEQ7XVYJG9yYpn2P1nEU2U9rzY=,tag:yDoMrO3dGQODZJvkbagvRA==,type:str]
    INTERNAL_SECRET: ENC[AES256_GCM,data:Zwi3L2pbt80d+u+XGeVY+t2fJx6Ei1LMAdXo0bqjmxEKvPeT/tgLx7SNl1LedZyNJR72jcqp9v+WdGyQelGmhA==,iv:Xd+XosyqiBzi7CGpvNpzSD6J1tR7Di4yTiib9H962F4=,tag:2cT0VOxhDZkJXy97UF5IWw==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:Hb4hRE5r3cWv7iVVRwpJSxXJKzY96P+5,iv:eL+tQTEcYNufjSIG85AZCqj6u91gJ8h7gyZKofuSnhU=,tag:gg03ruJQANlSw+6sPrAXnw==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:YS1oFc5y7SYughZalIvmzgMpjh/pLoLxHOw10cndaGPJaXaNhDEcH/rHfrs8PBhI,iv:HVPKqazz4bY0i0P3FD/1aGZn8GrWZpOYWFp/PzqpLEg=,tag:4NElJac+sdAL5pgCDLFIVg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuU0tXanE4VjJvMTBKV0R2
            TVJxc1JPdkVCRUdoRE0rTTFEbWlMSkF6MFhJCkw5ZHhpUTdmRHo3aUs0UG9XRnNI
            QVhxaXFjTnlIa3NDd3RoQ2ZJUW9UOUUKLS0tIHBoWTY5VFNaOTJSQndxcXNEMFow
            M1FXYWttOThYUUphallKdXhTMmRYbGMKi4dZStPSZMsD7dW/xSnK4PPhCXaJE997
            37udIWOq1FMJLkdetr1SEtn03SqQZ7K5QaWscKhIyOIbC6z4pdUC4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T17:59:02Z"
    mac: ENC[AES256_GCM,data:9glpXZI0mO9zzVw4j6vC6p7iWUf146u/A0Y9K1B+cC0KwzN8i15vXHwiIk2afAXd32pL9ov12BTk21bx6qn7/6fxQxNkvyXR2O0giPrhy91LedDicB+veExPMh8/Ny8DVJa4a4jca+EI1TEiIu8TPi4ko0m4a5wKqV8qlETj5m0=,iv:HUky0m+xEP+fEIEb5ze8ojilqgsDyJW9B7cnhnNJku8=,tag:b33Bn9NEdMiph7u4U/rDvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
