apiVersion: v1
kind: Secret
metadata:
    name: flow-secrets
    namespace: flow-system
    labels:
        app.kubernetes.io/name: flow
        app.kubernetes.io/component: webhook-router
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:UUN6Z5Hta/SCj/FiAqfkl9faWI3BbrT75V2FNz/z18GVoYW0EhI8WkQ6mTdRxv5lBM0D0Aj9jLWx/8tknrdAAbLZz/HF1eyiLQF1EZcmZHh/9yilc9y80hb7WdN1iaPyCNYYia8=,iv:6ofYvaJ7EVcQGaDeO6r7Kj2m/29XhvWiQ6RkVdMSnlU=,tag:YC7UT8S7j/nF3HQ47E0qsQ==,type:str]
    TEMPORAL_HOST: ENC[AES256_GCM,data:3CDRk+LTDsc674IJA6uk1hcJZkRQuJ2BHC3sSbdWQf0l84OZLRbbpOgxGF/fmCiZ,iv:bv8lj8WS+C9bAEwmxksilHJIMmpPlBO1M2u7hzpHQgE=,tag:hP0clT9OeXFGgSNtq1Gg+w==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:mMeXlrwtU5/4G+epRd+6+UmrM5MaPQFnZgDUKHUVrD2cf7RayzHf7hG+YiU=,iv:YdBYrwZJiD+dmdyMbkox+BTXHaF/VzjdANXa0IqeLhU=,tag:vKvkuL1YujWbU5EWiNhjaA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:3JATt87oTw0UTCVxsF2t4/bBrNxhGFyxiHr+MbgjFGUT88ix9Ec8yKjrofFX0G64rvwPW5GQJUG0m2gl201se018T8QOXa858D08XNWKdU4dZjmkwHQXFw==,iv:A6D2v+3K7VeC8UbBJ9HavrDh1SKc0F12aifRxdX1lvU=,tag:yRzBPpkpze9lUlzjfxTkGg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWFl5MlBOWERyS3l3TnFQ
            ZDFUTFNqVGpIbkZzMy9QNVlMWEY0c1k2K2tVCkVoK3dSUU5Zb3RZckxEWHQrY25z
            Rm9mT1c4ZFgxZ1d2MTlsZmhxS201bDgKLS0tIGVacUd2ZnljemIrTHlqa3N3NGxa
            Z2dFQVVTckE2SFRkZzdmOXh4MzdNQUEKCaZXiu/RBjKOECgGVmDTPNCnbTeShh/T
            +ei8N/TOEOIgbqN1j4qMd8rZHO4WaiNVBDMFpGjFYpLw9TU3SMkTSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-07T15:45:05Z"
    mac: ENC[AES256_GCM,data:GFHNe7vwd+7NV891hdtL51NZTEUntBJfTB5wHDObniiwVMEwyfoS93pdb4VV+nngVxPFzTJ291RvF8nD5IkCd4hEJIZoQsh7XhkF4nA7qckZKcQlgds7z104f1db2ayHW2vM666t3qQJJS+XltoKnWHh6l+ZAd/fESxv4ulTa/Q=,iv:kJbleFYbWQkRCfYW82qFy7Wjq8uOypxE/EZSgaTgqOM=,tag:k5rjpU8CytlGrSzUJRAxjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
