apiVersion: v1
kind: Secret
metadata:
    name: flow-secrets
    namespace: flow-system
    labels:
        app.kubernetes.io/name: flow
        app.kubernetes.io/component: webhook-router
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:iGSejXkNoFgOhvd/Y1O0JDsJJExygJ+chBljxWVi6sPGk/CB8iD+jZKHnmpa/zzpcw7Jpz6R85KUlTwD+MGpfW+M0kBhzySlhrDaYItbD9RhM6sSoTOSYG9yaJACe6WJ/5yYTW0xyE0=,iv:lmbAd2VKSkxgWQxWHWUi8XPrGiLDMco/MggXsroL55A=,tag:SoO6vGKluyjeerdn074axA==,type:str]
    TEMPORAL_HOST: ENC[AES256_GCM,data:UBRXai+javRIhCVuFJaXh2ez73H1hW4XqqZax9e9e+BRN0OWcdALre2NMLd8RyuQ,iv:ZIJgFtO6/p9Q2NUgVlq/vKCH83G6/YHYAgGut5FboiY=,tag:ogGutdZwo9RQ8EHL+uXviQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:sxC7jZ/pxEv2/99yh9POYnQDP89dW5TdVWmqOSAOyviEAMteOhysWruGfb8=,iv:cJkcfPqsjwF50xbBL3Vzh/Y9LeSXfuemWFERMQO+YBM=,tag:Ch+qNpfH0dWFYR2tkU8ulQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:GwdoaZ55idJcPaH83uH7Ta+ipKAMF5LVqCcbWarwDqIMk0xj0FBauBeXdXkm1g72PsOMbe18eCmyxRuyNhVmlOFhg8xh9G/PO6nCL/GNRHBikYJaxVULxw==,iv:fRfUwLvvchcEmkqj+rF24fwzs01u7JGBIYNGdUg2Mik=,tag:SApMuwZyjysklwG3LT9+jA==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaWI4Y3NTTklVUkY3bUUz
            aW9wd3hDclRLbjBrOXlBT2pGd25NaUpDNTNRCnVsblpOK1ZNcFRheTNxRytWYWRF
            WFlwNTZsU2lhWEtCMmorSXBDZ05SUk0KLS0tIFRNK3NLeFBqOGh2SXUrbFhWNDlJ
            Nis5M002TjZxUFVmN0oyZmx1bzJ1emcKixOuwO/Op0TjlY+1QhF66r3R95GtNXnr
            IoAFJa/PLE9zh9yMChQGtkL9tBof4ScEI2Bj0p+cK6I2rESqLG6GWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-07T15:50:15Z"
    mac: ENC[AES256_GCM,data:Hk0KYaxsaDuvVedASo3FH7jbm+h6MLKcMr+QckFL9KiAUKnG7jDchViwE07JDtZ++7ko1ru1IgjF+1RXPABmqxLGz+lhvQ8bPHS/RBiXWtYBc7mpDK/5l7Bd6NtpSG9TTH+jPkEbX497LFa3IOsBmnoDMrUQYoUZ5gB4bCAutes=,iv:hgh1NUVxPOzPxWZF0fABNT6jwpwTdDK0ZwMGlOLcBTA=,tag:z7nGpR6NB5pVbWrryfcovA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
