apiVersion: v1
kind: Secret
metadata:
    name: flow-secret
    namespace: flow
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:XUrS6w==,iv:RD1KHLJzRg5sg2ZusljeKvsafwUbVDLN7w0QCO6Yij8=,tag:NslMN1lM8dj6/j6vy5dX5w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:TK7FFfNYpchA6D0ftBExWJpRcsPaaIXS6SMvA3w3DQ==,iv:gNMuprXwygH2s08RaNfH2mEpevpTPEzpHxlA5S0Qviw=,tag:m1UoeRmCL0XubA1uDBR+Mw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:oGVy8w==,iv:AuXtVF+IDWppdxQ9Ldmo0vsD+WAyedwwQ7wT9rMMWrw=,tag:umA6jgEQI+QExquXI8E+/w==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:guErYfE49IJfnV6WDBfU1FbZttrf//8G48owB6aeabY=,iv:sNZQpxl7OjMK3rn83FHYPM9IqWBXkrSW9bHhXSz8ef0=,tag:FWiI3Ds/IupjahLCv5ix8Q==,type:str]
    INTERNAL_SECRET: ENC[AES256_GCM,data:aasUOqjlyT+WypQC/MiuVJkgOWLi2c7reeoEgfwLly1bH8GSZw0SIdu1ySVUHRjGjmDuilOxflRX+p+Po/zWiQ==,iv:VujDQtwM4CksB6ZI+xcX5X4G+QayanufTHx+/mwvE6A=,tag:v3brBHDmT+cieuzHHUVdpg==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:lNhNqEpUgJeFpgByEhbyP3/C9y+V+bwj,iv:v/Hmtu0UO1tGlr7KPjYXV3BhcZhKY4ZoDLVWfLWdATM=,tag:AQ4MgIGMB7VhZk9PPEFLyg==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:3OHLkBglY5x6VNJVdqbjLhiXtWeIzK8MG1Qsbqr8ZLCDNH0n7HJ67jQZMFUqCClw,iv:3deLWCTKXRFlWFG9Exqe44WYGF6fXOYGNAZJlRsK6O8=,tag:vaE1V2dHtGFZZBm69moHuQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcy9xSldxWEF3KzA1RzFY
            eTZJeUc5NDlQN3h5aGhkYmFPcWVMbitpZEZzCk1acDZUTHRxdGczN1c0WHNQVFEx
            bkR2SVRDa2RTc3VPOW9CSSs4YzRUbzAKLS0tIDFYWW15dHAyMlNHN0hsUURTYjhI
            M0k3Q2Y1dEVHSWVralBRMDB2Vk5rbkUKgClg4Hu3NmdhW+j3TuVj1EhyKC7NjQCh
            Qm20JhAMD0ZH9o6rHGy9KvhnFVG2FwXAId2/AyOUD+oWOkhlr6OOMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T01:31:15Z"
    mac: ENC[AES256_GCM,data:IMTXlbGziSaG8kjAesK7NNS+4QHmHJBAemxU6VSWExCCuhb3PRypBxaYQ8EJqPqWAlrBZmJItr+ycPKb6PNlrLDyQXCNmAbyn/uGPunNqZKNy9RQX2rmffyG6aOkxERCfOVBGXZwNG9j85HAOpo5oDIVrIA4V2zhFYVlwpepH2A=,iv:CvqDAfx5yQ8vTwaqAFJ3d0Q0mAQ3upnOnTp0NYZJ9U4=,tag:BoZIgnPX7Eg0wNT9LmYfNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
