apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldr-data
  namespace: local-deep-research
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: app-storage
  resources:
    requests:
      storage: 10Gi
