apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: "4.4.10"  # Specify the version you want
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  targetNamespace: rabbitmq-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Basic configuration
    clusterOperator:
      watchAllNamespaces: true
      replicaCount: 1

      # Resource configuration
      resourcesPreset: "small"  # or specify custom resources

      # Enable metrics if needed
      containerPorts:
        metrics: 9782
      metrics:
        service:
          enabled: true
          type: ClusterIP

    # Enable Messaging Topology Operator
    msgTopologyOperator:
      enabled: true
      replicaCount: 1
      resourcesPreset: "small"

      # Metrics configuration
      containerPorts:
        metrics: 8080
      metrics:
        service:
          enabled: true
          type: ClusterIP

    global:
      security:
        allowInsecureImages: false