---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 5m0s
  targetNamespace: traefik
  values:
    # Enable Gateway API provider
    providers:
      kubernetesGateway:
        enabled: true
    
    # Enable experimental features for TCPRoute
    experimental:
      kubernetesGateway:
        enabled: true
    
    # Gateway configuration
    gateway:
      enabled: true
      namespacePolicy: All
    
    # Define entryPoints
    ports:
      web:
        port: 8000
        exposedPort: 80
      postgres:
        port: 5432
        exposedPort: 5432
    
    # Service configuration with LoadBalancer
    service:
      type: LoadBalancer
      annotations:
        io.cilium/lb-ipam-ips: "172.198.1.100"
    
    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 1000m
        memory: 200Mi
