apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "32.1.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    providers:
      kubernetesGateway:
        enabled: true
        experimentalChannel: true
        namespacePolicy: All
    
    # Enable dashboard
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.horus.maix.ovh`)
        entryPoints:
          - websecure
    
    # Service configuration
    service:
      type: LoadBalancer
      annotations:
        io.cilium/lb-ipam-ips: "172.198.1.100"
    
    # Ports configuration
    ports:
      web:
        port: 80
        exposedPort: 80
        protocol: TCP
      websecure:
        port: 443
        exposedPort: 443
        protocol: TCP
      # TCP ports for services
      postgres:
        port: 5432
        exposedPort: 5432
        protocol: TCP
      redis:
        port: 6379
        exposedPort: 6379
        protocol: TCP
      mysql:
        port: 3306
        exposedPort: 3306
        protocol: TCP
    
    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 1000m
        memory: 200Mi