apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config-template
  namespace: zot
data:
  config.json.template: |
    {
      "distSpecVersion": "1.1.0",
      "storage": {
        "rootDirectory": "/var/lib/zot",
        "dedupe": true,
        "gc": true,
        "gcDelay": "1h",
        "gcInterval": "24h"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "realm": "zot",
        "externalUrl": "https://zot.maix.ovh",
        "auth": {
          "openid": {
            "providers": {
              "github": {
                "issuer": "https://github.com",
                "clientid": "GITHUB_CLIENT_ID_PLACEHOLDER",
                "clientsecret": "GITHUB_CLIENT_SECRET_PLACEHOLDER",
                "scopes": ["read:org", "user", "repo"],
                "keypath": ""
              }
            }
          }
        }
      },
      "log": {
        "level": "info",
        "output": "/dev/stdout"
      },
      "extensions": {
        "metrics": {
          "enable": true,
          "prometheus": {
            "path": "/metrics"
          }
        },
        "search": {
          "enable": true,
          "cve": {
            "updateInterval": "2h"
          }
        },
        "ui": {
          "enable": true
        }
      }
    }