apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
  namespace: zot
data:
  config.json: |
    {
      "distSpecVersion": "1.1.0",
      "storage": {
        "rootDirectory": "/var/lib/zot",
        "dedupe": true,
        "gc": true,
        "gcDelay": "1h",
        "gcInterval": "24h",
        "storageDriver": {
          "name": "s3",
          "rootdirectory": "/",
          "region": "us-east-1",
          "regionendpoint": "http://minio.minio:9000",
          "bucket": "zot-registry",
          "secure": false,
          "skipverify": true
        }
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "realm": "zot",
        "auth": {
          "openid": {
            "providers": {
              "github": {
                "issuer": "https://github.com",
                "clientid": "${GITHUB_CLIENT_ID}",
                "clientsecret": "${GITHUB_CLIENT_SECRET}",
                "scopes": ["read:user", "user:email"],
                "keypath": ""
              }
            }
          }
        }
      },
      "log": {
        "level": "info",
        "output": "/dev/stdout"
      },
      "extensions": {
        "metrics": {
          "enable": true,
          "prometheus": {
            "path": "/metrics"
          }
        },
        "search": {
          "enable": true,
          "cve": {
            "updateInterval": "2h"
          }
        },
        "ui": {
          "enable": true
        }
      }
    }