apiVersion: v1
kind: Secret
metadata:
    name: zot-minio-credentials
    namespace: zot
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:HleC5df7IuwNoODY,iv:OgdKAIhXXvoDnwIEWm0t2nmyQwQJkac4xl9czEvAtxg=,tag:rYtBqJXCP0YTvqGpgcZwnw==,type:str]
    secretKey: ENC[AES256_GCM,data:9JCaIWuHdhl2e1rQII4YNPnkjYiuW6C5urqwEw==,iv:FNHoesynTOCsej0AyUS6aCJ4q+ewUfjOiNvWOObUQGg=,tag:ERitLNwIVavXygf8/udUOA==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYWRFbi9WRWVZMFUrTDdC
            b1lHb1p0d1lHTkx4R3QvZkRVSjB5Ynk4dFZNCjltRFY3c091dzNKaG9oWTdWTWlV
            bjZDK0pzb1FzTzNGTTJHaWhHUXIvNjAKLS0tIFVoVU1kRS9OeVJQanQ0bUhyUWpT
            YnJxYzBFekZhSjQwcFdXOEt4MDZidUEKnxrT13cqMKuHQsvIY0TLcZ1jqxuFPzpH
            VZck7V0ZrdxXZpXa3yIcUGe1qRZitZG29CPB2CZuB0qa1vilckCooQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T11:24:33Z"
    mac: ENC[AES256_GCM,data:gD8df17sq+dXzqy23iUJKwesz87G8L3YGnyVaygpXhtgBisZwviHookYfu2U5gWQ8QhTVdFPf9ogQpNN1MY8m7Wyz6YdYWJuvle2Sn+/TxmDK2iTcdqY2bo2wgHAhSC3PLH2s2NjhGwaY45X2tuwcW87qh8xd58fM87OsDOdpAk=,iv:qlOygvjDFKMl2Tibu/kVFhp1NmkBXCYBloqwWJCU7xA=,tag:g8TlulYDBHODxm3Hky3zfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
