apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zot-data-pvc
  namespace: zot
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: app-storage
  resources:
    requests:
      storage: 50Gi