apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: overseerr-server
  name: overseerr-server
  namespace: overseerr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: overseerr-server
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: overseerr-server
    spec:
      containers:
        - name: overseerr-server
          image: lscr.io/linuxserver/overseerr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5055
              name: overseerr
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: VERSION
              value: "latest"
            - name: TZ
              value: "Europe/Paris"
          volumeMounts:
            - mountPath: /config
              name: overseerr-config-volume
      restartPolicy: Always
      volumes:
        - name: overseerr-config-volume
          persistentVolumeClaim:
            claimName: overseerr-config-pvc
