apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-upload
  namespace: firefly
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: app-storage
  resources:
    requests:
      storage: 2Gi
