apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-db
  namespace: hermes
spec:
  storageClassName: app-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
