apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repo.yaml
  - secret.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.crds.yaml
  - release.yaml
