apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: 1.19.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: cert-manager
  values:
    installCRDs: false
    replicaCount: 3
    extraArgs:
      - --feature-gates=ExperimentalGatewayAPISupport=true
      - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
      - --dns01-recursive-nameservers-only=true
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 9.9.9.9

