apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: gateway
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:5u+BgH9LDiXZbJo05H3dCjLQFW5bpOrVAs1iSe4hFixkDQIhPwueyw==,iv:ALWhYUUpBvoOrJMaQYz5J/+3RTuRRxcD2ilsRHvKvKQ=,tag:8tHUYD4aN+VFG9cgaOFaaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSVZkZHRyY2l0SkdaWWxC
            SGV3VU1WaXo1Ky9yVUhuNVZ3Uk9YZG0rMVNNCjQ2eXJGVk9yQ2RGa1JMMFIyYUQw
            dFpVbkZueWtHRDYvK2V3U0F6ZEVjaWMKLS0tIFAxcG01Y1ZCaC96YW90U0pDRjRV
            bFM2c3AzWDdIdDE1RmdtTXlmMy9mbWMKsoa/z/nfWMlz41GZuNCOWMtNXrYBg9Zp
            WxaFRu/HGg22ZATemI4fKMdh16Fh8iQWKeuNe5pder+ucUx3T4Ojvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-18T19:44:45Z"
    mac: ENC[AES256_GCM,data:+b0iQEDwotDImY4GZEIEwMgaM/pmUhxX+RqEkwawjnBeut37R3aCEZq0ZMhASFZdWqxgvTNyjpBtrN+/B23EgKU64ZJPaSZkCyL9Ak/z3c4+zw1WFaSeHeMAns5ND1EtkU7R9jxyJgQYQePYitr0EsWFuQQQhb5m6q4U+ae7bX8=,iv:7QwQh159QZ6+FALjjirGvOrBP/0itBSu8BhKvamWMZY=,tag:zZV2cTk9+fUAwCP3bReOiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
