apiVersion: v1
kind: Secret
metadata:
    name: livekit-credentials
    namespace: livekit
type: Opaque
stringData:
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:qe2i3AJN1lndwg==,iv:+l/TvGFyWlawrcm1JLNFafPXRrgmspHT2hLQGikSR7g=,tag:+bjxZ+zYAEBtdYbKDG0+lQ==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:D6xQY1u1WGBcTsMA47fMmq4MUCosdeAai4na3GLA7rw+fRLbF3a14iYv/xE=,iv:SBOYY7VZvEi8FuIv53DMVPQt9sGgzcK2YNZZn/ApXjI=,tag:hAFp7q7qTzQt/lqe/LQ5LQ==,type:str]
    API_KEY: ENC[AES256_GCM,data:ZPVlbOXebuK9JxEvmShy36nD0UJ4CY8ixHHrpLeegFAnn1WsAng0RFvnwVg=,iv:jbicXjq353U4Q1pr55bNepZleZAEGICemdLYrWQ/DCw=,tag:jUBiqrTll42TDMhQ23BWDw==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwS0dkWk9ZRi91aDQ3K1Bw
            SWJiUFJXUUgzOVNtZEJJVjhqbnhvbzFTVlFrCkNueEJWNFJQRU84Q3RrdWNRRUZL
            SW5HbEY4YkVLZi8wMFlKdENQSndrK2sKLS0tIFdoOUFpRXp6NXhCN0dTcVFBcU1i
            T3NrcEg4VSt1QmVUQ0g5L0xLMmNwSkkKRSln/ebllrE7YvWTOnxOt5YoDw4NUzjC
            1JankZsosaAeLE142ZBd7OiEdtb3YeYJ9XkyUczf5tBYUqiXQ8nQjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T16:28:19Z"
    mac: ENC[AES256_GCM,data:JzZl0f9q46RxZJu4P73mc2As8frlJZFNCLmJjcuRJndWuAmj49CfnFcHKWgIUAxNHhXFOuwvWa/igutqHW30t5qurOChsA1d8uY5c9QQ0J/sX32is9iRRlXi31wTLmyZhJZykvtlKuDvYPvm4uhAA72CKUW5F+reI9NaO/u8H44=,iv:8/Cs/Ti7UESCWxzOhT6BvwvHUmffYvL/tgGQFsD+HlA=,tag:GZtn+cKDT91VR+i7gxUdLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: livekit-config
    namespace: livekit
data:
    livekit.yaml: ENC[AES256_GCM,data:3QNGa1YqqKRp54XTXIy9InHciwDTUQhjby0cIFNLVPaWdYgAr9w8kjcAIYx01pyBcodzFUo9Usz5GdHgIwNwvLZrpyYcWtnv3/IZaZognLxpOJuLGemxIBziZAZn+39Ofqrn6sdswtIjwA2+dcPIPUzr9zK4KM66cHghQ/A7lpA9eut2mcC7FZ7i590Vq9evDuo7g3EBFLgkZcfyTJ4/t1Lk3WC1EmQnU9LzOk007wA6wMxkA9sPdYHRH5q1YNmT4qU5NT8o+0nh9LGj8Sc1OJIHjrxrwcPuyiA7nkYnEBjQFiIcZ+zWJ1rGz+qdjuZuou+8Ak+qRiV6UWI5UcBtS/z+14VVATLImUEejrsqxCkKKR1ZeH31sj+3LUuCqqYWMUQw/jDV4hrL4LEkuJfXzhEeFMJjDiRgrWhOTCJKKHHJLDf8cIC1DDDguDlFdDpHelxF2UKkxao2r22fPolOEUhg7rDMXm6Lo2xHKIUyy8IrfVb6FsVos3cY+lbLT1/w3XHBmdlvscNDnF/P4ekvsKYxNuGKvoBf9IOpejF0XmlY+crdg7MTTJ99Erj9/qD31Rcsp6dQ,iv:WqmNfw9Vff7nFdwi6P/lJ6zVlr5JhynmG2PMT5eqmUU=,tag:7aS4UmQoq7xwqWkfxMYH/w==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwS0dkWk9ZRi91aDQ3K1Bw
            SWJiUFJXUUgzOVNtZEJJVjhqbnhvbzFTVlFrCkNueEJWNFJQRU84Q3RrdWNRRUZL
            SW5HbEY4YkVLZi8wMFlKdENQSndrK2sKLS0tIFdoOUFpRXp6NXhCN0dTcVFBcU1i
            T3NrcEg4VSt1QmVUQ0g5L0xLMmNwSkkKRSln/ebllrE7YvWTOnxOt5YoDw4NUzjC
            1JankZsosaAeLE142ZBd7OiEdtb3YeYJ9XkyUczf5tBYUqiXQ8nQjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T16:28:19Z"
    mac: ENC[AES256_GCM,data:JzZl0f9q46RxZJu4P73mc2As8frlJZFNCLmJjcuRJndWuAmj49CfnFcHKWgIUAxNHhXFOuwvWa/igutqHW30t5qurOChsA1d8uY5c9QQ0J/sX32is9iRRlXi31wTLmyZhJZykvtlKuDvYPvm4uhAA72CKUW5F+reI9NaO/u8H44=,iv:8/Cs/Ti7UESCWxzOhT6BvwvHUmffYvL/tgGQFsD+HlA=,tag:GZtn+cKDT91VR+i7gxUdLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
