apiVersion: v1
kind: Service
metadata:
  name: livekit-server
  namespace: livekit
spec:
  selector:
    app: livekit-server
  ports:
    - port: 7880
      targetPort: 7880
      name: http
      protocol: TCP
    - port: 7881
      targetPort: 7881
      name: tcp
      protocol: TCP
  type: ClusterIP
