apiVersion: v1
kind: Secret
metadata:
    name: vor-secrets
    namespace: vor
type: Opaque
stringData:
    GATEWAY_API_KEY: ENC[AES256_GCM,data:wIktYnDUa5/SdTFpMWi3Bov0Xm3Wi2WW+IQSAHz5yKvHLDv1DEo/4CP9G0vgae6jN7gFeQ==,iv:FMzxPjqYWpA70DMu2f+spOArXFu3aYAIINMvyV+x8lg=,tag:PO+M/Ys49HZEvvJ+Lhs+Tw==,type:str]
    LITELLM_KEY: ENC[AES256_GCM,data:3iVuNiZTyK+OkSmBo4r+Oy9K1J+W/m3ecg==,iv:cmkgvFJWQa/v06e4Tq4HFgc/5p4u0+XGA79a/EA4wUE=,tag:ktZdFyQ9W8c1rD85Dg+cDA==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dDJYa05zMENlRENTaDN2
            L2ViQXp2YmI5VzZDaGVTR0U0dWlRcisvaDBnCmVla1dsenNHZ1FiZ3l0ZDMzZE9a
            bmZnRGJzZmJleUVIUWZvV1ljNUxvcEkKLS0tIEtrTmF4cFQ2TTdqNkVXUjlVK3Zj
            Zmk3cTBTRk9ac2ZubWgwcWFRT0R3RE0KjUqSklfJYk2zHntSEEEJqoysMtCGuGxr
            xW/pTtiWR2S4OB/8gIqCM81MwC6L62NE4Kw2PtXgj0hl50VE7A3lGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T22:49:16Z"
    mac: ENC[AES256_GCM,data:ovTPqtASkCjWePOhKA/bXnDh8r/w080bkWOkgo6mJ8cfoDQp3Uc+QAe+u+yJHwNaXJbV3Xwwm4gsa4qrG9EXn0Pw7YUkrF9sXJV1Q+aiDUwmCfEWlAhtY8zvvV3QDUaKZMiAOiA0lAozAKZiA2Ey04zq9wBBWw08sHjrrAFJrJs=,iv:/kn29/VeNUxwHKFf8iYU32wGBObTWGeQ/4ZT0fOZL04=,tag:c8kwTnCry6xBQHS2btZPMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
