apiVersion: v1
kind: Secret
metadata:
    name: vela-video-secret
    namespace: vela-video
type: Opaque
stringData:
    VELA_ADMIN_USER: ENC[AES256_GCM,data:64ZJwr/sk+7p,iv:4Am+/UNGgD3R8sN0lq4DkGpqMFdWqtgU5LFK/1tZVpk=,tag:elKlTTUhuD6/9q4cHJt/hQ==,type:str]
    VELA_ADMIN_PASS: ENC[AES256_GCM,data:ju4FNCzv0YyrZvQaolpMtbtXUaI=,iv:yovSid9v9eULX50ew9WuOwBbKkahpTY8m6u4kOf0af8=,tag:WPo490YyHxP9ufI9Aj3d9Q==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSTJFZHJsRUJHRmloTlhw
            ZHdWT0h5ZGo5cTZpb253VWxLRHlWbXN2ZFYwCmZ6RjNUNmlQQ0JPSm9zNFpBTGV4
            T0FOcXpnMnVRMTRuRHRKY2ZzWFQyUG8KLS0tIGY4WldIM1pENE5CeHROdEdaa1dL
            U3ZycVZ2YklyS1B6aVZYUjU2cG1jNlUKQezGYRf72vAn+bWpq95q7X5Z+hnqgC+g
            /WLhc/N97WkSFlWVc6dg+YnNbg1jdFZJzTkmf2OpprCjhgYFSHFVRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T11:40:48Z"
    mac: ENC[AES256_GCM,data:xMS9Avo7lIiBP4zo7XasXdZWq/Ior+mrENrOnDajb3noW/7TaJLEVwtypihZY1aXdgmeyZN4ws81hmQRn+3NjHVx4LwaQ5PKiliOZP6H4GshWzpY+xqr+qfOlHbGWolKNjdNoWsDL+ZswcUGKMKVQVOdyp06vDX7gzMCEDa/390=,iv:3zsQTCKGDS+QeJ4ElB7cVt1tmGT6f7QHHpRF4OTy+mM=,tag:SQIFaXcgnq+csilko1C5SQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
