apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-data
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-dnsmasq
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-data
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-state
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
