apiVersion: apps/v1
kind: Deployment
metadata:
  name: frames-deployment
  labels:
    app: frames-deployment
  namespace: frames
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  selector:
    matchLabels:
      app: frames-deployment
  template:
    metadata:
      name: frames-deployment
      labels:
        app: frames-deployment
    spec:
      containers:
        - name: frames
          image: elevenam/frames:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/critical
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: frames-data
              mountPath: /media
          env:
            - name: DATABASE_HOST
              value: pgbouncer-service.postgres.svc.cluster.local
            - name: DIRECT_DATABASE_HOST
              value: postgres-service.postgres.svc.cluster.local
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "frames-production"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: frames-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: frames-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
            - name: DIRECT_DATABASE_URL
              value: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DIRECT_DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: frames-secret
                  key: JWT_SECRET
            - name: REDIS_HOST
              value: redis-service.redis.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_TTL
              value: "86400"
            - name: REDIS_DB
              value: "2"
      restartPolicy: Always
      volumes:
        - name: frames-data
          persistentVolumeClaim:
            claimName: frames-data

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcode-deployment
  labels:
    app: transcode-deployment
  namespace: frames
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: transcode-deployment
  template:
    metadata:
      name: transcode-deployment
      labels:
        app: transcode-deployment
    spec:
      containers:
        - name: frames
          image: elevenam/frames:transcode
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/critical
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: frames-data
              mountPath: /media
            - name: transcode-data
              mountPath: /transcode
          env:
            - name: DATABASE_HOST
              value: pgbouncer-service.postgres.svc.cluster.local
            - name: DIRECT_DATABASE_HOST
              value: postgres-service.postgres.svc.cluster.local
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "frames-test"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: frames-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: frames-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
            - name: DIRECT_DATABASE_URL
              value: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DIRECT_DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: frames-secret
                  key: JWT_SECRET
            - name: REDIS_HOST
              value: redis-service.redis.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_TTL
              value: "86400"
            - name: REDIS_DB
              value: "3"
            - name: HLS_CACHE_DIRECTORY
              value: "/transcode/hls"
      restartPolicy: Always
      volumes:
        - name: frames-data
          persistentVolumeClaim:
            claimName: frames-data
        - name: transcode-data
          persistentVolumeClaim:
            claimName: transcode-data
