apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-route
  namespace: test
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - "test.horus.maix.ovh"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: test-service
          port: 3000
