apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: transcode-route
  namespace: frames
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - "test.horus.maix.ovh"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: transcode-service
          port: 3000
