apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frames-route
  namespace: frames
spec:
  parentRefs:
    - name: cloudflare-gateway
      namespace: cloudflare-gateway
  hostnames:
    - "frames.maix.ovh"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frames-service
          port: 3000
