apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frames-ingress
  namespace: frames
spec:
  defaultBackend:
    service:
      name: frames-service
      port:
        number: 3000
  ingressClassName: tailscale
  tls:
    - hosts:
        - frames
