apiVersion: v1
kind: Secret
metadata:
    name: frames-secret
    namespace: frames
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:RKbdK+WTpiQ=,iv:b/IZrsTBtbc7Og2P4mLjNq/leIC5j41fKyPyxuC41Us=,tag:rDaHj/fxYsmX9X2YWsxmTw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:DvAgvmqpMs6mUw==,iv:uqQeW0n2NcTntosNqDJryDnFh5U9j7lu2LrXR3aD4nw=,tag:gIdrVPCF5hnnepS48ZP1Sw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:qtJk/VWvnGVsfaOElDivulfq30XRzQ+ku6I2M1KTcw9onb0NL12/SNLsopkgRPyMXqyK5OsWDXHvxQwbQIe14A==,iv:6rAPxggf8CEX/OgLYFKq2FypIzp46fLhT0mJq+nQ4iI=,tag:z4Jh+3XrK4Tzw4ivpQtUTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cjh3WFFYQ2xwbGthbU9h
            Q0IyQVVYNE5JZHBMNkNXaWVtN3VQWVk1cVNjCkpQNy9jYVZwYUh6ME8wQ1VHT1dj
            Q3M3YzlQdEMzODNncHdpNk5lQTdiOFEKLS0tIGxWOTdHQU5CWCtxVDNhbTVUNzFJ
            MURJM1lyVjVRc1NVT2Y2SFdDRlNrSUEKoRoFjjT9ZHYX8WoJ3CcxUlMJaU+Unjbk
            0CpNFSZiW+unVGHXit9vApsH36NIcTpNn+mcvgzLXNDz5r8v3115+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T13:32:11Z"
    mac: ENC[AES256_GCM,data:rK6ldZQRa14KJnPjQXuYEDGLkUWy1zIqTrsBfvs0gTppegYTJVg0x9YPRRNQrrKEjhfRu5AodpXj1Jf1dD4/6eWNm2StRoEvnWMvFbrtdaBUgmkxQ0J/iMyZYMtjK5MHjjEmn3Vu7+5FehQd1rDXuPih3zlARSQ0Wcju+hjVsHM=,iv:b6qsOwaWeQWcQ6HrAuv3Ju8RsBVmhsWQucnwMSDvxuc=,tag:2sc6FBVx8ZX/+tmA9Ne7+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
