apiVersion: v1
kind: Service
metadata:
  name: frames-service
  namespace: frames
spec:
  selector:
    app: frames-deployment
  type: LoadBalancer
  ports:
    - name: frames-tcp
      protocol: TCP
      port: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: transcode-service
  namespace: frames
spec:
  selector:
    app: transcode-deployment
  ports:
    - name: transcode-tcp
      protocol: TCP
      port: 3000
