apiVersion: v1
kind: Service
metadata:
  name: frames-service
  namespace: frames
spec:
  selector:
    app: frames-deployment
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: api
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: console
