apiVersion: v1
kind: Service
metadata:
  name: frames-service
  namespace: frames
spec:
  selector:
    app: frames-deployment
  type: LoadBalancer
  ports:
    - name: frames-tcp
      protocol: TCP
      port: 3000
