apiVersion: batch/v1
kind: CronJob
metadata:
  name: video-processor-cronjob
  namespace: transcode
spec:
  schedule: "0 */12 * * *"
  startingDeadlineSeconds: 1800
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      parallelism: 1
      completions: 1
      template:
        spec:
          runtimeClassName: nvidia
          containers:
            - name: video-processor
              image: elevenam/video_processor:latest
              args:
                - "--gpu"
                - "-c"
                - "--log-level"
                - "INFO"
                - "-t"
                - "/transcode"
                - "-i"
                - "/data/downloads/"
                - "/data"
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "1000m"
                  nvidia.com/gpu: "1"
                limits:
                  memory: "8Gi"
                  cpu: "4000m"
                  nvidia.com/gpu: "1"
              volumeMounts:
                - name: video-volume
                  mountPath: /data
                - name: transcode-volume
                  mountPath: /transcode
          restartPolicy: Never
          volumes:
            - name: video-volume
              persistentVolumeClaim:
                claimName: transcode-media
            - name: transcode-volume
              persistentVolumeClaim:
                claimName: transcode-temp-dir
