apiVersion: batch/v1
kind: CronJob
metadata:
  name: video-processor-cronjob
  namespace: transcode
spec:
  schedule: "0 */12 * * *"
  startingDeadlineSeconds: 1800
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      parallelism: 1
      completions: 1
      template:
        spec:
          containers:
            - name: video-processor
              image: elevenam/video_processor:latest
              args:
                - "-c"
                - "--log-level"
                - "INFO"
                - "-t"
                - "/transcode"
                - "-i"
                - "/data/downloads/"
                - "/data"
              volumeMounts:
                - name: video-volume
                  mountPath: /data
                - name: transcode-volume
                  mountPath: /transcode
          restartPolicy: Never
          volumes:
            - name: video-volume
              persistentVolumeClaim:
                claimName: transcode-media
            - name: transcode-volume
              persistentVolumeClaim:
                claimName: transcode-temp-dir
