apiVersion: batch/v1
kind: CronJob
metadata:
  name: video-processor-cronjob
  namespace: transcode
spec:
  schedule: "0 9 * * *"
  startingDeadlineSeconds: 1800
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      parallelism: 2
      completions: 2
      template:
        spec:
          containers:
            - name: video-processor
              image: elevenam/video_processor:latest
              command: ["/bin/bash"]
              args:
                - "-c"
                - |
                  SHARD_INDEX=$((${JOB_COMPLETION_INDEX} % 2))
                  /usr/local/bin/process_videos.sh -c --log-level INFO --total-shards 2 --shard-index $SHARD_INDEX --temp-dir /transcode /data
              volumeMounts:
                - name: video-volume
                  mountPath: /data
                - name: transcode-volume
                  mountPath: /transcode
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
                limits:
                  cpu: "2"
                  memory: "2Gi"
          restartPolicy: Never
          volumes:
            - name: video-volume
              persistentVolumeClaim:
                claimName: transcode-media
            - name: transcode-volume
              persistentVolumeClaim:
                claimName: transcode-transcode
