apiVersion: batch/v1
kind: CronJob
metadata:
  name: video-processor-cronjob
  namespace: transcode
spec:
  schedule: "0 2 * * *"
  startingDeadlineSeconds: 1800
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      parallelism: 2
      completions: 2
      template:
        spec:
          containers:
            - name: video-processor
              image: elevenam/video_processor:latest
              args: ["-c", "--log-level", "INFO", "--total-shards", "2", "-t", "/transcode", "/data"]
              volumeMounts:
                - name: video-volume
                  mountPath: /data
                - name: transcode-volume
                  mountPath: /transcode
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
                limits:
                  cpu: "2"
                  memory: "2Gi"
          restartPolicy: Never
          volumes:
            - name: video-volume
              persistentVolumeClaim:
                claimName: transcode-media
            - name: transcode-volume
              persistentVolumeClaim:
                claimName: transcode-temp-dir

---

apiVersion: batch/v1
kind: Job
metadata:
  name: video-processor-job
  namespace: transcode
spec:
  backoffLimit: 0
  completions: 2
  parallelism: 2
  template:
    spec:
      containers:
        - name: video-processor
          image: elevenam/video_processor:latest
          args: ["-c", "--log-level", "INFO", "--total-shards", "2", "-t", "/transcode", "/data"]
          volumeMounts:
            - name: video-volume
              mountPath: /data
            - name: transcode-volume
              mountPath: /transcode
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
      restartPolicy: OnFailure
      volumes:
        - name: video-volume
          persistentVolumeClaim:
            claimName: transcode-media
        - name: transcode-volume
          persistentVolumeClaim:
            claimName: transcode-temp-dir
