apiVersion: v1
kind: Secret
metadata:
    name: convex-secret
    namespace: convex
type: Opaque
stringData:
    INSTANCE_SECRET: ENC[AES256_GCM,data:iIpDbrw7/kTspoiYl/0fFkbeumUrt15F6xdK4HM+pn0iLpXYH3kpC39ESRJgl2CmjB0MY6WwB37eJMbetp59MQ==,iv:t/EE/QGC4Qp/+fQsL1Rq5MINkA76QNrom0wZj9YvyLI=,tag:qU+ss4o/wwAQgbiPaBxkDg==,type:str]
    POSTGRES_URL: ENC[AES256_GCM,data:4xj5CP/sYYkZKQWTbhJuQgFUfimERqUqyjXgR2wRYdZh6lPkP2eoaw+39ZrbLLhXy+mKVeJ0UVdmOGrBzFjBB6k5x2ZWnx5u5uk8sHKcNgpa,iv:Ghzq8j2iJ164p1HGdW/Yy/A8smrbEo1qW+p8caPk/ns=,tag:qwDb45ARQGn5nZzFNSSetQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QlhYd0VlUTM5Nm81WDhK
            VkdoSEh0ODRtYWFSbHEzaEFtdjFnYWVpVkF3CldoaXdzcGV1UE94V21qcmw0enJ6
            QmI4WlkwM1JFUk5lZThEWXQyK1J5VE0KLS0tIGlzYmUyUTdUcDE2Y0VrNWdqWWlq
            U2tNa0oyRmVKUU1qZmdLTGxob29yYU0K4sQLiTuBaKeXaBncNMhLW0SZhlSMr8iB
            ymmFV9ScwtGeMVTDZkFPsP2/01UJAluX1mkNMCrKj+MMyo7RyUoLtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T13:39:15Z"
    mac: ENC[AES256_GCM,data:/gHn8dZng3jG8hxRsO2RaC01scaSGZQcMqa187zHvU5sQhi6lWeMaA6qqrE4EvUoHHHNv+8XzckK7lp+PC2VP6HV7FMDx50Id3l5c574aNDiM5gvasPZ0m7T7ptefyTO+u4Lu3f4H4ilC7srr7FRjCJZFxDKxU3luWqDQsxgkf8=,iv:GcI6L//BaBXsTx4I5M3b6TgTQObu/Ctxubux8V32Zbw=,tag:fbu/8WYt1lqW+iZWbA6VIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
