apiVersion: v1
data:
    name: ENC[AES256_GCM,data:FZ5IBm3MSAAVhGy87Yks/7SiFZ4=,iv:B9IbANVdbGBm4dX9E4tc3s7pgA+BMggmTe6yFWhXP0c=,tag:VvPcm5KtzqvZWSPgE/6dFg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: db
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f29gqwf93q66ycdqz773da3wvp58ph4pq3drm9m8cyq97jkzdufsvcdhqf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSzJCbHU1TEp3TzJuWitO
            bktxYSt3UXBMbEUzSmFVdng5UzNTR3FnRUEwCmNPbEU4eTdhSTZhd1BoTHUxYlBR
            Ym9NS09vaHBMYVVKZ2xmUE90c3BlejgKLS0tIGp1UHRoWStyTVQ4dFByZ0pkVGp5
            OWNXSGJMekVDRVZQLzRnVTVkdUJIRTQKycY45eiPhoQcNzBn9Mpg+G9Hsg9W/9J8
            UO9eRIVK3t0z13MMTHw47mMamDxplw0iVDbUhWFqHGQz660jVW79kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-18T19:29:40Z"
    mac: ENC[AES256_GCM,data:kAn2MErw2Vdrz6Gn4M14WA4rDXD1o2aCYgqdnoSyJvo+5Szzs1Ybm1ejFgFEDfoKLgSWBBP/qHPcHmqE92r2xq0nyu50PPlQ0EPoeVby//o8WADvBkvkZYS66ZcXSMkLqeVSmrghNLEvwcpXn3TCj+vN+TQJSXEGYMIM3ujs7DM=,iv:uCsckXsJ0PPCoolaZKyb8RE2H97uQtqJdhi/MyL24Uo=,tag:Kj74urvvsOepTE9nyayGLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
