apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zot
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/talos-cluster/zot
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: zot
      namespace: zot
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
        optional: true