apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-staging-gateway
  namespace: gateway
  annotations:
    cert-manager.io/issuer: cloudflare-staging-issuer
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.staging.ossai.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: cloudflare-staging-certificate
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: gateway
  annotations:
    cert-manager.io/issuer: cloudflare-issuer
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.horus.maix.ovh"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: cloudflare-certificate
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cloudflare-gateway
  namespace: gateway
spec:
  gatewayClassName: cloudflare
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: cloudflare-certificate
      allowedRoutes:
        namespaces:
          from: All
