apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: gateway
type: Opaque
stringData:
    ACCOUNT_ID: ENC[AES256_GCM,data:xoKXpNzI9oijaq7nh1xJtzB+KtF8leNQvfBqXV/go1U=,iv:nbreMvFPR2nuwEXnPRJw5fwA1Ve6XM1ke3mMXZBN+XQ=,tag:tOYisvwBaQDboGZ4EroxZg==,type:str]
    TOKEN: ENC[AES256_GCM,data:RYDmtqaD1twZBMvHDidTRaQqrutZ2jlx8uBqny11m3BcoPnxx6ykzQ==,iv:vZvqhPKz967T6H8FaiiHnuxQkJ4HccL4hoPErVRt2vs=,tag:FXk40PuBQkiCbxTsTAUc7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGd0lnb3ZYdlJRS0lWTEp4
            TjVmRkZyMDdjOTJBT3kyc1o0bU9XU29qaGxNClN0SG5wckp1RXFGWmMvaGdjN29I
            cVZ1RnNhMTRMbjlXNE0zb2JyeDVKaG8KLS0tIE1oVktGN0lVbERFaDNiVFI2OHVs
            OGVqM2hCejRTMVR4UGlTWm5oZFFsOU0K9IAsXnbq5UrvgA9MH1Ub4Pv/Othrmzx8
            zXHzhJxqievyXtssbsb4D5OO/WLj4SZXV/33AiMyPy5v5S38bIKljA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T15:56:51Z"
    mac: ENC[AES256_GCM,data:ZouJecSlLQtLZPha/ByOOF34BWmnLTBvxze/v7KhHfWu4FoV8GklTEQrByg0LO1gIZsnTXsw3ac0i4fnseQo/t9oBnE8bzwpO0esWN5HZYKSD7bpKETB+g1CKf/wzkSTzqRIn9yISfqBuw8jMsZPpl5eVO6VYYSHPjlEieBkdRY=,iv:3S8gvIc4+u6OAWgj0jr0/Rl9TmIyrrbLUh7Uol9fLPo=,tag:PzZjKpeO1q+qVtDPYuBd7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
