apiVersion: v1
kind: Secret
metadata:
    name: postgres-cluster-app-user
    namespace: postgres-cluster
type: kubernetes.io/basic-auth
stringData:
    #ENC[AES256_GCM,data:vZvmz//AzV14IP/QIRLcjysdjBYh8J0LWT1mv/HdHZmsrtJL,iv:j8uly5IgI4EUcveiyCfAPCFr6EmQThAW+ZcPqvhzxRc=,tag:x0ioIJ2C0uHjT9qJSExGCA==,type:comment]
    username: ENC[AES256_GCM,data:S0IM,iv:hazQ+24/5bfcQ3eU2sRRyIgVPYa1VUE2BuY6DkDQiBE=,tag:rn3G/kY+VKnWzeQK2F5H/A==,type:str]
    password: ENC[AES256_GCM,data:lG7d8LFJjvCrNgd7uLIN3FXvvLgC0jmc,iv:HbOFrUf042QnM1O8FDV09ZpN8AFivsz00/rlOw5nRtc=,tag:pkQCx/yR2V8DAk8oRtZWOg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTUF5YXpmdFUrU3JmKzQ3
            MmVUSWJKa0VUYkNsMyszaE5na1BMV2hrR1I4Cll0Y2NFYmZ1MjlHZVRRK2V6RHRj
            bXBqQkFzQ2dUaHlhc0UzdUNuSjh4Vk0KLS0tIEZKQTlDN1ErLzJTd29ETFUzZFh0
            Ui9EN0xxaklBWGlzaWZibUw0K2g2TlkKsQoO8VdRc2Vm0CSvGbeQ1JUs8UKq+208
            /MSd4voK8XtW93QyGaY2tXx2TAtiz9tYxRJlUKZcl/u/7Ew3eyLVNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-07T19:13:19Z"
    mac: ENC[AES256_GCM,data:Zs3qF01+/rCD1uwjWdJByD3vg03SCOCu911AdB/bumxNBKxM/3hb2TDmnYT8GobxwKJ9udXXTmW090MP98/7F4rg5r7YO+T9NR7NY58JCFRvy6K5bja4iAXqkB5sVf4DUf9UyIc6a1W6SHD3/wehn2NRGm0Ar+TxI1HIIKHMvAI=,iv:OVYoOU4e+rxIWJEg3I8KhCiz4sPc2vhbq2ld6eAguMY=,tag:XDhZOTwOP30IhtwFLJGe9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
