apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres-cluster
spec:
  # PostgreSQL 16 - latest stable
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  
  # 3 instances for HA (1 primary, 2 replicas)
  instances: 3
  
  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "8"
      max_parallel_workers_per_gather: "4"
      max_parallel_workers: "8"
      max_parallel_maintenance_workers: "4"
      
  # Superuser secret reference
  superuserSecret:
    name: postgres-cluster-superuser
  
  # Bootstrap configuration
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-cluster-app-user
      
  # Storage configuration
  storage:
    size: 20Gi
    storageClass: blizzard-storage  # SSD for better performance
  
  # Resource limits
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2"
  
  # Backup configuration to MinIO
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: "s3://postgres-backups"
      endpointURL: "http://minio-service.minio.svc.cluster.local:9000"
      s3Credentials:
        accessKeyId:
          name: minio-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-backup-creds
          key: SECRET_ACCESS_KEY
      wal:
        maxParallel: 8
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 2