apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-cluster
resources:
  - ../secret.yaml
  - ../app-user-secret.yaml
  - ../cluster.yaml
  - ../loadbalancer-service.yaml