apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-cluster
resources:
  - ./secret.yaml
  - ./app-user-secret.yaml
  - ./minio-backup-secret.yaml
  - ./minio-root-secret.yaml
  - ./cluster.yaml
  - ./loadbalancer-service.yaml
  - ./loadbalancer-ro-service.yaml
  - ./loadbalancer-r-service.yaml
  - ./minio-setup-job.yaml
  - ./scheduled-backup.yaml