apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-db-setup
  namespace: harbor
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: setup-db
        image: postgres:15-alpine
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: harbor-secrets
              key: postgres-password
        - name: HARBOR_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: harbor-secrets
              key: harbor-db-password
        command:
        - sh
        - -c
        - |
          # Wait for postgres to be ready
          until pg_isready -h postgres-service.postgres.svc.cluster.local -p 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          
          # Create harbor user and databases
          psql -h postgres-service.postgres.svc.cluster.local -U postgres <<EOF
          -- Create user if not exists
          DO \$\$
          BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'harbor') THEN
              CREATE USER harbor WITH PASSWORD '$HARBOR_DB_PASSWORD';
            END IF;
          END
          \$\$;
          
          -- Create databases
          CREATE DATABASE harbor_registry OWNER harbor;
          CREATE DATABASE harbor_notary_server OWNER harbor;
          CREATE DATABASE harbor_notary_signer OWNER harbor;
          
          -- Grant privileges
          GRANT ALL PRIVILEGES ON DATABASE harbor_registry TO harbor;
          GRANT ALL PRIVILEGES ON DATABASE harbor_notary_server TO harbor;
          GRANT ALL PRIVILEGES ON DATABASE harbor_notary_signer TO harbor;
          EOF
          
          echo "Harbor databases created successfully!"