apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - namespace.yaml
  - repo.yaml
  - secret.yaml
  - database-setup.yaml
  - release.yaml
  - httpRoute.yaml