apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.13.1"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
  values:
    expose:
      type: clusterIP
      tls:
        enabled: false  # TLS handled by gateway
      clusterIP:
        name: harbor
        ports:
          httpPort: 80
    
    externalURL: https://harbor.horus.maix.ovh
    
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          storageClass: "app-storage"  # SSD for better performance
          size: 50Gi
        chartmuseum:
          storageClass: "app-storage"
          size: 5Gi
        jobservice:
          jobLog:
            storageClass: "app-storage"
            size: 5Gi
          scanDataExports:
            storageClass: "app-storage"
            size: 5Gi
        trivy:
          storageClass: "app-storage"
          size: 10Gi
    
    harborAdminPassword: ""  # Provided via existingSecret
    existingSecret: "harbor-secrets"
    existingSecretAdminPasswordKey: "admin-password"
    
    # Use new PostgreSQL cluster
    database:
      type: external
      external:
        host: "postgres-cluster-rw.postgres-cluster.svc.cluster.local"
        port: "5432"
        username: "harbor"
        password: ""  # Provided via existingSecret
        existingSecret: "harbor-secrets"
        existingSecretPasswordKey: "harbor-db-password"
        registryDatabase: "harbor_registry"
        notaryServerDatabase: "harbor_notary_server"
        notarySignerDatabase: "harbor_notary_signer"
    
    # Use existing Redis
    redis:
      type: external
      external:
        addr: "redis-service.redis.svc.cluster.local:6379/4"  # Using DB 4
    
    # Security settings
    trivy:
      enabled: true
      vulnType: "os,library"
      severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
      ignoreUnfixed: false
      insecure: false
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 1000m
      
    notary:
      enabled: false  # Enable if you need image signing
    
    # Resource limits
    registry:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 1Gi
          cpu: 1000m
    
    core:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 1Gi
          cpu: 1000m
    
    jobservice:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 1Gi
          cpu: 1000m
    
    # Metrics
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false  # Enable if you have Prometheus operator