apiVersion: v1
kind: Secret
metadata:
  name: harbor-secrets
  namespace: harbor
type: Opaque
stringData:
  # These should be encrypted with SOPS
  admin-password: "Harbor12345!"
  postgres-password: "postgres_password"
  harbor-db-password: "harbor_password"
  redis-password: ""