apiVersion: v1
kind: Secret
metadata:
    name: harbor-secrets
    namespace: harbor
type: Opaque
stringData:
    #ENC[AES256_GCM,data:kiZlOuefbHDuCWWc1zYCymb39ybHYMJ/vLNsxaeyOiv3CfJv,iv:ADy1CcvyekWyzsQnfY4HJhG+p7nG92gqhx3z4LoTXBY=,tag:QB9Yp4vixa4NzZyk0WvAiw==,type:comment]
    admin-password: ENC[AES256_GCM,data:crc6Q8w06llEuoizYV6hK2dk4AFTaeJy,iv:BszlO8AORljVzNroA0qqBwi2P4VNeGsjmmaKlpU/PzU=,tag:uXkuWoMMqMfuEMA4+x6xzQ==,type:str]
    #ENC[AES256_GCM,data:6zjwqkiuic7VyySTInQhRw7p2atDm+9K27gk6THO,iv:MeHJWFtirDuI0MCdKGqcAiSR9O0PFiX86B4f2PKl5w8=,tag:LOxBKVGrd9o5W0wjcScx6g==,type:comment]
    postgres-password: ENC[AES256_GCM,data:U23bbZmFdqesY33acRivoABEo2A0H+hJ,iv:mtydyrqr+602ot8sOZfMHe508llJoOnwBr393NK3hWM=,tag:wQ1uIa8mRRMjgrOT0F+yxg==,type:str]
    #ENC[AES256_GCM,data:oo/OSsEjYtMLhLUIj0f6IzmzWZq77pspAanwbmKY,iv:wVRGeBeuO7EhQRfnqv6WkJdeazG+KH3Vxzx/JD9r1zk=,tag:iBh5/5Ln7w1rOUwwB4MZrQ==,type:comment]
    harbor-db-password: ENC[AES256_GCM,data:gt6mb27/3IfFIHWSWFVfDiwusTKK2VZc,iv:ZeGn8wTzzArDXRUGIFujD/anMTIGB5/uC9eMY2QTHx4=,tag:L0t8IanW2V+/jqeJ61HrIw==,type:str]
    redis-password: ""
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bHJhNEFIQzVycjFjb0dw
            TVpmaGJmWVBydzQ2dXNhUGtkZE9ObUkwVFJ3CldwTC9EOGF0a1VQK2xmQnhsTDEw
            bjlNNWViN2Q4RTBzUW5LZEFnOGVRWEUKLS0tIEtJaTBSdWJVeFFoVC8yVlRWdkxz
            RkZjWVVFN3BWcjFXUmVieWQreVp2dEEKErPILfSph95xd8zc4F0AawhdqWGft7CH
            gWkaYB6Bhq3++RtIVgzWd5RXtAG8Whd9j5cL6XZ+Kx/3e90YNnY8Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-07T19:24:19Z"
    mac: ENC[AES256_GCM,data:6l2+1F8OZa4Er2dpOuzbwf6uwlyA3fbUNUriPRrP2ZpED/213tkK5bmLkWHCsDwMptcA6jSnpL/cSCu2w4+NaoHhoxx1WZDeeT5Sow/dOgKClEFI1tidXFfmA79+9MyrhyKrtdxvH/nA5Wpoe+YYl67+zdUBiwwOx8zduJgr214=,iv:2PWIw9LNNgpL/zmTJDHd3X7F3nuHk2qYeVt0zpU3P1c=,tag:CplIQkSZnrNCi9ixKKLTMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
