apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- sops-decrypt.yaml
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/experimental-install.yaml
- cilium-policy.yaml
- cilium-pool.yaml
