apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-csi-release
  namespace: kube-system
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: nfs-csi
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: nfs-csi
  values:
    controller:
      replicas: 3
    driver:
      name: snow-storage
    storageClass:
      create: true
