apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-csi-release
  namespace: kube-system
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.12.1
      sourceRef:
        kind: HelmRepository
        name: nfs-csi
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: nfs-csi
  values:
    controller:
      runOnControlPlane: true
      replicas: 1
