apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-csi
  namespace: flux-system
spec:
  interval: 15m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/
