apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: object-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.101.100
  share: /mnt/snow
  subDir: /objects
  onDelete: retain
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.101.100
  share: /mnt/snow
  subDir: /media
  onDelete: retain
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: app-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.101.100
  share: /mnt/snow
  subDir: /apps/${pvc.metadata.namespace}/${pvc.metadata.name}
  onDelete: retain
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blizzard-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.101.100
  share: /mnt/blizzard
  subDir: /folders/${pvc.metadata.namespace}/${pvc.metadata.name}
  onDelete: retain
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
