apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backendtlspolicies.yaml
  - gatewayclasses.yaml
  - gateways.yaml
  - grpcroutes.yaml
  - httproutes.yaml
  - listenersets.yaml
  - policy-validatingadmissionpolicy.yaml
  - policy-validatingadmissionpolicybinding.yaml
  - referencegrants.yaml
  - tcproutes.yaml
  - tlsroutes.yaml
  - udproutes.yaml
  - x-xbackends.yaml
  - x-xbackendtrafficpolicies.yaml
  - x-xmeshes.yaml
