apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
data:
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_MODE = prod
    
    [server]
    DOMAIN = gitea.horus.maix.ovh
    ROOT_URL = https://gitea.horus.maix.ovh/
    HTTP_PORT = 3000
    DISABLE_SSH = false
    SSH_PORT = 22
    START_SSH_SERVER = true
    OFFLINE_MODE = false
    
    [database]
    DB_TYPE = postgres
    HOST = postgres-cluster-rw.postgres-cluster.svc.cluster.local:5432
    NAME = gitea
    USER = gitea
    PASSWD = ${GITEA_DB_PASSWORD}
    SSL_MODE = require
    
    [service]
    DISABLE_REGISTRATION = false
    REQUIRE_SIGNIN_VIEW = false
    ENABLE_NOTIFY_MAIL = false
    
    [packages]
    ENABLED = true
    
    [packages.container]
    ENABLED = true
    
    [storage]
    STORAGE_TYPE = minio
    MINIO_ENDPOINT = minio-service.minio.svc.cluster.local:9000
    MINIO_ACCESS_KEY_ID = ${MINIO_ACCESS_KEY}
    MINIO_SECRET_ACCESS_KEY = ${MINIO_SECRET_KEY}
    MINIO_BUCKET = gitea
    MINIO_USE_SSL = false
    
    [attachment]
    STORAGE_TYPE = minio
    MINIO_BUCKET = gitea-attachments
    
    [lfs]
    STORAGE_TYPE = minio
    MINIO_BUCKET = gitea-lfs
    
    [security]
    INSTALL_LOCK = true
    SECRET_KEY = ${GITEA_SECRET_KEY}
    INTERNAL_TOKEN = ${GITEA_INTERNAL_TOKEN}