apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea

resources:
  - namespace.yaml
  - secret.yaml
  - minio-root-secret.yaml
  - postgres-credentials.yaml
  - configmap.yaml
  - pvc.yaml
  - postgres-setup-job.yaml
  - minio-setup-job.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml