apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data-pvc
  namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: app-storage
  resources:
    requests:
      storage: 50Gi