# Create a HelmRelease resource for the NFS CSI Helm chart
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-csi-release
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: nfs-csi
      version: 4.7.0
  values:
    externalSnapshotter:
      enabled: true
    controller:
      runOnControlPlane: true
      replicas: 3
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          effect: NoSchedule
          operator: Exists
