# Create a Delete StorageClass resource for the NFS CSI driver
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-delete
provisioner: nfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  server: "192.168.101.100"
  share: "/mnt/snow"
---
# Create a Retain StorageClass resource for the NFS CSI driver
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-retain
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  server: "192.168.101.100"
  share: "/mnt/snow"
