apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-config
  namespace: matrix
data:
  tuwunel.toml: |
    [global]
    server_name = "matrix.maix.ovh"
    database_path = "/var/lib/tuwunel"
    port = 8008
    address = "0.0.0.0"
    max_request_size = 20_000_000
    allow_registration = true
    allow_federation = false
    trusted_servers = []
    log = "warn,tuwunel=info"

    turn_uris = [
      "turn:176.149.222.82:3478?transport=udp",
      "turn:176.149.222.82:3478?transport=tcp",
    ]
    turn_ttl = 86400
