apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-data
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blizzard-storage
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-media
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blizzard-storage
  resources:
    requests:
      storage: 30Gi
