apiVersion: v1
kind: Secret
metadata:
    name: matrix-secret
    namespace: matrix
type: Opaque
stringData:
    CONDUIT_REGISTRATION_TOKEN: ENC[AES256_GCM,data:WEohwK5ZCDQxX8yFplSkEFp4O5K3P8bVnUMocAf3yPaTYN2xQRDEa9XHB3Ww0bHpJmyy86jShrOZz7EneVlgPA==,iv:vxCY7jdh+iHjSmfhcGXQdqMP6ZXJUD+RqdLj5Ub5NIc=,tag:eelZfDJCplGAsS4ppSze5g==,type:str]
    CONDUIT_EMERGENCY_PASSWORD: ENC[AES256_GCM,data:APLKk0eD+ZF/pa8eRnW7+J/cp0B8q/L7LC27/q5pRV9+ghQCyVywmZ2AFh0pn4DR,iv:/pvW+O5wERtpLfGUxfqesoTdDf3ziupTZM6IYucwoW4=,tag:cTHB4i6+EfCgFv19ia2Qgw==,type:str]
    CONDUIT_TURN_SECRET: ENC[AES256_GCM,data:HQhKwz9flFZvS1hyoB/VnjOvdD9JvXGx0hUtjUY8lZ6fBy1MuqxZ7amvfCo=,iv:mkZYLfZnfO6AtV8e0xCZ+6CXon6sstmvCvCHhU92TGQ=,tag:FOhc8Ga7zO1/qfkEX6gqHw==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGS2tIMHlzcmJ1R0k0TG16
            dWFJdFg5aC8wL2FjTDVMMDlZNkdDeXVZSlFRCjlRL2IwZjk1SjA4Z3hCalc1Y29Z
            d3lESXhIdDN4QTBLbmZsazZaek5IT3cKLS0tIEtxQ2FkaG1uRVZLVUxWU2NDV3I4
            Z2xjU29HWTVPTGpWR29tQUVLdEdnTEkKWwo5nVFI7iVfFCKtlmyG7e/bYGJUsV1f
            01/nlzKkiIkgcXWPgN1OVBhNeyMnN1TYeC8YBgxwR+2cNC14ph+UlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T22:30:20Z"
    mac: ENC[AES256_GCM,data:alEwuQUzbOI2HQyQ3ap6a6gbj+5Ngtfc1vQVulVGzWVV/1lgpDCF7ZQtYgIBMyNYyJymbcJflrPANBhDsgzWzF24DyGgOgpLxyrnf/vV7mjCxK3IwA7HcsNv1GLq+Z/qiuKI7L3Dtwu3wdvt8Rr9sX3goZUOQoPia5RrNUJ+WEI=,iv:4/khkuQyV2m/uSKwlv9O0+ETwmW6dJW916Axoj2kHJk=,tag:H5apFty1ccUB4c7hxsGwpQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
