apiVersion: v1
kind: Secret
metadata:
    name: zitadel-secret
    namespace: zitadel
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:vhqbusH2IQ==,iv:RllEohB7vrVrmNLwlO/XYWDORgKXOyUXUx5XShs9Pv0=,tag:ZijfkzykeWAHgi1Q+coXMA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Y274PBYMxl5PtKhhjgzNf+VMgxfpR3K22hLObdcqybM=,iv:yhU2ssBIBzFV21Icgo+NE8lIC+lGw/dEpTpfoiQGOIs=,tag:hHufLi/gRM+FiQuiT/+c8A==,type:str]
    DB_NAME: ENC[AES256_GCM,data:JTm2cceEpA==,iv:uh9s+ypdEN3pln5D2JfjVzHf3cUlFbChzNC7kRnPVE0=,tag:W4u+XcwciOdG79w77zCk9g==,type:str]
    MASTERKEY: ENC[AES256_GCM,data:17IM3xNT5LE2MjMYiVB/7iPKdAry2HClHzJu3PRxrsw=,iv:0A0Bh8oYOy5/ptQvVCLQ8sI0qSzhZRwfo6Fbc9chh1o=,tag:cjfxQm7se9VUkKd+OOs34Q==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:oG+DrlgoM4dOt4HsZXSRQbchVclr82TDz9Y=,iv:ytkOj+Jm9ZSQh+BgGoofL+sp/3t89+9goNkcSQwTC1o=,tag:mRsQxkAdTj0CBbOWr9oUzw==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbDdYbC9CM00wNXA4S21h
            eEMxVHZodmMxcDZJUlMwNEU4T25pU0l6MkEwCmdUWHd4cFd2UlRDZG5QczlsRG5P
            YkZ5ejR2Q3R1ajhCd3JRUEk2Ym9yd3cKLS0tIGZaeUVYOWxrRldlclNYeTJac0JH
            KzBPS21tQjZOYTZWQnNXQ1FsMDRHdjAKeB+LUiFWr2ZWENKY8hWtwZ6cMxcAKESd
            HzZbSk8UlGT5mnTgHa1trU/zimaCyEX3OYOXXzm5YdPvlwtxkWQ66A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T08:28:06Z"
    mac: ENC[AES256_GCM,data:L+f/xKoWc+8ogLZQ/Uv/d/o+r4eDf1jar6UKSmoQFyoN1bh6clMwWLt7yZrIdNac9DCmwJYfQoxC2Yimickkjm2G+l2HAH3+7kW7sebrF8b3HxTSCYZuWRpo9TM2BEHSaVF9hmR+8IuIv9dU6m3bsnloEbmMQxTt6LxxWCrQTok=,iv:hDNNpm7CpBRunk38Pwr2cXNsHfPyA136TS45AD01UmM=,tag:0T8g23cYmKgE8emMb68UBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
