apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: filebrowser
data:
  config.json: |
    {
      "port": 80,
      "baseURL": "https://filebrowser.maix.ovh",
      "address": "",
      "log": "stdout",
      "database": "/database.db",
      "root": "/srv"
    }
