apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data
  namespace: filebrowser
spec:
  storageClassName: media-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-db
  namespace: filebrowser
spec:
  storageClassName: app-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
