apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-data
  namespace: searxng
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
