apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reranker-cache
  namespace: reranker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blizzard-storage
  resources:
    requests:
      storage: 20Gi
