apiVersion: v1
kind: Service
metadata:
  name: reranker
  namespace: reranker
spec:
  type: ClusterIP
  selector:
    app: reranker
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
