apiVersion: v1
kind: Secret
metadata:
    name: usesend-secret
    namespace: usesend
type: Opaque
stringData:
    USESEND_DB_USER: ENC[AES256_GCM,data:uQnx5GQnYA==,iv:NH64nFw4/0MvUeiaK3egT6w8MNBJO0J+wK+abcqrCQs=,tag:qyAhkat7Q4rLO3+kXnFOXQ==,type:str]
    USESEND_DB_PASSWORD: ENC[AES256_GCM,data:Q53ixnRAUXQjzyiNdPGzZ9OoB/OH32a9NYqWZb2fahkFxC7HryTJEdnc9J5t/wsE,iv:er2QYuZMx0ZYlfOzkx2ihQWhRW6jGmjHeA29Mfv1sDM=,tag:N7UOEJiqgWWUkkD9a5jhVA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:wq9EsInRRqFecl393L3mZzQrnMGHT6//VjKVZ7MmgOzRgjQxcwOrvwWxljRJ50cG52RSBR8n3D1VmPacRTYrlufwW1dlLeWZM6RXm9WSN3Wo4zwq3/IKmDoS2n2idj9z9FsBICDcuvr3W3xKZf8CUDhykMBCaqmPjJBK7w==,iv:dqD3n0I5YRZasNHsBOnjodplhKb79V8AqXAR2HO5Y9k=,tag:69wVMNVeqrJ0bld2seC4aQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Ul1bXCB1QEXnPN3va4EfVnEDdj38Q4KT68SDRdMrE3i8d3/WHe00lu203WOAwBnaZt0=,iv:cvKW29DQW1JWHlyx9xkIs/XtG2VxxENbHHZNyTZ4+18=,tag:zmHB18Sq5/jfZ4U/GMP3GA==,type:str]
    REDIS_KEY_PREFIX: ENC[AES256_GCM,data:r7ivCPIwrQ==,iv:Vn2QF9u+US2O+P68pQwfEsShmmzhsThB/2WcHHPZSWM=,tag:HuOltsSEPig7a+fpS1JW1A==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:mtVKMhT/zInBEUhT78sTedJd1MYghhKdx/HB9shC,iv:SrysRc2x2CpWUOlAa5VSRWXH77MI4Xp4kcBW1CmkT88=,tag:AHCeNAXwYXlpJ17mSwtbDg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:kdyQ9DNB59FBV46vUZ+tcwsOhrcCEKEOThF0CukQ+0ffNt7OWrZMcGfiksI=,iv:ZnA8sGFv4MIJ8axzSddlfIQANTsNhq5g+68aEpayteA=,tag:SERCoYExdC4/aGo45dyZAA==,type:str]
    GITHUB_ID: ENC[AES256_GCM,data:ADC3grV+lL/tGCPPWdvQWx95TG8=,iv:htcdGwRealuIxXT7RzLjr7Dh/Ljae/KT++0qg5ScYp0=,tag:57LziUzvvBjKnQSqltP9/A==,type:str]
    GITHUB_SECRET: ENC[AES256_GCM,data:jeUFEJM2u1o/Y6AwBTC7k4RjN5Ttu1DVbRSGlsIdxiBksnIEiGHN5A==,iv:iMmkF0pclaTxcm1GVy/Fb40RpRQSXtL8RoPZtXW7FRA=,tag:uQmlw1cNenB1fgwwsY8b9g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pYZfq/JSsemmPeaAUvIuvOGVSCw=,iv:MF2P3G4XaR+TpxAjzzxryF8NY5FRc94TIi4SOMIVelI=,tag:snw8HJq4YCX/w/EuapwCbw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZDT55JqdIMRARR0lMWhlI2HMQxz3r+K9GRKA+Um72bsrrrzxrofagw==,iv:lzcy2HBxGjhawewABWyt1CCPaul2HHoYvqRI9BgrMZI=,tag:HVBb+yhLDV7D/DDnmEc4cQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM0dySXJhbFlVOWdrWUxZ
            TFIrRTBNN1dNVlprMzQ1bEk1VFVMckR4a3l3ClFON3FuZjJVK01mMFU2Vm90bmtv
            RjlpYmtZc0VKaEV4Y2orTEpJcTgvV0UKLS0tIEY1Z0Z3Zmx0YU9RZHdNbmVMUlBT
            MXdRY1RuUFdKY1kxSldwdFlmbXB3QmMKEQkKlWHdmCZBME4ZvhUzz1Nv94D5dv5T
            +94Vf5zxLgicVpT6ZnzXwcebH5iKPsDfigXTAB9KlCIDmgaEOWPffQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-04T10:56:07Z"
    mac: ENC[AES256_GCM,data:Qqi8Y9Lz4OSTKqB1cwr6tSU3z9y783dkLOrd1VHoU15JEXzRpX4ZoA4nKIi4ow7/1uv0+7OMEQykg7L4S9iaVl+vvmK4qNx+seR846DIQoOVBczaGY7mjQFcfxalafZXRTsbFn4JmiEzvbfHjk7BbFjW47Tj/LZy1EdbZZQETrg=,iv:teVIDihaLhcNNsL+Jqq0JG18CaOMGYygxswFU/31rH8=,tag:TdZkLFM0HrTVwaJgiyUFvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
