apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng-deployment
  namespace: search
  labels:
    app: searxng-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: searxng-deployment
  template:
    metadata:
      name: searxng-deployment
      labels:
        app: searxng-deployment
    spec:
      restartPolicy: Always
      containers:
        - name: searxng
          image: searxng/searxng:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: searxng
              protocol: TCP
          env:
            - name: PUID
              value: "1005"
            - name: PGID
              value: "1005"
            - name: TZ
              value: "Europe/Paris"
          volumeMounts:
            - name: searxng-config
              mountPath: /etc/searxng
      volumes:
        - name: searxng-config
          persistentVolumeClaim:
            claimName: searxng-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: search
  labels:
    app: backend-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      name: backend-deployment
      labels:
        app: backend-deployment
    spec:
      restartPolicy: Always
      containers:
        - name: backend
          image: itzcrazykns1337/perplexica-backend:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              name: backend
              protocol: TCP
          env:
            - name: PUID
              value: "1005"
            - name: PGID
              value: "1005"
            - name: TZ
              value: "Europe/Paris"
            - name: SEARXNG_API_URL
              value: searxng-service.search.svc.cluster.local
          volumeMounts:
            - name: backend-config
              mountPath: /etc/backend
      volumes:
        - name: backend-config
          persistentVolumeClaim:
            claimName: backend-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: search
  labels:
    app: frontend-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      name: frontend-deployment
      labels:
        app: frontend-deployment
    spec:
      restartPolicy: Always
      containers:
        - name: frontend
          image: itzcrazykns1337/perplexica-frontend:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              name: frontend
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://perplexica-backend.maix.ovh/api"
            - name: NEXT_PUBLIC_WS_URL
              value: "wss://perplexica-backend.maix.ovh"
          volumeMounts:
            - name: frontend-config
              mountPath: /etc/frontend
      volumes:
        - name: frontend-config
          persistentVolumeClaim:
            claimName: frontend-data
