apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 1h
  chart:
    spec:
      chart: keda
      version: "2.18.3"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  values:
    resources:
      operator:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 256Mi
