apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-researcher-data
  namespace: gpt-researcher
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: app-storage
  resources:
    requests:
      storage: 5Gi
