apiVersion: v1
kind: Secret
metadata:
    name: gpt-researcher-secret
    namespace: gpt-researcher
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:EjTNXtSxKiYO4dgTkDL634r0Y9MYr3oUJA==,iv:lPRTJcRxDL1AP0RYOpXI07Uyq53xS5E4ERlpnO2eEkY=,tag:PTcFenRZ0V90XWBwZxDSUg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SHBWN1FEcE1PMU55bFdu
            aWJPREl2eERadkdMSk1nV3RWS1JBOGhwY1ZrCnNTaThsVm9VUTZ1SGNLLy82RC9I
            bkxEbGlCRndjYXREQ29NMGJmdXluSjQKLS0tIHRkWXFscVg0UTN1MUlhOXo0UlhY
            M00yUVAyZloycHZkbitHd3R4RUo1ZnMK0Z8VGZYl81nA3A5BNfAlGWY0MKvUtrQN
            sfITJrQSwY332wkkFDfX8pR/VVKWwlzxNw5gpXtsFGCiPUpqEHUd3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T16:21:36Z"
    mac: ENC[AES256_GCM,data:Sl4oTLjIH/mi8KWa4pcXum7uVylFZLKMACOKWDGVxOPpcTT/0qWu4E36vpGW9E7FuQkyqw3du5EfXdN+Sz7i7qzLogQyhu08ll7ZniqAgBpaXI8hfiCz9e0J3FlBSFykpktdDJ7dCfCBpZumyLCUN0dz3iuCCAa5Y0wliG0uvzk=,iv:QLWoXHy1vmLCLfkiM7EbUlsJmdLkqXQBHmlWw8gI39c=,tag:PV9n1gYbx5mcKqYzqvRx9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
