apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-data
  namespace: readarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-data
  namespace: readarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-media
  namespace: readarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: media-storage
  resources:
    requests:
      storage: 100Mi
