apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fission
  namespace: fission
spec:
  chart:
    spec:
      chart: fission-all
      version: 1.20.1
      sourceRef:
        kind: HelmRepository
        name: fission-charts
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: fission
  targetNamespace: fission
  install:
    disableWait: true
  upgrade:
    disableWait: true
  values:
    defaultNamespace: fission
    persistence:
      enabled: true
      storageClass: app-storage
      accessMode: ReadWriteOnce
      size: 1Gi
