apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-db-init
  namespace: authelia
data:
  init.sh: |
    #!/bin/sh
    set -e

    # Wait for PostgreSQL to be ready
    until pg_isready -h $PGHOST -p $PGPORT -U $PGUSER; do
      echo "Waiting for PostgreSQL..."
      sleep 2
    done

    # Create database if it doesn't exist
    psql -tc "SELECT 1 FROM pg_database WHERE datname = 'authelia'" | grep -q 1 || \
      psql -c "CREATE DATABASE authelia"

    # Create user if it doesn't exist
    psql -tc "SELECT 1 FROM pg_user WHERE usename = 'authelia'" | grep -q 1 || \
      psql -c "CREATE USER authelia WITH PASSWORD 'authelia'"

    # Set ownership and privileges
    psql -c "ALTER DATABASE authelia OWNER TO authelia"
    psql -c "GRANT ALL PRIVILEGES ON DATABASE authelia TO authelia"

    # Connect to authelia database and setup schema permissions
    psql -d authelia -c "GRANT ALL ON SCHEMA public TO authelia"

    echo "Database initialization complete"
