apiVersion: batch/v1
kind: Job
metadata:
  name: authelia-db-init
  namespace: authelia
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: postgres:16-alpine
          env:
            - name: PGHOST
              value: "postgres-service.postgres.svc.cluster.local"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: authelia-secret
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: authelia-secret
                  key: PGPASSWORD
          command:
            - sh
            - /scripts/init.sh
          volumeMounts:
            - name: init-script
              mountPath: /scripts
      volumes:
        - name: init-script
          configMap:
            name: authelia-db-init
            defaultMode: 0755
