apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-library
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 10Gi

