apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-release
  namespace: authelia
spec:
  chart:
    spec:
      chart: authelia
      version: 0.8.58
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: authelia
  values:
    redis:
      enabled: true
      enabledSecret: false
      host: 'redis-service.redis.svc.cluster.local'
      port: 6379
    postgres:
      enabled: false
      address: 'tcp://postgres.databases.svc.cluster.local:5432'
      timeout: '5 seconds'
      database: 'authelia'
      schema: 'public'
      username: 'authelia'
