apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  releaseName: authelia
  chart:
    spec:
      chart: authelia
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    pod:
      kind: Deployment
      replicas: 1

    configMap:
      theme: dark

      server:
        port: 9091

      log:
        level: info

      authentication_backend:
        password_reset:
          disable: false
        refresh_interval: 5m
        file:
          enabled: true
          path: /config/users_database.yml
          watch: false
          search:
            email: false
            case_insensitive: false
          password:
            algorithm: argon2
            argon2:
              variant: argon2id
              iterations: 3
              memory: 65536
              parallelism: 4
              key_length: 32
              salt_length: 16

      session:
        name: authelia_session
        same_site: lax
        inactivity: 5m
        expiration: 1h
        remember_me: 1M

        cookies:
          - domain: horus.maix.ovh
            subdomain: auth
            default_redirection_url: https://horus.maix.ovh

        redis:
          enabled: true
          deploy: false
          host: redis-service.redis.svc.cluster.local
          port: 6379
          database_index: 0

      storage:
        postgres:
          enabled: true
          deploy: false
          address: tcp://postgres-service.postgres.svc.cluster.local:5432
          database: authelia
          schema: public
          username: authelia
          timeout: 5s
          password:
            disabled: false
            secret_name: authelia-secret
            path: storage.postgres.password.txt

        encryption_key:
          disabled: false
          secret_name: authelia-secret
          path: storage.encryption.key

      access_control:
        default_policy: deny
        rules: []

      notifier:
        disable_startup_check: false
        smtp:
          enabled: true
          address: smtp://smtp-relay.smtp-relay.svc.cluster.local:25
          sender: "Authelia <noreply@auth.maix.ovh>"
          disable_require_tls: true
          disable_html_emails: false

    secret:
      additionalSecrets:
        authelia-secret: {}
