apiVersion: v1
kind: Secret
metadata:
    name: sprite-secret
    namespace: sprite
type: Opaque
stringData:
    SPRITE_AMQP_URI: ENC[AES256_GCM,data:dB4prGAeDaDEglgrYOWIHWKxu8pdSMJE/TkLXLiuwp1ft0A07Cbfi+ITu+H/lnOtriG7rrIex/wVMwUPUl8zJLb1ZdJlNc1sndj9KpUVAO4T8mwCBdaveEnx4p2zQWK9/gAB/imxv9VDFSKFypYUd1lkEEp04Q==,iv:RNBGU72Or0Hz6ByHjzXn7pJCbjU8jE6rDapZCkUOjSI=,tag:YnmaWNi9F6sAkyGKG0tTdQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxa1p1M0xYZG9FZWQ2N2Fp
            WUF3dGRkK3NoU3FTZE9aN2UrMzZoUkNsdEdNClRoNG05MDZhbXRxQkFvWDhucWV3
            WDlTS0ZxTGV0NkpGTDlmTHhVd0UvNXMKLS0tIEJ2cUd0b3c3d3c0c2tyeUc1cmtR
            MGJZWkRVQ0hkdGl3eHpHb2VEa2dld1kKtljzSQtbBkz9SQyqHf4IUf/dFE9ox33o
            xgzsF9AbwPekUbee31KtzA1QACM5tSYDBgJKBrWhH8vdmCdCddNh+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T18:06:42Z"
    mac: ENC[AES256_GCM,data:lIAgiA3/BZRq2H4sk4ZpixCtePufls6+D5hkoIQZiNyT+Gb0LYUGT0oRy719ejYoo+1o3kL7ClShOrFQx7WlF99FoEE7ak+/R+GsUNSJYEM2wdw2DqocQ3bo3kpPjwBwBnWLjgF8xYaG2tpLJ/EQuVRBSeY4l/3Rdqx4WWcNqng=,iv:3SM5MV/KC0w1Hmm1Yptx23R7Ozp1gr6actexQ7kRYK8=,tag:Vaq3mWfefwTqjdJDTxradQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
