apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voice-sidecar-model-cache
  namespace: voice
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: blizzard-storage
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voice-api-data
  namespace: voice
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 1Gi
