apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voice-agent-model-cache
  namespace: voice
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
