apiVersion: v1
kind: Secret
metadata:
    name: livekit-credentials
    namespace: voice
type: Opaque
stringData:
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:Jh5SEpjr0ZbQHA==,iv:9bhlnUFE2LDUllGXsyayjUJeWifoSjt0Uv5weZsiZJE=,tag:2TZONeru+GuQv6dRGBsKpA==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:WvwQkAV935IHheyO07PjH0x7/nf2UjXFbljMXaWXEntODWpXaHGZNAK+vpc=,iv:XsZ7ZoZvo9/8ZVicbLknt/coOgGpZR/KaKHCl9wC42U=,tag:mYe6pykQb0vLeEiZnjsMag==,type:str]
    API_KEY: ENC[AES256_GCM,data:T/Hdk46AZUaf5SHBRrD4VYNYUJ63wUGVyTIyC3jD9fA51588M5qh6oD36oc=,iv:UZmwRLfYZab4ibrqmgcFRaJnlWlz9iJQCn15vd7Bo98=,tag:9UdWsJO7cOTCcHwXTwsQcQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbVFBMGVzU09PQk9nSDRZ
            ZVp0c1pZM3dlellEN2xFcnRYdXpTTm1CM0VnCi8yVkNnc0NHSVQzNVdzUHBJOGpT
            RHhBMm1vQmlkYU1CN0xiU1k2L0RWQU0KLS0tIFlTUlIra21HckZXeXVSc1Ayd1hR
            dENYcldDcDFnSHBEb0JtQUdqYXY1dnMK2uKPrmcp89yIxxaTDi0GfEIr0X/5ISaf
            Vzq5wJaFxsCyZBwtNstLNCTzMRMQ3yBamo9bBWOjsfRT9+Kc6Bj4wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T17:25:49Z"
    mac: ENC[AES256_GCM,data:beUZmEx3QSUBubOR6F8YymAokGKxGldfBKR1vnP//xJelP9cnhF2D94nMsmRI5RKKKJgTm1J5aLhOCFd8/ynrRXZt1Gw93ygFD527TJbP2yhRxy7+1dHUxJQIcVINvVsnR5kC46yFphB8s+fFK7xw7gHYGkecVdC96cMV68x66Y=,iv:LZxEU3IjdqoaPmXB2DkWqOOQ3ONvqvP5isIn3GzF+a4=,tag:YJZzB22rAQDH+VmPfYK+CQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: livekit-config
    namespace: voice
data:
    livekit.yaml: ENC[AES256_GCM,data:I0hlRP/9lwPUfg0Ccd/CdEUQGLwQpLR7fnd61SEAFb2uZGrVdNf+SIsdibK079LcCLdjYDqQSMdE0Vf/hHi6NIogkQ0i0APtKoZwluxTKnZPhvHwwAOHJq6ksmeVsF8+vEuZS/3XO5FfgwobRoywj+IUIF92J+kD87AEgWtdWTnefRVG0AezXyCShLXfZgAxO+wgP+0k5IVffC7XXkAQ4OgVuBsyknib2UPT8GQhsHEiXtQTMqOC3HQcK806osfyCmkDmkZ38fvlW2cbSWARy65J2rPEvhBqgSYPmYhRyr+UKd0Ln3pRc5hSj/5+AsHCvDdcEFtdw+OBf9tzHHiOAX8PvCbXfv1y8LGyniPv7hzE86lfNeK+BZsKSHAwbFs47pMFSLPKGUgCkVZc/xL6PwvC8QgjjNTcrIxGEV126Gkioxxm8Ig/R3wu9HM10Ij2d/NdSejCwCcldQE6mDMe+y8+S40Qkfwq/Aq/QEI/0u+dbobvenVb9NUREsj/u8jbDLpRdbvDiGJayJ48YcE30roDfzJvaClPMJ7GI3a/MTxO2e7gxLdj8eqA+W3PD7rSVpqr041XAlRFnq8w2xMy3locFvN/e1wKpB04os3VqPmhvi6bIICPyeLuj9u3Rr19ktJu6w==,iv:Vuq0r5fOnhe9M5KgIra5SPV/XBdQg0tVK1G/lI4aToc=,tag:xyj3FWj3KHnsOcaHGLj0aw==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbVFBMGVzU09PQk9nSDRZ
            ZVp0c1pZM3dlellEN2xFcnRYdXpTTm1CM0VnCi8yVkNnc0NHSVQzNVdzUHBJOGpT
            RHhBMm1vQmlkYU1CN0xiU1k2L0RWQU0KLS0tIFlTUlIra21HckZXeXVSc1Ayd1hR
            dENYcldDcDFnSHBEb0JtQUdqYXY1dnMK2uKPrmcp89yIxxaTDi0GfEIr0X/5ISaf
            Vzq5wJaFxsCyZBwtNstLNCTzMRMQ3yBamo9bBWOjsfRT9+Kc6Bj4wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T17:25:49Z"
    mac: ENC[AES256_GCM,data:beUZmEx3QSUBubOR6F8YymAokGKxGldfBKR1vnP//xJelP9cnhF2D94nMsmRI5RKKKJgTm1J5aLhOCFd8/ynrRXZt1Gw93ygFD527TJbP2yhRxy7+1dHUxJQIcVINvVsnR5kC46yFphB8s+fFK7xw7gHYGkecVdC96cMV68x66Y=,iv:LZxEU3IjdqoaPmXB2DkWqOOQ3ONvqvP5isIn3GzF+a4=,tag:YJZzB22rAQDH+VmPfYK+CQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
