apiVersion: v1
kind: Secret
metadata:
    name: gateway-secrets
    namespace: voice
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:Pf8QsyK52DI2LoHGbdJm8taO5eZ2nz7ZGhII5tN/0lA=,iv:CkSaaPjuVkdwMpjcIXPu72LVcusYTwHJT2etHbZpaKQ=,tag:ACX1DYp050E36HUwpSiUEA==,type:str]
    DATABASE_DSN: ENC[AES256_GCM,data:PQYqXAzljzaqgxN/h/ItXhzz9GyTtwJNQRSxF39oKKyJ+bJovuqi77GK+dSOqmFiyTRPiuL4NiVSxV+CvF7Es4JJjwSl6Uhi36kJ+jm+AoGHre9ZtKmUog4s7VFt4zt6mY0jGcjmpowvdrd9W8M=,iv:pxKq2jMHafbMcobZoHUpQ2kiRZe1zKnINdLhJqD74p4=,tag:DpsE2GUtkcJjaPqV9C9Xbg==,type:str]
    REDIS_PASSWORD: ""
    HMAC_KEY: ENC[AES256_GCM,data:LUq8J+4gfAWCVKXFtQ6FCp81dUStdwPAzQickftyjcHz4buu7mODHIM3Fds=,iv:4hwEITIL3ThFDp3t09a7weUnHM9Gf3ZzE7iK0TZSUTQ=,tag:CC4jLXBZTlfHlFtZqDU6VA==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYmpWQmE0d2lOaG80YXg5
            Sk9xMVJ6dUxLOU0vQTMyVEJxdDBQQnQySFNZCnJERFkvRGJnR3U4RWNBa05JRWl4
            NHNwd2txWDJGaHRQME5BOW81MTBJN2MKLS0tIG5sSWJqTWVtNjdUS1JMZGY2NDcv
            cUNNRWYySjlvaUpLdUlvYVRITTNyNmsKfWCQ92lA7y04iV+7fmXZD5Dq8SHOB5VW
            LGi6ibljY2G8hhzH3ZbjgWapzt1wJ1HQLuu/GMMqjV8+RO3qgSCAKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T19:10:51Z"
    mac: ENC[AES256_GCM,data:jELzApb5Ojp31RM8O7ex777b0e9EO9YdeZQQTcMGz3gyuRx+B4fRyyqpmpMxGsKyIRuODdled78enABha6/lIZ0TpqFTqOsarJBe82LUXwHVqRNKnlXEKFj0IBKH7Op6OWROT6YB0O5sjif/jrOQeYPuxyLrDNsc7/PPhm0t+bU=,iv:/pA1LVM6gfbBQJTCGwfjJcdNbkhfvOIBCMaND8yHfJ8=,tag:wjmdw784cXZAvMiGM+BrRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: memory-secrets
    namespace: voice
type: Opaque
stringData:
    NEO4J_ADMIN_PASSWORD: ENC[AES256_GCM,data:unDNUi48TjO/cYo44XfEmmIMgGM=,iv:EoOZD4sf/YyRk8OTMYxyvevZ/JPmhjCeBDatHq2MAEE=,tag:O3rvamDCFcZqZkrV9DYizw==,type:str]
    NEO4J_USER: ENC[AES256_GCM,data:/JmqRtLkZxX8Nlkt,iv:uqLxG4BG10br+8CXe648op6NRYDYCK/sXm6brpAezxc=,tag:7IbSxAX+XnqqW1SCWH4b4g==,type:str]
    NEO4J_PASSWORD: ENC[AES256_GCM,data:FfNU/XA12ODIvcPty97/39QRHYl9hcf6dbmLg4VdL8Y=,iv:hP5tUsULMXOd8yJPz5mr/q0S28KLrP4pDwi7NS5i7EE=,tag:Av2bo5ZapNtINW6UvykBww==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:qfXq0wyChzDmVn7E,iv:TjH7FOsUoXH2XqZJkNtp2bDMa+PCPN/Mlh5gzZv0oNU=,tag:PLQ/tSB9nLnCNDDMUmCgfA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:21liLZjiRAwfC3n2GQknGtRDN0XZeHzcmVSRY69weOA=,iv:ROnwHWe+vmljZZ58yVLLr+MEsZeqaomC+v0HwSEBhb0=,tag:9BM+E1ZcVsChnoFoeJEcoQ==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:FhlAbequ7wXE,iv:lLJcdlembEDUDX8tNITTwEs+7rvegTkKPEzkGvPDiu4=,tag:PXeV2q3DQ3aOysOiwt+OXw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:67lD0sybTBqn+ozC6joWk6F86xM=,iv:1KvvGNnEYEWXiYjmFGoHnAPsUXxn/5eOvxI+jBX4ra8=,tag:H8tllrVtJEo0XbmxTxDLuA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:WGNGRNcoJY6Ycqt9,iv:QAehbFylfCiEupXEISIxK/prKixo6TEG1pyadUtJXxY=,tag:KJulO9b1ctpz8bRVH2V6zw==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:Sjd3vYjAQdFaON/h1+sCCl8lQVozChNmq0PpC2aDN+5+LYt4NHB7p4CnGD8=,iv:8nSyHFBEmzreNPa8xG9JtttemY3apV1eMz53phK9WNA=,tag:d58VmNxEWY3+iGaY71Pcyg==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:1u7LDWYTCrk5gw/vJ/iRXeIcJI4dsX+R00CCD7swsU5IT0fTc/7POomDuSkdxwV+Dt6OFqi/t5NOXwltxyfMfdjWq9xlns9JcFOiVW8c4wLVFDZXKdWTE/a9XlIOEB7StMq4Y7zlI0Dlf8sc,iv:GQNmqfIUM0XfNqZwUXgLID4b665Jv9B/QmxGh4iyMOw=,tag:kpmxz640CfYaOL4RbeS68w==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYmpWQmE0d2lOaG80YXg5
            Sk9xMVJ6dUxLOU0vQTMyVEJxdDBQQnQySFNZCnJERFkvRGJnR3U4RWNBa05JRWl4
            NHNwd2txWDJGaHRQME5BOW81MTBJN2MKLS0tIG5sSWJqTWVtNjdUS1JMZGY2NDcv
            cUNNRWYySjlvaUpLdUlvYVRITTNyNmsKfWCQ92lA7y04iV+7fmXZD5Dq8SHOB5VW
            LGi6ibljY2G8hhzH3ZbjgWapzt1wJ1HQLuu/GMMqjV8+RO3qgSCAKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T19:10:51Z"
    mac: ENC[AES256_GCM,data:jELzApb5Ojp31RM8O7ex777b0e9EO9YdeZQQTcMGz3gyuRx+B4fRyyqpmpMxGsKyIRuODdled78enABha6/lIZ0TpqFTqOsarJBe82LUXwHVqRNKnlXEKFj0IBKH7Op6OWROT6YB0O5sjif/jrOQeYPuxyLrDNsc7/PPhm0t+bU=,iv:/pA1LVM6gfbBQJTCGwfjJcdNbkhfvOIBCMaND8yHfJ8=,tag:wjmdw784cXZAvMiGM+BrRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
