apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale
  labels:
    app: headscale
  namespace: headscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale
  template:
    metadata:
      name: headscale
      labels:
        app: headscale
    spec:
      containers:
        - name: headscale
          image: ghcr.io/ifargle/headscale-webui:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: HS_SERVER
              value: https://headscale.maix.ovh
            - name: DOMAIN_NAME
              value: https://headscale.horus.ossai.dev
            - name: AUTH_TYPE
              value: Basic
            - name: BASIC_AUTH_USER
              value: 'eleven-am'
            - name: BASIC_AUTH_PASS
              value: 'headscale'
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 80
      restartPolicy: Always

