apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale
  labels:
    app: headscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale
  template:
    metadata:
      name: headscale
      labels:
        app: headscale
    spec:
      containers:
        - name: headscale
          image: simcu/headscale-ui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
      restartPolicy: Always

