apiVersion: v1
kind: Secret
metadata:
    name: khonsu-secret
    namespace: khonsu
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:g9fIE1Z32btdUXIoTE49Y3HEgS684fHS0CZ3CtQ/63mY9WPKrUWDMoVTlhw=,iv:+JImCectbz8a2BqeK1d4ueKYrr+sWiX7WFuOiJfXD9E=,tag:5GjW/uvj+wk6krBEFS8gnQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Xr6v7foAkHB6YhDKQDIZ,iv:aQWo1nSSJiBhvPa1rfGsU53JylVZpYIYU7NmQtsq2Gs=,tag:tm6zostyHX4vwD0hLtvBmg==,type:str]
    TAILSCALE_AUTHKEY: ENC[AES256_GCM,data:MRpn103scA2lrKEtj3ziX6dNOlVUmMArBJXelJrSFd7TCPNmYHMCRh0EwtyQ/LbQ,iv:S0eWtq4dbacz3CNnEVZjozGSVgWUgfsDClMRwinEhW0=,tag:IXooN/Uj9XsmEMwzB53rFg==,type:str]
    TS_EXTRA_ARGS: ENC[AES256_GCM,data:OlmPMa5JBqA9tDTtz+p9PDxGguYkDbhekrVdgXAyEvaAXnrzEI4nUoeNznyUQSrgcZeMsUPceDQuLzwYWWGw,iv:4e0bC8+TfCVFAF//g40GDjVIayiq5YLV7NArIuV4fIQ=,tag:yG/QBEoBUOXpv8cTATSzww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eUczSjRVSXBDWUtZYWNS
            VjFiM0l1R1ZScnFycm5vdkdLVXFXelBuNkhVCk5KcW9taWpjL2pHajJoY29GTDlw
            cjdSRU9rN1FkdGRqRjV0NUNqWmZZVkEKLS0tIGxlS2hvbndsNVhwd1pxbFBLRERR
            ZkZweWhaOE5neDB2OGJreGhta1VOcGcKeYimTPM3gPJszVcqtxhjd0MtVtJMj0gF
            R9QMBiMG8kX0OJ82to8U7BrMzm5dlvUBVENbZ5cQj6Iqeycew4rFdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-19T22:37:00Z"
    mac: ENC[AES256_GCM,data:fFA4mcO5Ti9XNERIT9l/30hbo2iOkJ5htVFtvx60so7nd7I6uuYbB2RgiBD9tlGPHKgMS4aRyPm5I4y3yCpAhNX0MZWTsf1fE1LLbyXLS3ZKP/8vr7lFCbwSqdCYijWF4qanVF8YBYZ2ZoUQWj9yJaalw1Oc8OXXnvqbJy4t4u4=,iv:r9hyRBUXI1XncKGaLmoZjGJouYhsKiYjS493iEtwNiI=,tag:ShNLwrTE6EMQDbMIY+7TRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
