apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: open-webui
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: app-storage
  resources:
    requests:
      storage: 5Gi
