apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: radarr-route
  namespace: radarr
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - "radarr.horus.ossai.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: radarr-service
          port: 7878
