apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-data
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: object-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: object-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-media
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: media-storage
  resources:
    requests:
      storage: 100Mi
