apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr-deployment
  namespace: prowlarr
  labels:
    app: prowlarr-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: prowlarr-deployment
  template:
    metadata:
      name: prowlarr-deployment
      labels:
        app: prowlarr-deployment
    spec:
      restartPolicy: Always
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9696
              name: prowlarr
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
            - name: prowlarr-media
              mountPath: /media
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: LOG_HTML
              value: "false"
            - name: CAPTCHA_SOLVER
              value: "hcaptcha"
            - name: TZ
              value: "Europe/Paris"
          ports:
            - containerPort: 8191
      volumes:
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-data
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-data
        - name: prowlarr-media
          persistentVolumeClaim:
            claimName: prowlarr-media
