apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
    namespace: prowlarr
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:U90M/dIdEgq5fZ3pXdVvAfUNfBGVabn7nIKU7eKmW7AshfDMu5howada7qg=,iv:LRZt9zcbNsPbLEjTPNY5B+c0G+DYy57rmWhwfKO7HjE=,tag:0VNDWzJXvFgK6aWZ9yDkhA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:h7fO6j+UBE6kWVgQbw==,iv:JgJjsnv18OymrllYWK5U6dV2GoP3aRVgLKBoLsT+gjE=,tag:NRXY1Vd98b6ZlKifs/FveQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdWtKdFg3UkZka3RMZ09R
            U1JZenk0VFYxcmhMVzlXaHVsNVQ3bitIZVhjCnBJN2IyL0x6QmV3bXNjcEpLZHZ2
            eG1oTE9hRXZsVUtFc1pXY216TUE5c0UKLS0tIFpGbGh0WlFWMXIxVlRyM0NlTEcr
            eXZ4K1A2TURJeFMvdjc1Uk9qdkRSVVUKIbB8OndOHoTeUSOx/dBXETPEidHsPC51
            22PXPXtp30fBRfgJSVRXW2u52Xq14IC9lz7LJc4lqfAmhxVxt5CaZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T10:41:41Z"
    mac: ENC[AES256_GCM,data:zuV3/OFbMXtLiL9iW2gBuZ5unf5xwdEPHgGel3sK7X0XtXojjplRUL5mRGvwEiloJ/PdKYMu0amQoR5PD2hriIzNNvVFNoDVIuZqShTTopqyFNwCZeoBT1UxiyyQKUMljPUPsWV/Y9I23sxoj5vQjFsZWh96p2ByRd7WZpTtpeY=,iv:a5XCO3rXIhHBAVCIvaey4EmZ0gTlLyB3kzketazawv4=,tag:eR4uE2qrlscfimAJYi9O3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
