apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: 1.80.0
  interval: 1h
  values:
    oauth:
      clientId:
        valueFrom:
          secretKeyRef:
            key: clientId
            name: tailscale-secret

      clientSecret:
        valueFrom:
          secretKeyRef:
            key: clientSecret
            name: tailscale-secret
