apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  chart:
    spec:
      chart: tailscale-operator
      version: 1.84.0
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: sops-operator-oauth
      valuesKey: client_id
      targetPath: oauth.clientId
    - kind: Secret
      name: sops-operator-oauth
      valuesKey: client_secret
      targetPath: oauth.clientSecret
