apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      version: "*"  # Use latest version
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  install:
    createNamespace: true
  values:
    oauth:
      clientId:
        valueFrom:
          secretKeyRef:
            name: tailscale-credentials
            key: clientId

      clientSecret:
        valueFrom:
          secretKeyRef:
            name: tailscale-credentials
            key: clientSecret
