apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      version: "1.76.6"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  values:
    oauth:
      clientId:
        valueFrom:
          secretKeyRef:
            key: clientId
            name: tailscale-credentials

      clientSecret:
        valueFrom:
          secretKeyRef:
            key: clientSecret
            name: tailscale-credentials
