# Create a HelmRelease resource for the Tailscale Helm chart
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tailscale-release
  namespace: tailscale
spec:
  interval: 1m0s
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
      version: 1.64.2
  valuesFrom:
    - kind: Secret
      name: tailscale-secret
      valuesKey: config.yaml
