apiVersion: v1
kind: Secret
metadata:
    name: tailscale-credentials
    namespace: tailscale
stringData:
    clientId: ENC[AES256_GCM,data:5q0aZJzfOlVuJuEvALksnP8=,iv:S6n3vJWZFG0+bnl3j8qKo7OIJkUgU+0YVitNp4GzwsE=,tag:csA7echNgGspHj8uV2u/Kw==,type:str]
    clientSecret: ENC[AES256_GCM,data:u8Q1aT0hAv86XdQgplUFuYcQd/H1DsSG83U2jhzRJqaLtaAKPNUdRIS3tPFX66U8r1sRc+41fxS/hKtn3AtljA==,iv:WhkzHr9rIWM+/FgvU3ecN5/q45LvSiwZK7lzwLIQDiY=,tag:fpmZxZqVJXZyVyVl10KZSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobDhhM3BEN0RMRmNsbUs1
            M1lVSnpHdloyRU9tQ3hDZm5IaENyVWdCQ3k0CndRS1RnRk9CaHVVOStFVk9MZU94
            K0dSUWQrQlhFQXVBNWRZc1dZcER1azgKLS0tIEJqQ2VqQU1uUDVRUFY1aDFVV2Nq
            RTlXMTUxdk9oS214ZzM1akJBejI3WUEKijMLVg37lhnowKRWBekm3VMOciRY1sij
            B3BuM7f4CZERvtAxDFC/fFOWeaUm5Wv5WDtTduvzKbE7wWWcALO0VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T14:52:05Z"
    mac: ENC[AES256_GCM,data:WV/EeR1GuTBX7VPFrzgNVQtE0xFrB5yOtCf8iDss/l6G7Nj3HivpFEmhBGCj8D460ndABLidfRXU9rwZ+iRe0MHPnnexqK8HyJVP2ICWj1msL5Nxi2vOwBR80UWRLl31lx3eWavFrj7csjCO3WwqNU/sCC6P1BBl95uB6iVxrfA=,iv:1gou4AAZudwgV4zvzW0iqN9Q9a/ZDVStzPWjPdvhZQE=,tag:BDuxsuIha5ZWG6/drJ/LXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
