apiVersion: v1
kind: Service
metadata:
  name: vllm-reranker
  namespace: vllm-reranker
spec:
  selector:
    app: vllm-reranker
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
