apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webhook-router-pvc
  namespace: webhook-router
  labels:
    app: webhook-router
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blizzard-storage
  resources:
    requests:
      storage: 2Gi
