apiVersion: v1
kind: Secret
metadata:
    name: webhook-router-secret
    namespace: webhook-router
    labels:
        app: webhook-router
type: Opaque
stringData:
    rabbitmq-url: ENC[AES256_GCM,data:jZEFsGetu+2Q3mTJ/eoKrBUTzL+MS5pjUd0tkCmaP7E0ryF65iOWBHMYjfyd2K1GfrmWMwv5Jd9wyjptHd8SFMTp6IVFuh9i9UPEznyGj8eg+qAKjHbTbhMI9Enwo8pUgR3jNQw0XMrZt+b3cQPKHyZL/5FlDy0lt//YeaONLu16,iv:4Kt4dxNC6u1h1dx6U9ABVu58Ezb97dl3u8CKdb3edJE=,tag:BbVeckjUrsRtw7+fC+7NsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bFhkSUQyN2Z6UTZhbjdR
            RlFhUmNNNlFldVhvdjduYm5PRmloV2IyY1FjCjIvZnJRVTJGV0VKUFhhM0VYNVd2
            Nnh3R1dIc0xiZDZCTUt5NDdUbS9jSTQKLS0tIHUyemhPOW4rWHM3NS9ZbmN6MStL
            WmJ2aTc4cW5wUXFPWnoyY0lQRGdsUEEKnMWVnwBLdGUZIyJ0t8g3fKdR5rx0Z2EJ
            yNBd72v6TpXHjJP7ingAl7z3zKfJpoV2VpuU7LS2KM91jS4yovX6qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T21:48:03Z"
    mac: ENC[AES256_GCM,data:+5XoFq+9e1CCMgTH924H9SnH04vZplENUOBCVj0pmeQcfGgU8k+fCljCpcAIBWobPUSZt63oobKta9dVrmifrb03MvJv905dHVGOxDVPN0ioKZ/BQ6dKIdjaPIe4MU3r/I3GwW/zYUGQGdbfmlbmseGcmZe8MNFR3YP9iLHLJYw=,iv:sxbrqKmze/1K7f/lvBiB4u4OFy0xmAzZxhvKY8Dvelg=,tag:xAewCB2byF+c23ImtzqY+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
