apiVersion: v1
kind: Secret
metadata:
    name: livekit-credentials
    namespace: livekit
type: Opaque
stringData:
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:k9maotMduHN5Bw==,iv:ljUhJ7GfQYZhia35Y2eorDExqKc7A2plG9xSORA5qrs=,tag:sCDB0J1HS6CZxIE4l19RqA==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:BF2p2ObJYD9mLFXfVHpZ2sN+xoKitiBJAuTr+fU6ZTTVxyWdnwyEoz3WIAA=,iv:2FaPIZo8Yb8KYQd0MzrjZ6Kwne5BQ1n09vTGYGhsJwc=,tag:piwDX6mm+nO/Y9F6gI/O+w==,type:str]
    API_KEY: ENC[AES256_GCM,data:o5c4Ck4fvhPlVccE/7yOx2fW3HF39JFIUFsIkQlham7E/xTB+bpm59I93lk=,iv:6BFPVOR7tWLsyrD2PFyr41ESJVLWx1v+8mrwHN+l8is=,tag:kkToxmUIgGxiUOvxfDA9lA==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d0Z0S0dqamxydXY5ZFE2
            a3lmSndSU1plbHNSNmxBZlkyVE12NTc2amh3CjNTN2JLTFcyLzVZVmdLclA4QlFh
            dnpuSzBBL29hZG9IQ2hVNllOUTF5ejQKLS0tIFdEcjhXWmhQMVJHTGpJOGlQYTJB
            NkFvalJtVzF4QVZyTDlwMDhzbFVrZDAKmS5L19C8kgD8TpLA87u0byEq/jcohVot
            O/loa69nNAKh+VcO5kJcborKHGhLeNlt0IA1e+zv2UGceiYQEvSFng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T11:00:59Z"
    mac: ENC[AES256_GCM,data:mtz79yMBGR1ZNTW8adlZwhRqpNtt3uXgJ+tGi4wxrdsgyEGsOz1r+A+zcFwvdGk0tM0KdDpbnF1VObORxluQmccGlkZz2npYsgPTGdBX0dcOIZEZhri2a4dQK9fSU/MIMx/JOk092uBneKUrjGrqnnfEXi9B4XgtecfU17qIPfs=,iv:V7MDvjfvoCbJFcKMVxn6zF2jEhlv4FnoSTtQF41VDd4=,tag:FwlQ7OEgPNhho5euDCuEvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: livekit-config
    namespace: livekit
data:
    livekit.yaml: ENC[AES256_GCM,data:+d7fPpNrU0a5Gl/3dMy5QG9ovghBHTGE+lHct4AndrY2yL3v+ARHAUm2FZL/RpUu1Bj2zX5KnbbcEu4TqTT3Tu4pTkDutsj3FxcanCcJVugzUUymREJvaINEkhLwyST5o/AcwCKb2FKS6IbDOkjd14KlOAPyJSBqzOH8R00UYVpZZ1fU3xSedgJiLXuvVQDu3LMJJP+a8dsPJD7DmAXu1l9g8vf47UuGFuGBm9O/HNiyZlaYc/h09Q1kTUWRVtWGbaPTfTW7o+duW3yUA5N40Stnv3CPPPWj2/HAxRVCaQYWajVdva++AJMT3JuhYIWwGQvEnJ2CHslna/FWwKatdaO8y9uRu4qCe2bRyWckaFxQhpwQJHpSM7EMysRjFQW5Gn+qgNoF36iUR8izEX9oNeK21wiyC8sYpCourQ==,iv:ZRxMJxqbwnC/8j59hi7bzHaLlF4HSdsBTVaclz9gqqU=,tag:jWTYw02O0fSwWWRC3UDz9g==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d0Z0S0dqamxydXY5ZFE2
            a3lmSndSU1plbHNSNmxBZlkyVE12NTc2amh3CjNTN2JLTFcyLzVZVmdLclA4QlFh
            dnpuSzBBL29hZG9IQ2hVNllOUTF5ejQKLS0tIFdEcjhXWmhQMVJHTGpJOGlQYTJB
            NkFvalJtVzF4QVZyTDlwMDhzbFVrZDAKmS5L19C8kgD8TpLA87u0byEq/jcohVot
            O/loa69nNAKh+VcO5kJcborKHGhLeNlt0IA1e+zv2UGceiYQEvSFng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T11:00:59Z"
    mac: ENC[AES256_GCM,data:mtz79yMBGR1ZNTW8adlZwhRqpNtt3uXgJ+tGi4wxrdsgyEGsOz1r+A+zcFwvdGk0tM0KdDpbnF1VObORxluQmccGlkZz2npYsgPTGdBX0dcOIZEZhri2a4dQK9fSU/MIMx/JOk092uBneKUrjGrqnnfEXi9B4XgtecfU17qIPfs=,iv:V7MDvjfvoCbJFcKMVxn6zF2jEhlv4FnoSTtQF41VDd4=,tag:FwlQ7OEgPNhho5euDCuEvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
