apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
  namespace: smtp-relay
spec:
  selector:
    app: smtp-relay
  ports:
    - name: smtp
      port: 25
      targetPort: 25
    - name: submission
      port: 587
      targetPort: 587
  type: ClusterIP
