apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tyche-data
  namespace: tyche
spec:
  storageClassName: app-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
