apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: janus-data
  namespace: janus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: app-storage
  resources:
    requests:
      storage: 1Gi
