apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  namespace: qdrant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blizzard-storage
  resources:
    requests:
      storage: 10Gi