apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-cluster
resources:
  - namespace.yaml
  - repo.yaml
  - operator.yaml
  - secret.yaml
  - app-user-secret.yaml
  # - cluster.yaml  # Deploy this after operator is ready
  # - loadbalancer-service.yaml  # Deploy this after cluster is ready