apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-cluster
resources:
  - namespace.yaml
  - secret.yaml
  - minio-root-secret.yaml
  - cluster.yaml
  - service.yaml
  - scheduled-backup.yaml
  - minio-setup-job.yaml