apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-lb
  namespace: postgres-cluster
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres-cluster.local
spec:
  type: LoadBalancer
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    cnpg.io/cluster: postgres-cluster
    cnpg.io/instanceRole: primary  # Only route to primary instance
  sessionAffinity: ClientIP  # Stick to same backend for connection