apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-lb
  namespace: postgres-cluster
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rw.pgc.horus
spec:
  type: LoadBalancer
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    cnpg.io/cluster: postgres-cluster
    cnpg.io/instanceRole: primary
  sessionAffinity: ClientIP
