apiVersion: v1
kind: Secret
metadata:
    name: minio-root-creds
    namespace: postgres-cluster
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:vI8vAceFI9Jl,iv:exSrEdAZ/OA8ViM5FgbrhTRD6h+uLptAXKLZKVqt0iQ=,tag:9IVgwJ0sX6FUEbwlmn+kRQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:lrq7ThVLeLngfZ06FN7g0yaHsAo=,iv:agrA67/KmL/jz1fdEfHfo9fYaMd5eEdCV3gfLvo7fGs=,tag:JNEFmoBiBsZ8LV9vx95Y/w==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQm1PNzNKNVNVbDhlZ3Jr
            RWRucE80Rld4VHdKZEoxZmc2ZG1YdkhmVVhNCkpFd2tnZEo2WGIvcjhNVXlKSUE1
            UHJOTmp4eWhmMTNSb3Fid2p1RzJwYW8KLS0tIHlFMDE3WVJ2c1RHY0NFaEUrYi9k
            L0k1ekxXOC8wbkJaeEwwcS9USUFmY28K0cRIlNMl473i0FGbmoWJgVaiSxN64/ao
            SvY/lOxaJdRAPu3gHltte8RsrtZyxoaBoG2FYIF5S4o0x3i/8qyv7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-08T07:22:22Z"
    mac: ENC[AES256_GCM,data:LvHQj19E52F+gSEBuE4qAdQmCP+3i2V5rYFVCNtNKfYEKGuHSenckMDEPyFHX1tDIdtQ56IOnKDpje0TJVG5nd0jtmG35ynZNxkRS7QOPD42MKp21Pmru7vcuIxXRLqwT1sBpCcpRDZeOiumB8AO45WeUj+IB+YWAs0OOtiz6l8=,iv:JcPxUcbHHEXF6o8edOseEbZOexVTr1SQDp7+cLrZW+c=,tag:NGbofcnDfA3vCIZ940tlew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
