apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: postgres-cluster
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.20.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: postgres-cluster
  values:
    # Operator configuration
    replicaCount: 1
    
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    
    # Monitoring
    monitoring:
      enabled: true
      podMonitor:
        enabled: false  # Enable if you have Prometheus operator
    
    # Webhook configuration
    webhook:
      mutating:
        create: true
        failurePolicy: Fail
      validating:
        create: true
        failurePolicy: Fail