apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blizzard-storage
  resources:
    requests:
      storage: 50Gi
