version: '3.9'
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data/npm/data:/data
      - ./data/npm/letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - backend

  headscale-admin:
    image: goodieshq/headscale-admin:latest
    container_name: headscale-admin
    restart: unless-stopped
    networks:
      - backend

  headscale:
    container_name: headscale
    image: headscale/headscale:0.23.0-alpha11
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data/headscale/config:/etc/headscale
      - ./data/headscale/data:/var/lib/headscale
    entrypoint: headscale serve
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
