version: '3.9'
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data/npm/data:/data
      - ./data/npm/letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - backend

  pi-hole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "7070:80"
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - TZ=Europe/Paris
      - WEBPASSWORD=ziqpYw-katbup-kihzo6
    volumes:
      - ./data/pihole/pihole:/etc/pihole/
      - ./data/pihole/dnsmasq.d:/etc/dnsmasq.d/
    restart: unless-stopped
    networks:
      - backend

  headscale-admin:
    image: goodieshq/headscale-admin:latest
    container_name: headscale-admin
    restart: unless-stopped
    networks:
      - backend

  headscale:
    container_name: headscale
    image: headscale/headscale:0.23.0-alpha11
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data/headscale/config:/etc/headscale
      - ./data/headscale/data:/var/lib/headscale
    entrypoint: headscale serve
    networks:
      - backend

  mullvad-paris:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data/mullvad-paris:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=xxxxxxxx=
      - WIREGUARD_ADDRESSES=x.x.x.x/32
      - SERVER_CITIES=Paris
      - TZ=Europe/Paris

  tailscale-paris:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./tailscale/var/lib:/var/lib
      - ./tailscale/state:/state
      - /dev/net/tun:/dev/net/tun
    network_mode: "service:mullvad-paris"
    environment:
      - TS_HOSTNAME=airvpn-exit-node
      - TS_AUTHKEY=xxxxxxxx
      - TS_EXTRA_ARGS=--login-server=https://example.com --advertise-exit-node
      - TS_NO_LOGS_NO_SUPPORT=true
      - TS_STATE_DIR=/state

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
