apiVersion: v1
kind: Namespace
metadata:
    name: mullvad
    labels:
        pod-security.kubernetes.io/enforce: privileged
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S1d0ckl2NnR1N25IVFBQ
            cFFWbVVTdTB3NitQNERhY1gwbjhvR1htS213Cm44eHhPa2lKMXlFQ1B3dHNpUXFP
            UGdCQ0M1YThaVWlHRDhjdndWaDFrc0EKLS0tIGNSeWVudlFmY0FIZkRHNWFnc3pz
            djlPNzBVTnpPak4rYUp2aytJWmp6ZWMKdhgCm785xaO4xjOikiF6C2hGIC1Hde8l
            7hZxktgfxzOd8U1e7kzhE6Ye9Yv8J7kniPUTXg1xdQ+5zYnwTJzqpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T09:54:26Z"
    mac: ENC[AES256_GCM,data:yiRTBzZTc+/oyoIOeAV+eOPGclhasYzvsasuNM4Wxkk5vgxoEkT/XM1E8WZUY0bKfcexVyuYGCSUADH2RsJLdLZqupBHhRrJyJwCzQ2SpCpojAT056teM0p2uJavkHh0GWK1o55tKUFoHWC37TeiVPLeTUjw5kzGVrG+s4jDR7A=,iv:NLgT7dxeHXzwI8/SxrG/frezgv/fzzyXmGStFNrKz5Q=,tag:OHswmdBhChcuRsNovklKiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: gluetun-data
    namespace: mullvad
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    storageClassName: app-storage
    resources:
        requests:
            storage: 100Mi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S1d0ckl2NnR1N25IVFBQ
            cFFWbVVTdTB3NitQNERhY1gwbjhvR1htS213Cm44eHhPa2lKMXlFQ1B3dHNpUXFP
            UGdCQ0M1YThaVWlHRDhjdndWaDFrc0EKLS0tIGNSeWVudlFmY0FIZkRHNWFnc3pz
            djlPNzBVTnpPak4rYUp2aytJWmp6ZWMKdhgCm785xaO4xjOikiF6C2hGIC1Hde8l
            7hZxktgfxzOd8U1e7kzhE6Ye9Yv8J7kniPUTXg1xdQ+5zYnwTJzqpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T09:54:26Z"
    mac: ENC[AES256_GCM,data:yiRTBzZTc+/oyoIOeAV+eOPGclhasYzvsasuNM4Wxkk5vgxoEkT/XM1E8WZUY0bKfcexVyuYGCSUADH2RsJLdLZqupBHhRrJyJwCzQ2SpCpojAT056teM0p2uJavkHh0GWK1o55tKUFoHWC37TeiVPLeTUjw5kzGVrG+s4jDR7A=,iv:NLgT7dxeHXzwI8/SxrG/frezgv/fzzyXmGStFNrKz5Q=,tag:OHswmdBhChcuRsNovklKiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: mullvad-secret
    namespace: mullvad
type: Opaque
stringData:
    TAILSCALE_AUTHKEY: ENC[AES256_GCM,data:TblPxP6Gh0Wjcpf1nepbPrBkwBf3Sg1ccAs9z7cRjxwOV+fxsimXPp4rEVcC1sWR,iv:bTOEINR+w3UMwbG3gMrkY7PTNqruUtXCY5PFjhRQ0/U=,tag:Ldvf4UMKkBcVuMD+KOk2ig==,type:str]
    TS_EXTRA_ARGS: ENC[AES256_GCM,data:czg/19FR02KNPkYsTHt8t92NwxzmWAUmyDzu/l7JglLPuLIWjpheQMT+76HWwaGjkMguShZnSpTWHnW1QJGfeE4/jCrOLFL/mWMmm+CW+GLN6g==,iv:7TBTJVnIFLoPMTvKvzlLbuuMu/tWoKy3vJyNOL4BFoM=,tag:dprbRieN9g8EMu/TcHyelQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:VCVoWEn0oixJat8IB49wpE03R6N6/R1MsbvlPFTEiCikaGbVSr1BNdzTgno=,iv:084uFiyK6j6CC44bS2r58uk4r6cfBYNZ1yKP74Gd9fo=,tag:pKqE7TFLJq5f7brVRPbA1w==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:NnA7hUECqNCkIc3/sDtsBA==,iv:tb8BTRu32VRnV5dN69MCG25ukFQcwmzfDfaYB+PNxMI=,tag:+SlCvVF+K8KqdVeXIeuP+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S1d0ckl2NnR1N25IVFBQ
            cFFWbVVTdTB3NitQNERhY1gwbjhvR1htS213Cm44eHhPa2lKMXlFQ1B3dHNpUXFP
            UGdCQ0M1YThaVWlHRDhjdndWaDFrc0EKLS0tIGNSeWVudlFmY0FIZkRHNWFnc3pz
            djlPNzBVTnpPak4rYUp2aytJWmp6ZWMKdhgCm785xaO4xjOikiF6C2hGIC1Hde8l
            7hZxktgfxzOd8U1e7kzhE6Ye9Yv8J7kniPUTXg1xdQ+5zYnwTJzqpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T09:54:26Z"
    mac: ENC[AES256_GCM,data:yiRTBzZTc+/oyoIOeAV+eOPGclhasYzvsasuNM4Wxkk5vgxoEkT/XM1E8WZUY0bKfcexVyuYGCSUADH2RsJLdLZqupBHhRrJyJwCzQ2SpCpojAT056teM0p2uJavkHh0GWK1o55tKUFoHWC37TeiVPLeTUjw5kzGVrG+s4jDR7A=,iv:NLgT7dxeHXzwI8/SxrG/frezgv/fzzyXmGStFNrKz5Q=,tag:OHswmdBhChcuRsNovklKiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
