apiVersion: apps/v1
kind: Deployment
metadata:
  name: mullvad-deployment
  namespace: mullvad
  labels:
    app: mullvad-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: mullvad-deployment
  template:
    metadata:
      name: mullvad-deployment
      labels:
        app: mullvad-deployment
    spec:
      restartPolicy: Always
      containers:
        - name: tailscale-vpn
          image: tailscale/tailscale:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              add: [ "NET_ADMIN", "NET_RAW" ]
          env:
            - name: TS_USERSPACE
              value: "true"
            - name: TS_EXTRA_ARGS
              valueFrom:
                secretKeyRef:
                  name: mullvad-secret
                  key: TS_EXTRA_ARGS
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: mullvad-secret
                  key: TS_AUTHKEY
          volumeMounts:
            - name: tailscale-var-lib
              mountPath: /var/lib/tailscale
      volumes:
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-data
        - name: tailscale-var-lib
          persistentVolumeClaim:
            claimName: tailscale-data
