apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale-admin
  namespace: mullvad
  labels:
    app: headscale-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale-admin
  template:
    metadata:
      labels:
        app: headscale-admin
    spec:
      containers:
        - name: headscale-admin
          image: goodieshq/headscale-admin:0.24
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: headscale-admin-service
  namespace: mullvad
  labels:
    app: headscale-admin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: headscale-admin
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headscale-admin-route
  namespace: mullvad
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - "headscale-admin.horus.maix.ovh"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: headscale-admin-service
          port: 80