apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base.yaml
  - secret.yaml
  - tun-device-plugin.yaml
  - abeona
  - ankou
  - hermes
  - meili
  - sedna
  - shurdh
  - tia
  - horus.yaml
