apiVersion: v1
kind: Secret
metadata:
  name: mullvad-secret
  namespace: mullvad
type: Opaque
stringData:
  TAILSCALE_AUTHKEY: ENC[AES256_GCM,data:LcHcCGTqgIMY2xJV0EYUU9ElhYAQDAWwf9O8J7M/5KHDi6S6eoDGx6N5MRrQPfYE,iv:6X5ozs6OmzA0rKNDnG+J/lO8Rrvk/7g0x0MT+rU8LZM=,tag:0IneMtGQjQWqHnVzDUYYSA==,type:str]
  TS_EXTRA_ARGS: ENC[AES256_GCM,data:HugjqGLjGAdAsv6DtUIRgZ8YKxRv1iAzYoGwtplrHzHRosrmZm0YCryYMnQVHVSCscd1NUscJqjogBgqg1cc8wMafEfA/7zWOzBmzk0jAy2wilWuZh9696KIHF0PjaVlphOYQA==,iv:ZuA9eQFZfYdwySRKJv6IYTO4ZBUqViRLX8rbwaEI2tY=,tag:bwIyDUosuZ6ggULSbiU0PQ==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:FZ65n92hDFESCXRz2BToIwNsYOgrZHJOAS/+yoc0yZShDEungFkVg/KoxOU=,iv:sGHdmKZBi491xBZlRP9udWtvHcxvTiFWcjjXUXF5Lv0=,tag:azHnDlqxIE05xagppbRImQ==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:1tWzSiW6kqSTVJm4AQ==,iv:mg9CUmw0lPbdyK5xLDn919wseWIL+yzIg2hOXuTOFPg=,tag:/PAOP2g/KqFXyU88ooQUwg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR1FtVGhkU3hGbGJYU2g0
        RitNM3FUKzlJYmF1M0pFNjZWSDlFb0E3UlNrCnZMYmhXY3lNSGp2bmp1VjdUYXBp
        K1JUb2QyM0hlT3FpaXN0V2RZNHI5VkkKLS0tIHgyS0RabU5GaGp3b2p1dGxsYUd1
        cnVMeTlBV2MvRFV4YmNmczhWVE02QjQK3Ed+DyGBpIgkSmdk+7t7N6kgq3mG15TD
        7B0NHRbkFLtI3sfqgZLwFmvh4TxBrdTSvw8qnM7cDZijWfYtJgfC1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-25T13:56:21Z"
  mac: ENC[AES256_GCM,data:oUh1iGhRA18n1L21cAyoNQ2L5zSr7ouOuN9hiJz0rlTdkaMA8nt55AKejfA3OT9ow0V6VCVXSV6q8Qvi4K36e+Qj2t2wiYst3PizNxVvU+bpWyDVTsnHJFFUUBNhiq//4p0m3ezs7t1b4S+qRdgWSH7BwMf2fjukc8PP8RuQEIQ=,iv:q7Z22tgIA0ZYUGRnR/3LCeamYhUcTYEiZD4C6IUIgWY=,tag:t2+KRlsz70PiEAmh7LS1PQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
