apiVersion: v1
kind: Secret
metadata:
    name: mullvad-secret
    namespace: mullvad
type: Opaque
stringData:
    TAILSCALE_AUTHKEY: ENC[AES256_GCM,data:sIMAZtY1WOHlXZKcff4Orxfkeb/WyrNR7rW7b2Zaj+7xCvbc09J1aAGFWa/nhk6P,iv:dWlDDMjs6NW8EGK2hZCZzqx7gmnWUOdPCdCVAAkL10M=,tag:i5Me7cJJZVlOLTm1362PGA==,type:str]
    TS_EXTRA_ARGS: ENC[AES256_GCM,data:PyCAhEVoh9XiIal2/hsUUjRhVLhXSLqJgAn9G12hpB7GovTxoPrCwn9Q6qKiOpDAWslFdExH1GfonAFA,iv:BOqhDUF0Cx3w0yOjhMRgWBzPR0F8qaWLOOdSBAubm2I=,tag:Q3zY+/x9zmJJTCD9IebEUw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:XcC4N3EoBpA9rMxCp2F26wYC78QZn9y4TqbwgmOMEQJR5Oscxr7WyL22eSQ=,iv:fFS5Wx01GF1qLLeK1lgR//LHvLfXdaN45TFPCZDpilo=,tag:9zx7AxiYL/hIkaHY1N5EIA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:tO70IzvGGrFOUaP6KA==,iv:/GvbO+zwpQ+J6Q9dn2OkLdgbw4dPqDRXRC78X7YaxUE=,tag:55CuVX4D0HXLmwuZ04mM9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJN3pBWmhIZXp4WGxVaEVO
            UWdmTGszeEdPNDRwOEhXQm9yVXNId2hSMkhZCm5rSm4yZTllaG5JRVQ1NDE5Sjcv
            VE9RMUtpQmNLS2FKN0xzUEhBaEZnWVEKLS0tIHl1SXNNUlkwNFN0VDdFVFcyUlVD
            anVqQWZ2TUNlSFkwMTFUeENobWNBKzQKcTxVgMwwzgvde/zDxRsw/FUw1brytxNz
            jZYbIeLv+rylLST6xet+gaLVFkdrUsdfJSiNH54KFxlALq7+h5SOCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-25T07:06:10Z"
    mac: ENC[AES256_GCM,data:ZQRD1Hs6PxV5rgauRDrlr2i3au3s6Iax1XbQm8Q1GRqNBaE1kQhxmSNTfQiUNqXrSRuXHGpoKT0xNkJZbZhpldvVkPrB1JrCJpdNr8UofadsMOpDd0e5BjgH93aiEL9b8i5QhBGS3QR5qsKLqvCPoKrtX6zyzq0XspFy677z9sA=,iv:1LspPVAIW0n7RzWwR9qBlpcfDCHiWSRYCqKn8Y8VVT0=,tag:dO3bLIn380GYSfJg/uzBcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
