apiVersion: v1
kind: Secret
metadata:
    name: mullvad-secret
    namespace: mullvad
type: Opaque
stringData:
    TAILSCALE_AUTHKEY: ENC[AES256_GCM,data:P75/qpRuLAynaovyyranzLVvGgMSU0a1X+sw3u9S0gyGeDjPSvRoNNn6SXCFZXb5,iv:7MOR+FzBTwWOE8HISASWbf4w2uOxXW8MzsC4ePf7s2M=,tag:+mqs5VDFFSxaq3JolzOx5w==,type:str]
    TS_EXTRA_ARGS: ENC[AES256_GCM,data:Hmu+gwyIWGgaPwBRoxg1wbD7ajpigRWK6ckEIdhgGAZgz190Ay4CIMvbRkbe+S/1F+3eQM4YWcVFOuB+Wk+0WqSA40NEQa/CaflCLNs1Ck8jG//T8WA9CafAaAzKmjwR35o=,iv:EcUtfmG6d4tLbUdYwT8dvkYyXoDLslhT9m6yiAoRO1g=,tag:G33pQ33UmlJFef8dvSP6rA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:wQdA0I8daiwcHhvP1r9HKTpcbgJirPQrn9f7BYMXxZG3RqFe54NplLmoP7U=,iv:El3klUugaRVO/H5flX1AVW2gw3kBhjTAus/QWHV2u6o=,tag:YsWWSJIG/H8sI42hylLPRQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:NTVOFgZnkSzkTeXpxgvw,iv:vy1pypHXON26FqH5u3khk5WX46DIUm31dZ5xaHJV+pQ=,tag:zowzCf54bADtX0eEiJI7+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TzlQbmp2c3pMdzNmVGVa
            V240eDNnTVBKbFBQZC9KQVJFejdsaUZWaEhBCjdiR0kzNlRaK3hLN1pYOFFIRXpT
            dmEzZm5yRGdBTXdJTlhuZWhtSE5uSTAKLS0tIEtaR0lZV0M1U1E1cUJaSHV5YlVh
            MW55TGRPTEFQcWVPU0YxeS8wSU55WEUKY329IdDAsHnYOZhlxtMhG1mUqK7YL1LV
            mGfzRDHnW7OwaxvG+PEmpBYFyKCpbqxw6wUWFKAxspsxPcKZntgp/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-12T09:09:42Z"
    mac: ENC[AES256_GCM,data:f+/N/Ix1UV/UxLVyy5dcbT4zM7GQ3afD3UWgzxqtb6T4unhFXsr9MRsiFtMZDDq9grAiLRULwfvZlYA3tJVr26jQzx8kGtTEWe1lUIIHPi2BqcNwbOtwi9alRYBKl+pE1d8bTERcxsBHgfMeGP0m90BGqlOzqL+D9iE/QuWKzc4=,iv:EAav1JbsDhUYGMaFsOnyqaSbrurhRIEVIknL/XA6xzE=,tag:X0hQS926k7rjwL/DKo0MYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
