apiVersion: v1
kind: Secret
metadata:
    name: zot-helm-secret
    namespace: io-platform
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:nutozEbretJ3ZAStFuRqDIx5,iv:6IKZ5Qfp7k4RGJaE1aySW7O1Sc2Y9FN8FPfEWKJQ5QE=,tag:24y3yTKdPnFF3TiqqUYJXA==,type:str]
    password: ENC[AES256_GCM,data:l7cbx2yTkYnF52cbs/zGm8Sv+/T3Sqr01IjnTCRJrvaVLiRM,iv:sxrXiH1yWt/XUlGjz5xpByAS7LPGo4MIG/oiLj0rBnk=,tag:xp3teP26zzMYKz+4ijJjpQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR2RIbi9nRGtmKzVFakZS
            Q29BOG1yYVlweWxNSEp0N09EU1c4bXVRR3dBClI0aVZKb1lXUkxBMlh5RE1ua2lJ
            TTVkZ2pMSjcxU0kwc1JsNEMrSnRBNXcKLS0tIG05WHg3NXNmQU5ha0l4dFdpN0Za
            c2dKMjhDM0xyYXJOWUUxakNPU3hGcHMKAXS2qF5jIstLYomLzfE83E5rjRXTArSZ
            X1W8r+bqjhNYoBvJ7Ra7w6z/+8MuTmhhNIuiRVZ2qwDO+09BfJy36g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T15:20:55Z"
    mac: ENC[AES256_GCM,data:nwMvhHh/abdQQ/BcywqCSv5qq9R7RVuXx8Ry7ceBl6/ycR2/KGHr94yBoqBchMvNJs1NEJ1wMAVzu4NsjhwkTB3HQKKDciA+6ZaIMg2VVuiikKVIQqUY66uNooDJ/EK7jBVXmjrzJpwg9wWbROC0rATG9AvVq9Il0CQlde/JznY=,iv:xfJEdNZFfkXTU8ecy2MHhOZzFFjKycpIvyHXAMwyDLo=,tag:Qx5oE7N0pwnXjBXlvu9NAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
