apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: io-platform
  namespace: flux-system
spec:
  interval: 10m
  url: oci://zot.maix.ovh/charts/io-platform
  ref:
    semver: ">=0.1.0"
