apiVersion: v1
kind: Secret
metadata:
    name: io-platform-secret
    namespace: io-platform
type: Opaque
stringData:
    ADA_BEAM_GRPC_AUTH_TOKEN: ENC[AES256_GCM,data:DC4snETWbHZG6NeU6JfrV+T3RNN6LdrredSrDOMu1+ahDMhixaFmWQbsLhRx2WsF6AEDVIPXarJFaWPV7T/ICQ==,iv:OM2tIpQkOBv6TGYzWQbUahP71j2KYQ5g88Iiosq/LkI=,tag:o/G76RogSL+3E2rlUvd5cg==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:KbSacmHXf46Yvtp/UlR+ecddbol6JEHCg2oxxItAMLnomVBGu7KXz8Wc0XKYZkYJGWNhHBW2RJM/2xML58mmQA==,iv:DwoR3SOR+l5gh67BAYopQjTm1YcppRUXwot0yGTlb0k=,tag:tJ619++ZLQvbLMux9doSMw==,type:str]
    CLOAK_KEY: ENC[AES256_GCM,data:OEK9L/wodCY4ENjnm2cDWAttsuhiisqV2WfVRAe2kF/i278Vc8M2pqPx9hM=,iv:vbmHc1N7u0dylxB6xwYtURrtbP8fcfSosLZyc/Ymenk=,tag:RfUP7oHTi9TznejDU9UmEA==,type:str]
    INTERNAL_GRPC_TOKEN: ENC[AES256_GCM,data:7/1nhBFsMCEQOf4/YoGak9ZXnGDKRhou6lUkfPDXK8naI7lGPeZ+9HIXUR6ZnCsI7iv42/PHCuvLZbAdYOkcpQ==,iv:tPrwTdVM7k6rAmvX9WHh6W5odt69iGvkN9vW6oYLyCE=,tag:viU4yj1EglZ7c1OA5XuicQ==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:4Z513OOAS6Ft9n+lf13VigRXXmrnMUmPrQ==,iv:D/yP5QPIof1eVz+lAuZ57iZ0Msi1DXROUXPXRcfMauQ=,tag:sx7aJu5G1u33+S9m7n3qzw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:/Bpz3h4OTrqqAK7HuiP6pTNoE0a/tXxZ/AVxZdo0tTM=,iv:1ZrswHEcOytT64Ir7vUHZQsJQEk38plfNSgiJtjQH3g=,tag:FPvsmXGhEDe7X9UPiV7d2A==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:CwN2BRlksy+79g==,iv:7S+1d/Sv5oC3LPQdADXOWKLLdjudkUlaZjzras/R1DI=,tag:VOesy0Nsk0pkvQbvKscJPw==,type:str]
    NEO4J_PASSWORD: ENC[AES256_GCM,data:w/1U7+vUWIWWlwXPcVcYSy+VLx/yBYyEf6IrbjtJK38=,iv:Q3YHgOoF9yqQy8b9yHhpw8xLrGp6x/qBxzjsbXjr9YE=,tag:g3HNUheKxjPcAL+yNhBbQg==,type:str]
    POLAR_ACCESS_TOKEN: ENC[AES256_GCM,data:zYZ0eErwbv/10RLgxaKr+S47G+rP+pXO8u20+FIdM/IOkbJfWTTc6jEYsFb/SbZsFkgZltw=,iv:prNC4/9L/dEq2iaN1spJWm4o6tnHYBMlAcfllE8rF5Q=,tag:x60HJByg5AqnSFIWEc7/Iw==,type:str]
    POLAR_WEBHOOK_SECRET: ENC[AES256_GCM,data:G18znDTCtPbMTSnkXIcaYT64i/d52CeUAMSraTnk8Ob6A6gZ49wSIq0DYeDInbtnnfGTMccdQviiPyynAKo/DA==,iv:qd2/GDTLEtGbmhx4Lq+BjSZNyI1bCK+On+n2FbzmDRo=,tag:rJ8RBTv9x02nI9P5mjCVlw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ab5GdptuvpNeiK862OM40o5gIvdoJNRxzixoNB/xqIg=,iv:I3TemiU8jSoPV96xYSnE/PvpPxgEUMva6i0K3ZLu0p4=,tag:iJZiiBIaJ3rWvnvFV/w/eQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:dGJYrVCSkTLYRTBbpcFfpswx0hCdYdaqhmgkkvy+3n2iOES2oJ0V1TkSmFevOnAIekeEE1f7eQeYeeUGLYRfuYy6TesBUKg3asGqY1sz/POIBtjrJ8O4lgwOFyhsSfR8LcsyLwnGMJ70cyhx+2PjtzCkMdSZOIK1DpvR8NkR7+0=,iv:TwgcBY991kOUURS3TJAm1n1dmTIUd6S8J9/vWz3htNo=,tag:Sm4FK6C1cJKo+15AxdKRLA==,type:str]
    VOICE_SESSION_SECRET: ENC[AES256_GCM,data:DPnC7nhUPfDXL3vhahHrAgbicldsGAkda+gzbQVXuzyPeb+tQLuPOZ3Ulog0iA8VYMtciiz7XVwef5F/mGPnXw==,iv:rUCgbpXGYoL1jvsB4r8rVjjEpvgWzPo3thSqMjgiKgs=,tag:lSIHnJdJRR4E1IvkrzFBoA==,type:str]
    TURN_SECRET: ENC[AES256_GCM,data:VyTAYuQ3XdKwOZkuUimnDsO1eTd3YvMsugJJ1eYKNy7v69bBTWEA1GGgFwUNOQ==,iv:XemRDmfFsZYO0rJkn0Vc36jGau0plW3mMBNXTqzBvEc=,tag:f34t0KL+j9O7oDe9soFKxQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cWJjcXVkWVhqU1dFMHNw
            ai85U1ZhclN6UmE1UEgvb2xYeDh6V2Rac3hBClluMXdUaFNyMS9HY2p1d0kydWtL
            WkFMOC8ybTJQdThabkVxbExJRC9YUzgKLS0tIGZ1QnNhYUwyUHVzUDNQdzNiSXND
            Q1hmc2FSV1Q3UW13Z3pFOHdhazJaOWsKPoUo5jNg0FFxFw3Mn5eiJyStp25EDruA
            UY+nPEAEoZoo2iXt2vwPAMSypfnvh+c0IWaApZN7AYQAtIWVlgDHjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T19:01:31Z"
    mac: ENC[AES256_GCM,data:TS3vJztc8OLo2+H2/Hfoqr8RjQpFpU3Lp11mXiBJkndNxM5MAFAGIMkIHXC08BkMC2l122sJyUp88v/QEqDohNkTKdkq/RtJeehpaZDHvDTrSnr6vRhKnXt/j4rClPHNQ6jly9FyfWUt+XM3MF8BBt8rTZWFvCQVOqbbYSsUUjY=,iv:pTSLbcwxVGYXrWilr5wdLlYznXEtWCRWtV8+XIaAQiM=,tag:w59GCuYvdj+6U0eb4DpgaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
