apiVersion: v1
kind: Secret
metadata:
    name: io-platform-secret
    namespace: io-platform
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data://YuDE4I+0Cqx5PKY75KB9Z/TMWSMcMS6aWsOHxbSxuABF2dDUlHGNoWJnm1JxKAqpifENYS1PVGBJ6m2qcuEw32HOgbWVniAk8xpdmsfYKkd22cjIW26V1YAP6/ZT+ujDgYLW6uGJK1MHkSs7SEWXikXkpvVZz+rtFEotdK2Co=,iv:UXMU7JmXqZD/7bWJgYsCggV3JZxOQ5yo29mvyFpDsvg=,tag:IwXpABBAvE7no9DOO2UH0g==,type:str]
    CLOAK_KEY: ENC[AES256_GCM,data:BLUM9rvhBT1NNUjMn+60jnOM76tdR3BitUMw+fRFAKX7egCVMwf9m/Wyxjw=,iv:54vRwpJvBRhMLEi3pJ1UjO3pEiI9CT/gThSwAU1qBoY=,tag:093l/CWbdLFE67sxmD64qQ==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:xXp3WyRDCvivgtCEW+4rb0zWzZh2pVeUCMRcZi7pYnBZeZ0zElDg1dZvg51NY319NEpvsdK6/2YG2qUc5TRhCQ==,iv:dlRf3kgl8SW01+UQjczKP+b3aq3lrT0FupfnNSVxz3E=,tag:GvjBCyz7+sVXV67R8ZpqiQ==,type:str]
    VOICE_SESSION_SECRET: ENC[AES256_GCM,data:q8WgJRrZWu9rOJeCXZv/Kb33xdgv5Nl/P5CFpDW89l+JIG4Ej0ZWFWouZ2t25v0Tgq4lOM0WarF8lgRt+nzKqA==,iv:MKaO6PGbXpWkVPLgihYauEccFfioDeYn1bxxZ5ZiCRI=,tag:9R6f4ZTwY+Pgyo3UjwwmvQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:mLyQ2UyrWTpP3fmvMtKk5jmkL7maE5uWDT990biAmVg=,iv:zQ64KcM0SbMatNF3NA7m8pOAjDISwCdK0JB80MgTKto=,tag:xYpLIHmpf5F7r/6WuVPm6w==,type:str]
    NEO4J_PASSWORD: ENC[AES256_GCM,data:A6z9l141pzX+gtq4tXsp4lrUp26CK4sT8tu6uPUWTWY=,iv:kYVaPiq7X8e6FuzDu2eiaAfaDKI/9TP4x+8WLBxOmiw=,tag:Aq38P3K2sPkyV8fiRnN1xg==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:SXOvmQewX5PWgw==,iv:g89IyEgtQDdDbcQE9Z026wloogDmUPVLqCy75Mds90A=,tag:LdWQkoVLv7jstdENxdjRpA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:zVwLM4sfiQaDigfieN8L/mD8k4cYkY0+J6Ux8F05214=,iv:izM0vqLyVUv60GL9TJ/SPT/93o9EjK1MylFJbnM7VKs=,tag:77EH0UPsCN+Tjo9PTVcmRA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:2F4RVsqhmYbShQc/g8PfnbBu8+uij3H4gY4BuyMLdm1zQW0Eq9hHg6xg6fK4B6Z5k9W/kDv9LvMWcIUF9xa+b8a6OXiWALkgPRySS5MM6eEOSuqQgMV5CE0MMuh6XPI=,iv:pBM3X8vNU1eKQ8Ch5OyiH+upOpBPVFSH65VAKQ36pJk=,tag:QcjwHNt+TWJ/5T2BfQD8BQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:rDblbMnpwRJZ7SqZM+1UhgoJYpgxwNRH6Iyf50DucPjMNKcWN6O+U9VEAFrSALjxtAU5w4hfKSgrJkUoTd1lfR4lltZowluIWw==,iv:8IOxKp3+JgBOws5Vl0rFPG0ka8EhSDVS9lRENCGyp4I=,tag:OXYD2R/aLjF0FhH17+/E3g==,type:str]
    GOOGLE_API_KEY: ENC[AES256_GCM,data:nAsrfX3YlJBl6wgd3F3EH4AW/HsHCOk+npHywX5yvQp3dB59CN76,iv:Te7SP+ThQNUHT5ZcHOrDjE6DaDpfgTDTC99dub35eI4=,tag:MuGRXv0r23cmmlu5iAlrhQ==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:Wa5BMrkF/d68x+s5TzW+pYIfh0C8sPCXAPjbNdbhsrc9r527o4DGnyX3rHg6BfsGlOCngmngN0X3Bp5wrdOSyhDSdxqdLMgHmcaql2xxCmvLn5MqTHXCZtu3jZBuE1lRzMw8NrNI32DRVFg8,iv:hsfiZBNoX32qfz8sVXAGr3GbxWPuxt4AnOAc9OcMg4g=,tag:8TDrxdCgCqfyifOirn45mg==,type:str]
    POLAR_ACCESS_TOKEN: ENC[AES256_GCM,data:Ds0Bpw5XRiJTlkK31C3vqYRIvxdqXwhz8mJAPgNpM8t6pYvoNYQMyxmnFGQGrGBasUfppr4=,iv:K7UtbQciVFSyHCEBHWNAYYlYLDph00gAkbG7iaFQ5XE=,tag:HdiOVHqcypFt+Bojb6NrfQ==,type:str]
    POLAR_WEBHOOK_SECRET: ENC[AES256_GCM,data:V1OjQn5J7zx8aenS9F9LdmYQ1jYoGwEONLGKpKHzrVcxQjriLTjrDLGGM8K3UnDNxaueEVhRfEkE92sAa0rR5Q==,iv:6q63vGQB4Wx+MAVNlE7V4j7+9iDkjDkHV4LEcMhLLVM=,tag:wjSF7Ia8V/2q4tS/WLf88Q==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOHVkekgvcUVoN2x1WkRB
            ckk4VkphdFNqYjNmRmpRdHpRcHZJMzVMU25rCmNVYWw3OUk3YVA2d0swZ0U3TExZ
            d1ZMcTJuSnN0R1E3d053V3h3b28yYlUKLS0tIE1kaGIxTUU4eDN3VzZJNS83SnJw
            REJTenkyVHRDOCtpYU1JQ3ZaaFhrd0EKNmyRwVRcmr4JnG74NJMQtkpAUQLIxZvT
            Em64qN02gunogt+MlHXTk00lM7ty9tV3Ph+IQ70hgXjGn6kzbPhSrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T17:02:17Z"
    mac: ENC[AES256_GCM,data:pdTDP4kMfhsU9xIDuIlVjrRMvG6y2f7bBzdH9uCDvnV6LM5MKhW3EMeNVYtY3QRU1uF+dC9iTuH2vSdfoaFJhytJ4cayfOcvlChiDbvPpgjZR5RYyIPCs+jQubZtLDLxQWPxleMip/dVcQ5UqnAI/50GkVEzqf8RIY+LFUFo5Wo=,iv:w72VT90zJnKxS7TFQ0CMS6bxSpLy4CTqm5eU8rSaqCU=,tag:vR0xTFeMhBVCfYoV4IbbxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
