apiVersion: v1
kind: Secret
metadata:
    name: io-platform-secret
    namespace: io-platform
type: Opaque
stringData:
    ADA_BEAM_GRPC_AUTH_TOKEN: ENC[AES256_GCM,data:0zNLqJ2l92MCFzkokSlCIkoJ7Pu8iG7+J+CUrkFy4fxJWk2tV0f5IpXd45BxTS05RmqhGY4ojmUGrhjYJjXnGw==,iv:lVmwy6bJeAZfwRBb50bIqBCmu1OWziTZwdunkekoWlY=,tag:KNWG3FnfCv+V0r56EKFyYg==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:SUDw6fpXPtHVqkPwpYTVyVZN8bOI4nCk7iJNxPsegpiRDsceT0pWMj/S0uZXe46FbvNOQClRR5puwXeQrAj6UA==,iv:SXBoh+uV0ttqiMNdg8JBe2Emn4lkx4qEkuDIYKei18Y=,tag:xkCu5JLXOunYBY8uYj54wA==,type:str]
    CLOAK_KEY: ENC[AES256_GCM,data:flG0wTBxME8VLuhhPGDyomdncK8aBSleKJ/Gv/fksgl0wSSphNGNyg9Mmac=,iv:JYeHgaSTVNBAu5IatKM1OU15Cvi51F3vlz2BsU0q87c=,tag:w/SHII1D2BwOnX6Wl/OreA==,type:str]
    INTERNAL_GRPC_TOKEN: ENC[AES256_GCM,data:h/WoxbMiojlsGCocFP2lpawynY+rsZAa1pgDn/0GIaEXwJhZTacX5ayxVlrZcBaAdX5+tMWrNrzqoWUS38T83Q==,iv:nYbCD6oDDSHd23yF6BUCW7q7PFHSE+niPkEnvd9aVuY=,tag:4HpzzYCuD6MnUJcSXL7C1g==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:I2eop+JryzWQCGEERqoe/dXRVUn970XnOg==,iv:ureJ4NBy8n/bMw7esDgA0utP259ge+kjujzVod4k4dY=,tag:LhsmafC6HPKKADJlnhpoFA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:SD72oPj+FeNvEGWG1W3dpl4rHzS3XDOU4LWmD4DsSfA=,iv:AlJfN92iDrPmD9YHfcTrCIljROlkqmZ6xlRbycGEc3k=,tag:OHN0HExx9+Ko79kAJJaWEg==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:woKV92huVguI/Q==,iv:SJ2Cr+1J8Tt+9URQ6ycf4iVzXtRaIC3jm4flAbaIMps=,tag:byai2XvOm10G1CP3d0HtHQ==,type:str]
    NEO4J_PASSWORD: ENC[AES256_GCM,data:XI1D8uj/Oxc42Mq1kF8Acru3JYzagCobKUxA1Meg9eQ=,iv:HAcMOB7FEBSaeiacV2FO5SVtagNH72QmFZIcZEfbbro=,tag:znSgx5rTrCNXqGj4Glwh9Q==,type:str]
    POLAR_ACCESS_TOKEN: ENC[AES256_GCM,data:DPFBvWYknfKJTc9CB/SBYUWwDq4f2EYf8rqV/Lz2E5B5qkDQ0yIP/7lZUkSly9WbrG4B10M=,iv:tuo3ZTtPpHCmc26S41dXfqf/KeQ2HH0APtiE+ay8UrE=,tag:G9nNqNkSJ6x9mLoeJR0utQ==,type:str]
    POLAR_WEBHOOK_SECRET: ENC[AES256_GCM,data:mCYFRWiMni4Dv4DUm3cOIWaCMTAcVLzhhrE7dd8AOx2MpPtb2HwkCMK9QPidjEs9mi8o5Mefak7djPzl4cRuUw==,iv:SRdB8/QDvGsB8Ao9dhXK+QcNFlfpkHCSp8HHg4yFaJ4=,tag:PzQCKqWSFhV46UwXTBShDw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QyvgLfLO7kL6qxou0wsODyWC4jMpY1/l10PmoGhC3Kc=,iv:CjlDP8CcCBpQ0PET+PrKWykkuRaej7pv6A8LjHIJvS8=,tag:giFRNlweLz552f+F1pAdDw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:q4yj36bVeGd+PX8QOGaZjt1HMrgU45teunugjt4cYfgffE4DEn3HX+NQGd3nVpeKB5kRTEhscUIn1UmSpaVVZPt76z766GnQzf1PyRt851LAsXvNsJIwi+KcifT06x2uzVfcxD4r3wy1/7CDShCFCTIkryIu7Uw9dOMkT+BXXrk=,iv:PGZ/6W2eO8JBYi/85TT4sHoGEIEzsmYfowPo8/k0El8=,tag:LB3pXfZZyikqI/9pbVJRMQ==,type:str]
    TURN_SECRET: ENC[AES256_GCM,data:dixibC2d+CYnkU0WBBbzEa/dOyOTQFfDb2fuICLexGBAZtx18+oVQbqMydNouw==,iv:P06+x4QOiGAdOPanr8Ms/M6bJycrN2opV3db2xm471g=,tag:nmrU4NPY7DpJRYzyTtRU6g==,type:str]
    VOICE_SESSION_SECRET: ENC[AES256_GCM,data:w/XP7vl0rw4mcpgIdYyAKGoE4Bj4wJi4QaRqHsOiID00MSN4+y9NyblMtbdmSFrHOCl5wWQOBUGZ8bAqgxVs5Q==,iv:7QhvFjIztRzo062iT/ZnT2SBWItJdhqSrgptrvxY5j8=,tag:EM97NfeClheQZ/O9bvfBxQ==,type:str]
    IO_RUNTIME_AUTH_PEPPER_V1: ENC[AES256_GCM,data:x8ufoXYe1ZecPsiTBfBihC71jBvjdMHlrDHQUofwqs11vUGYwh7XMa4uD265V3H6gOjlL1AU+ymWKeCyLidqgw==,iv:WOLy8XMUoNzFcUmqPDuqlnIK/uTSxXdL8aadwKB0jcs=,tag:h9fXbTnlfnmhh9b63xdNGA==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZW5XdU5QTjZkeGl3MnIw
            ME1iNmMwRytLR1A0aVRsU0R0NUNBRStjTUVRCmZpWjhZcmhyMkFxQndvbGVFRUdu
            TXpUN21wRmRCaWg4RXovVnpmTVNRK1UKLS0tIDJJQ3Qxb2YxcGthQWIwS3I2cGlV
            MnhoZk5Rb1JLOVV0bk1vb2NuQ3ZocHMK1GKqpBx5jdZ+olMZ0vfbfoFWM6bqH29/
            Mvva1KY2nvQPrZ2aR58IGfK84IwbstR6r4CRk7QoyJH77AM824lwUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T17:42:48Z"
    mac: ENC[AES256_GCM,data:M2xFzICI0RPxU8JT0BBxckKbjRA86P9saEPGcDbp6BaXAsJAc3fRRp9wFoGwO8Usl3wFtbqmjkiZxNgvWlb+nha8kpudncCxhM07bDpAF9A3fbTyL3G45noCvOBPWkoSB5USjgfE7oj2WefN0NrpZ0gB2WdjDf11m8TX4LA5PW8=,iv:q7w6R9dD9C4Dh5hPTdAjdHh2OUVO6UupyFf/Dc0JQZc=,tag:xe6jZNeR40MuuyQeed8Cmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
