apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j
  namespace: neo4j
spec:
  chart:
    spec:
      chart: neo4j
      version: 5.26.0
      sourceRef:
        kind: HelmRepository
        name: neo4j
        namespace: flux-system
  interval: 15m
  timeout: 10m
  releaseName: neo4j
  targetNamespace: neo4j
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    neo4j:
      name: "neo4j-standalone"
      # Password from existing secret
      passwordFromSecret: neo4j-secret

      # Resource configuration
      resources:
        cpu: "500m"
        memory: "2Gi"

      # Enable APOC procedures
      plugins:
        - apoc

    # Volume configuration
    volumes:
      data:
        mode: "dynamic"
        dynamic:
          storageClassName: "app-storage"
          accessModes:
            - ReadWriteOnce
          requests:
            storage: "20Gi"
      logs:
        mode: "dynamic"
        dynamic:
          storageClassName: "app-storage"
          accessModes:
            - ReadWriteOnce
          requests:
            storage: "5Gi"

    # Service configuration
    services:
      neo4j:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: neo4j.horus
        ports:
          http:
            enabled: true
            port: 7474
          https:
            enabled: true
            port: 7473
          bolt:
            enabled: true
            port: 7687
