apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdownloader-deployment
  namespace: jdownloader
  labels:
    app: jdownloader-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: jdownloader-deployment
  template:
    metadata:
      labels:
        app: jdownloader-deployment
    spec:
      restartPolicy: Always
      containers:
        - name: jdownloader
          image: jlesage/jdownloader-2
          imagePullPolicy: Always
          ports:
            - containerPort: 5800
              name: web-interface
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: PUID
              value: "1005"
            - name: PGID
              value: "1005"
            - name: TZ
              value: "Europe/Paris"
          volumeMounts:
            - name: jdownloader-config
              mountPath: /config
            - name: jdownloader-media
              mountPath: /output
      volumes:
        - name: jdownloader-config
          persistentVolumeClaim:
            claimName: jdownloader-data
        - name: jdownloader-media
          persistentVolumeClaim:
            claimName: jdownloader-media
