apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdownloader-data
  namespace: jdownloader
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdownloader-media
  namespace: jdownloader
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: media-storage
  resources:
    requests:
      storage: 100Mi
