apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun-deployment
  labels:
    app: gluetun
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: sonarr-secret
                  key: WIREGUARD_PRIVATE_KEY
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: sonarr-secret
                  key: WIREGUARD_ADDRESSES
            - name: SERVER_CITIES
              value: "Paris"
          volumeMounts:
            - name: gluetun-config
              mountPath: /gluetun
        - name: curl-container
          image: quay.io/curl/curl:latest
          command: ["sleep", "infinity"]
      volumes:
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-data
