apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-data
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: object-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: object-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: media-storage
  resources:
    requests:
      storage: 100Mi
