apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: sonarr
type: Opaque
data:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:QRxgz/fwMqX+bh9gHBA9oK96pmFIqzScq2G0o8x12c/Et1m7MzJ0oMeluX8=,iv:l04SB41AI5CICe4LaEtKmBgf1BeDXskIHBHQtPxrnj8=,tag:ANU2jkc5PVH1CdhAaK53Bw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:/yqJ7njS9COimiUiXa/7,iv:o6C6k8Hf9/zh2JytK0mw57UfFvi8ZtoT0RepvDU2SFQ=,tag:aulfGeLY4HmKQ4R495Fx9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VmdnaHZmbllOcnFCWTJs
            eXYwMTNDYzA2cGwrRXNpQ3BjWE5zbExTcWtZCmpQTkhUQ1kyZ3pVcXdyankvL1dl
            UVp0elRlOTRzem90akhrSk1ORXJtSkEKLS0tIFlHY3ZaN01IdEM5NDYxNzVKV1hJ
            NmJTYnJabUVmbWdEbVBZeEo2eGJUeTAK6yHKZvwfe0fpgHOI7gOs4aGhaK5CEm/a
            PGRp3871YW0m+3CAE9pdoGcGCtmRL/kHVjx1FH0igFhGhZog4AKYeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-18T21:00:34Z"
    mac: ENC[AES256_GCM,data:1B/Mn/Tp39wzNYaeueXnQaPSfrHF0pGAbte8Zpcl/myGUZwsfEgjo1TvVGaREWPAokuReLKh8elyHz2aurQ/m4oR7rDZ3u6vHZpAT//p7B5lUbV84j18a6mG81QMGZDzprtdAT4mpqrmsZGF36W5yRL4HSbi1hxXd6SQcAsSBGc=,iv:DnVgXYwyXnlZbB98H5gSZcB/1CfnI0aj5glObTVZUDA=,tag:tmfy6Pwbya9NECbeou2m9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
