apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: sonarr
spec:
  selector:
    app: sonarr-deployment
  ports:
    - name: shadowsocks-tcp
      protocol: TCP
      port: 8388
    - name: shadowsocks-udp
      protocol: UDP
      port: 8388
    - name: sonarr
      protocol: TCP
      port: 8989
