apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.14.0
          args:
            - --source=service
            - --provider=cloudflare
            - --cloudflare-proxied
            - --registry=txt
            - --txt-owner-id=external-dns
            - --label-filter=io.cilium.gateway/owning-gateway=cilium-gateway
          env:
            - name: CF_API_EMAIL
              value: "maixperiyon@gmail.com"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-token
                  key: api-token
