apiVersion: v1
kind: Secret
metadata:
    name: convex-mneme-secret
    namespace: convex
type: Opaque
stringData:
    INSTANCE_SECRET: ENC[AES256_GCM,data:7X67qxyBJ4oajct7GnNEMYCbvrbeqP+SqXA2mOrtEZNXwpf7jzNOsWCuSA2HiW9wxmfb0Et80Y+irYYGL+vI7w==,iv:kYeJPLP5Q81BIrBDVFvIE4Lzsi+otGtcE6BiLzfWWWU=,tag:51N4vYznauJO/BtJ/qpvgA==,type:str]
    POSTGRES_URL: ENC[AES256_GCM,data:XsVb7Q0dUUAoIfkfdShn7JSwymBYCvhJ1ScsIvaopzzZ8witOhGV7YgxkiTqmOProQKAjYkn7aza0Ra5xCfX8dfvRIKded8Vj3/JyS1hzwxIw0hSbIrt1s54yXTu9A==,iv:6SRmm+WoZvRovIBZTb4oKnWv1SIJpB3qKMSVWlLszO4=,tag:OvUgx73MNfMymYE2yrjDeg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:v9njyyZuCA0sMw==,iv:n6DumGxoYWpNrcgzByXv9X8m0DbU9vd1hrcJ71vRyF8=,tag:wElTmbv404LznmwQ2oUiZg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb1c0Y2kvMkJSOTBVbVo4
            bDBUZ1VmaFJ0VWVFcTBteWNBZU5Ic3NjUkhZCnBpR2RZSHk2cDI2QTZORDdQVGhh
            U1dkMEVqcFJmQWhYVTlCakNDYml6VncKLS0tIERwYjUyUW1nelRETk1iUmRlQjhu
            K01nbEFjcWtrMXQ5S2lmMTR4RTAyY00KgCYqB0FgcH2R66tjGApCyQVaxjl02UD+
            kidQ2Zk5VxMQ2Dlk9vEiEUafDDcnJmahiuMvfI7uIXGJZTFtGH85YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T22:14:51Z"
    mac: ENC[AES256_GCM,data:+6F9A14etgsjlbTkbTo4SmK/LYwJmpgQoH4ge7BVyoGVZ8P7JPX+i2Pm5ID7zGO/hglS5N3tLYufAvV5ZEYcV0EVZnzeglHBUXe4bBw2aAkww6E2hZkW2hTQ35Sn9NTr0Kk4g+b6spLfM22wp9YY6mAZqMtobMbpDQOgqw52QjE=,iv:qZWQj0SeimsEwZLjYbB1zAD3qp0AAtvcmwoEP2jdbjA=,tag:SWquHEU1M/bFMrqjvREQig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
