apiVersion: v1
kind: Secret
metadata:
    name: convex-mneme-secret
    namespace: convex
type: Opaque
stringData:
    INSTANCE_SECRET: ENC[AES256_GCM,data:55CvCIOIPkWzlNcgOw9UkoQl7wEFlxm7mhHbzTknjiB6807NyrWnVnXS1uGwWLTLdVQztYtpoUF2Q3kmbaTk3w==,iv:AiSRGaFP3FeDddczOG8ork3VJxxPcQIGUJprqhlHCqk=,tag:6z5NvmySSgWxLR3a0mqInw==,type:str]
    POSTGRES_URL: ENC[AES256_GCM,data:4qlgRDwYvw54SRakXHO8evfTWF7pXYHyskDJlyIqmCih/ARpPcYKFJ9ioGXSCBop1wp8McNU3JhI5ClBGtr69IQQ9Rl/8cgGW9iulUbLXl9B,iv:7Lfws4aA7UVbRSiLzBv2wLjC6ZCuRQ6VNMO6kSkzBnM=,tag:1hsz3yBNqLClk0y4OR/+BQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LzLv+LpkMW/tZA==,iv:FLxR+IsAIHjFBRbfo8ArtgQZjLI0hMljWQEbo4DKqJY=,tag:J6uhGUSdfzq5Cmt74JoS/w==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWmF6Y1h2WEdLV0Zxc3Jp
            cUM4bTF1YkRncDhRUUQrSXc2UTRaYXdiYjBZCnNrUVRiSUpQelhza2JubmVIUXdU
            UWhPcW9RdEFxU1M1a0YrSld6WndVOUUKLS0tICtBLzF0QUpmRWxrdzBhS1B1SWVq
            SDlHMHpwVm1iREdpaFI1VGt6MzM0bEEKOQ/dra5n9wOC9MlVI8j9pFL2ZQF4nlrI
            l8kCQkwCtMZRnhIDqcAeQzxxJRLVeUjK0jkk1EUx1lpQKQSfO4qY1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T22:23:43Z"
    mac: ENC[AES256_GCM,data:597WZFHhUlzj7HoJ+NofbTNqSFh28HvJeMjg+TdiMcsMkGpJX/JH8fTazVTU1TubD4yq2e9QzzPM0R/YTk70HPCJABxXHfSma2+We9JmbDJXAt23m5rkhzy6NJhCLMjNUiXhyoT8afd2hoqBtMHhlSuIxIZAnpE8MT1TwwRjY5g=,iv:V/43/r7cv0aad2xLVoiXsP8vdHpjQ4coB3nPpLMnD7I=,tag:9ct4+ImSm7hPvb0T98i+Mw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
