apiVersion: v1
kind: Secret
metadata:
    name: convex-vote-wise-secret
    namespace: convex
type: Opaque
stringData:
    INSTANCE_SECRET: ENC[AES256_GCM,data:Wu84nCD9MqnFqTE4vgHwVkdfqAVP18TAgg8L4vX9tnecIgmbM3kaWCBuFZ/O567SBW3vvKuuYm5gvw9qaRMZAw==,iv:QOzlHnyyUlLkqjhLjtZxTbiiAMSeOhz/XBhoaR/zA1w=,tag:vTqvaSDHuLKzfvlc0N1GjA==,type:str]
    POSTGRES_URL: ENC[AES256_GCM,data:E9hebOhNAvEjdm6clMLsGFbk77zZropKWYP4hqwAJ8UDrrC49FxxITZzBUSBTY+eNh4dsLHssQLCSQoRt8p/Xxt+w0qMqEJV6wU/OM20egg3,iv:BOakf3VV140sqj6XtzhCl7yJtcjyD6JNMGNLaPzNYdo=,tag:Si+qqhunNxLvBtHn2rEQyg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:aqNBRBvjFbjr2Q==,iv:bkvYP2QlWztUDQxuzPDqZiU4cPY0UPwzmQ6G4Oc+IDM=,tag:AEjQ8KEQiAbnlVh6UVsBgw==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTE55RjRYclcvZzFFcGUr
            TlpQQ0Z0enE1S3c5TlhlYnZaUmZNdTloMWc4CjlFdHJQaWZtT0pMNFJ0VmVQMnVz
            djBDMEh5Y01XM1gwRWFBaHFPVVQzbUEKLS0tIDUxOW52Ri8rVXE1VHZFTnk2THI2
            RE1rSHNhYkpSOEhzYStkVzF0RzUrZGsKY2lWYqx5n07hQhcsYtbCJaH0Ly+31XqZ
            2utyCIvJJfGF5qii3scojYkeI6+Z8kwPT6ABmyAz/uZRSc7dSr82mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T10:50:28Z"
    mac: ENC[AES256_GCM,data:Pqn46x1G36Sf+1l9yPJRG9cDFen80bPeBoAdsZ1lWeBu78AM4dhPPRvK8gXYD6H8pAjv9p+wdVuB4n60ddonfA+n2wdd2lqhhkVoAakhpCvslM89DaNgzwOR7PYFAQc8/R8/POPRu/kRh2UozA0XdLcoUuQDROoAeINzA0ubgqE=,iv:2j9r67tfOAk5xlozhGcVAyybUyspw/Pn1CDA5f06xLY=,tag:3CJ207kkcm4ws7GkbjLNZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
