apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tdarr-node
  namespace: tdarr
  labels:
    app: tdarr-node
spec:
  selector:
    matchLabels:
      app: tdarr-node
  template:
    metadata:
      labels:
        app: tdarr-node
    spec:
      containers:
        - name: tdarr-node
          image: ghcr.io/haveagitgat/tdarr_node:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"
            - name: UMASK_SET
              value: "022"
            - name: serverIP
              value: tdarr-service
            - name: serverPort
              value: "8266"
            - name: inContainer
              value: "true"
            - name: ffmpegVersion
              value: "6"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
            - name: nodeName
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
            - name: tdarr-media
              mountPath: /media
            - name: tdarr-cache-data
              mountPath: /temp
            - name: tdarr-data
              mountPath: /app
      volumes:
        - name: tdarr-data
          persistentVolumeClaim:
            claimName: tdarr-data
        - name: tdarr-cache-data
          persistentVolumeClaim:
            claimName: tdarr-cache-data
        - name: tdarr-media
          persistentVolumeClaim:
            claimName: tdarr-media
