apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-data
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache-data
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-media
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: media-storage
  resources:
    requests:
      storage: 100Mi
