apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litellm
resources:
  - namespace.yaml
  - secret.yaml
  - tailscale-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httpRoute.yaml
configMapGenerator:
  - name: litellm-config
    files:
      - config.yaml=config.yaml
