apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-tailscale-state
  namespace: litellm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
