apiVersion: v1
kind: Secret
metadata:
    name: litellm-secret
    namespace: litellm
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:7fNJu9R6z0ExhhO+C2lvuBPKIDgxb98epUceOFNvdEVpxx5zJ4g3Y6ygTQ==,iv:x5OqxD5eGLTsxApt0qrp8L6XvcTNK1nkmD/CVHStb6Y=,tag:C3rGD3ZcJ+RqFcIS2Ic25g==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:eX0cFFVSXfLilj/Bl+B4PyVfU8NwqSD0gE83RBdVM+Z+FPfJhz+7E94/T3R/Hz71,iv:mc0/A44VioSyxaijKW/AbOanPF1DhVWI+TtVoDiaK1s=,tag:Zv4pGJAlrMROEQwGg3mGvA==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:DdttLV8RI7EIhM/cgKO/PJ+awTiJii0DOPl1tkVmxUWFJwRozUxVhHXWMS5hMXFZGmsZKAkTx8JaBzZZZZ84UB2247qKz9vnRpS7lf4PxuVYsaEgFkhDYor/lQYxCS97X9cc/5GBvKVdx0PV,iv:0I57WNpt7bGXIQ5kDWqhrwIkQa1GIO3n1O75nhFLArY=,tag:wA0KFPNJaFRutn7LansSyw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:dC8O/izn4lQUrRK6Gg98gNtBfwAfrY8N1S0XpbwBjOoJ84ixmHV7lEfLsF9wxFW1yvY/kVCUkrP2QHrAr5mOwdY3zAmUn2Ud9mVJ1WhuMOvKGGQi1bk2uaj+rOmEPTo=,iv:IkEbkVDsN2oHPdyuvhYuU+P5GABggQpmq5BcIbY4BY8=,tag:tLzQCWmCqTtIp0eMC2sAEw==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:v6v9L8w41mqOqokSxTbp1EJvfGri04E4OHBwctMclVGjC2M4CaGy,iv:HexItCl+MoUx4aCpPnDIr3Agc0KJmgBEE+b2xxhZIpI=,tag:5N2EIj/pm0Yf7lKkEgkMcA==,type:str]
    LITELLM_DB_USER: ENC[AES256_GCM,data:0YPOjNGmhw==,iv:uE3A0HQCe3ml+XfrVzvcowPeZvofwggI+7T+lSbRo3U=,tag:Fb+c1bRLxfQoi6ts60nhPQ==,type:str]
    LITELLM_DB_PASSWORD: ENC[AES256_GCM,data:XkvCN5Cjlvo+5HvXjKk1XkasQ/iOJSby,iv:xB8Sy+IGOPZWT6+0Te5XxAD/GdJriw3fTClryN6vTl0=,tag:jM+cjw5PaCAH97RSXDtBwg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Nias7f80dEKcly5eIoaQcqmV4p81T2uGWvqcNCfClxGpvQ+DuLXPl97lRWUmt2o+lIjfAhx0X5fOJ9PGDUr4pBA0klwuN4ZAftQtT6Ktrdu5Muvz/Oot4MkvrzyCe+xrEE+S/dgl,iv:7evDQhjKmL4jwGFzDg8X0xJJa2DEpiCfDwwHohoVGjY=,tag:LCfOJW840z4zxYzkn2u1zA==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTjhMTVAzYVZpZDI2bnlG
            MFFGZ2VNWGZsa3cwNWV5UEdSYnNPT242d2tvClk4amI5Um9YelFkcjFxWWJMVFFH
            R1BnNnVXTGhWeE5oSUpHSC9OSm4xQnMKLS0tICthdXR2VFF6OGtmeDNoUE9jd2g0
            ZFJ1YllTYlh1Z0ZuYU9nYjJwRHVhV1UKh7mNVUDAM/ItFQO42MnqM//soQz6vvZh
            PzAKU/POyRvEA2flw8PJ0p6TfpJDVhqJCL3+bl29aoj5RsWFihjGSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T23:04:30Z"
    mac: ENC[AES256_GCM,data:rTFwv6WkaZ9mzNSsXwiTwazb2luhMiV0mDyoW13gpP27RI8L/8bk7jACYN7Y4XqAeM4t9s9kbcOhupjfZX5K6fgIGwpRY1I9817nNmInXW2W0lhRR85nIRA7KHqR+H37wStXF9VzPeARiFDlkBtc8qZg0bcIOlkQ7u8AmfypMAk=,iv:VY9qgGNCM3oyMHRMOEFkcxH/8FECClffCa9rmlMEQYM=,tag:n0eY1xoDPK9+m9Ig1b3XWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
