apiVersion: v1
kind: Secret
metadata:
    name: litellm-secret
    namespace: litellm
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:uqblM8pJ/Wkqg8zfzGEIBreWbpueJ9Danbc5d5jNy2bjQPog5E/BQxQbapf82SBReAs6CzBqoVE30lO6M6k4QKhFohbCXjAW6znr5mDSesC9DCL3QBgyewJkOgAtgNdHFSZdleRSrfIf8/m9,iv:Fz5EmIvnS1ORdHLNTMALbtlxD1Y2jUss5hJOFE13no4=,tag:cWUD9lK55AymJnbDW4aZ7Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:nRBJitfVLhp2JNXdSr5pfWjEUX6Sqlu3doquR/TBuPCLjYyAyrwDvfTCUNLgSEUckh+FqZW15NZMOTqBFrnJOG8c8gAjrCDQozL+3yyYJdUHUqtKo65xWX4Yy2P/9im1mfgF2U7r,iv:u2NOpvTB/DIAVvKUk1HWnNgbzMKJf5L3ZxuS3GdnkUk=,tag:eYGtMjFq18+PHJGIOd6SQg==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:7jkwZ7drTt8HOsb51MwuWZyjsV+CWZn1p+caxFlhgWZ45MyZzuuY,iv:DPxqsHDFfB5o9Zes3de8Fs7e7lthUmYPX4auA5vXzSg=,tag:GKbD3/8HWrZfGfI19FgoUQ==,type:str]
    LITELLM_DB_PASSWORD: ENC[AES256_GCM,data:VYN8QNgcCGlWJRMeIDrgr21ZXvdXU9xe,iv:KTMpih01yQNmHWs21CowrxdFluZ7uDzXNZHPWS9kOW4=,tag:/AY6JS0GdbTtj6HyQNrZ4w==,type:str]
    LITELLM_DB_USER: ENC[AES256_GCM,data:OjzzqcdtAg==,iv:bXjA58UCzteqQvR+g31/XziAILU8x8jGx+NMdlq7MhE=,tag:dpQnBavpCkHl1aB5bshTQA==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:U1nbFd2WipnngGgvo/wq+KcSSRGaAn4IkoD0BlssSgzzK0hRYSjrq7hU8w==,iv:zYNY+4fFNFggy4NqK2G0bgZf6ADtuBpv914jk2ehSJg=,tag:8vcdbMHKZEhi1KkCZihcKw==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:8U4kDXmyzlDyqq/YvupCTKC0HjNfd0lF1++OnV18Q7+hqHNaIUHWOczk0odB7Nso,iv:GN32bBxmRLLtPtwhuaTdofx8dES8VLOKWDv6jtmtj0Q=,tag:kQcMSX6lZQs1TB8pnltJ6Q==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:olaksiJrscGzR9qhZf8gCz2xeQEqcUOT7Qu40B5qn+qX50mITS8D4jQItFFWEJYaWNPYK3XKxvzvX0RrcTXxUXfAaaFNgo+cstT9whrliT6WdhYNY336dr8ZVY8Xk/Hrdh28oVeJaPLRiek23vMl2lnDkgnafxBqE0AI2Q9A,iv:aXhyeJsoltMgscOU8X0XeAKfo2Gv8HSV+Q7RvQ8tu9E=,tag:9gbG8J0iOy9E89tPZYxh0g==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:+u3QqbRq3NDmjZYhyOSS95BVUIa0AsfaunKBxXUgTNXePU3O4RUs4KG/5YEMxx2UhxzzuVU/FQNAB2MTbG0uE0She/f3fp+nnOOpObE4s0+pDU5yc79IUPA9im2vJcc=,iv:yTFVK80+qEiwfjhmIARFT0DLTdN0GNTcls7WQ2QRzus=,tag:FcioCvvYA1KkINcO9M33cA==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QjZjSEw1L3h1OE01WlBs
            UWI3U0k1d21LZDF0eWNOQmJRblZMaGpFSXo0ClJ5TThEalBXUTVYak5jUm5jaVg0
            SFNYWlNKUC8rNk1UMWxRWGpDRE42SmsKLS0tIExxSGthbCt6Y2NjUityeFQvazY1
            bjZBV0wwNnpmZDZ5ZWJIZmJSRGVzS3MKabAQLSgfyy0Hinglp+WdtVkK6103eJcO
            QmQT6GFmbk+v50s9M+QhKdBp10CHpstC/IZ1zFlFInfDw07vC9YS6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T19:13:11Z"
    mac: ENC[AES256_GCM,data:9wbaAsrMsb9RcB0uxzxWd2X60XDPbpJiKMlpjT4LIQ2IB8EYUL2HNjpDCBWkafuEFjbMEXGnTTUcR12ioA6UiEcSOx6svo8IXpkSpIomM93MGeFRQN2mGls8Ye7m2qQO3Iyf/7zbAVXlfC3P7xGAByVSxmvwBiHKPMV1uUikjyg=,iv:bqYYw+mxQdBktz1rtMv1L9robI7+VI2xO0gT4hTWhNc=,tag:voIRlfkIvd5ZsfAjP223Vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
