apiVersion: v1
kind: Secret
metadata:
    name: litellm-secret
    namespace: litellm
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:SJdSapKNjxwRWz76jSiPVWJ5iZ8Ktl8kRxwrtuL2AYYjS97D0gLE3FxBC0ZW25z6JRkn/oP52h5sRvpA3OdQGMVsiInbI027tKoGfgznP7pPOFnPu+yksQAnFtFnDlapytbIZ+whroUh6Ssq,iv:q1opw0Q8olvNWZyKEV+3PEg3BbjkEgDG1Fw1k2JvFoo=,tag:RxjJH1YffyWc5BFxG8fZ0Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Wg5yLo40LHB/FS6xYtKQHFQbM3O0Tt2pMpC/no/bIF9jscgDrMtDXgcUXGzpAdQs2Rwtr7ec/WHnrcZSu/rqpHTur64VPRqJiFURvNeAy6RpvhR96wTJWNDDofBnaUBE47d8ZnGo,iv:AFqJ73WkTgGPHlWMdDoHiSIHNPHU5bHekGCf9bVfBAQ=,tag:/jTt7vB+XkqXbZsguU2Qxw==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:JjlCouGIznhop/JdcOddzvRTz3bW4PSES6GhwcN1WawbFH4PB4pI,iv:LL4kUg9zNZKmRuVpf8apPsNYs3p6m+DjUGwfHWOwjn0=,tag:A7IPrglceG+9QZMcRnGasQ==,type:str]
    LITELLM_DB_PASSWORD: ENC[AES256_GCM,data:CQIO8V8bloxYkPj/YP/vb9taaEsptjJQ,iv:1YOsxxZ2h0ua1Z06vguXxpgxOtgRkKzR+GRUje2KpvE=,tag:YNqUW/Ho8M07xwhiv+bpaA==,type:str]
    LITELLM_DB_USER: ENC[AES256_GCM,data:H+Q/K7v20Q==,iv:akP+iFoiLhSom9h3EG5Dx/XOJXxsnQlDnQ79ECjbwQE=,tag:37+QD0FpRo8ekMBSgc0fmg==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:zrwPQpVg0tXc/NWU/q56rCQN9zwqssHZs1/TrO1YD2NAgvymI7VpQTi1lA==,iv:ntCo/ACTqNLGmnC+CgSjuxWRFHqrXm82Xzmw+WIO+Ns=,tag:6bXtzcRZCxUq97Httq3oSw==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:QHhDEmQ0BTAC34tKfhPeGiIE9ATF0ydc1F7d41WHVCxPDsNoD0w2/rSInVLSOlbm,iv:6eJ8g3rer5BTzsSIzLxS2Uj7crFZo4X4d8TaXWTXVLk=,tag:t20fXXRfSwkh7khkyk+aag==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:3ENF6DVarV0IsgshDtpLtR4Vr9eOV5UbE3M3/C/f3p/qEMD7xJ47yoqZUuiJncNsYWSEGVN4yc9FxWiT2hMnALvMi54yisrGoipH5wZ3Mj0TA1+S6911HbW+ff5cMskZuTSf5/+IuAPGqjKngNmFugwJLclTpN7G82HGzZw=,iv:t43shXvBIyQYegmDPXeL+dd+FWg5IhroOA60P6Na+9k=,tag:AupkS3v/xRZ3jVdYGmt6gQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:qorSg9KAAtZDhTF0HKDJSQ8FfeKOOtyVjkYUm4THI00MhO/LUf/wHE0ceJfz5WyX7UilWSBQ4timaeXJpmEXBUskvkFOVbNNm1qNvNke8T/nWwiW9sKl/fEQAsxFbGA=,iv:OjzOlFBj+eIa0WVXAH5f6LDMgGcKXMz6U/FVnasXBAw=,tag:hwoDVuBZG9YoxSVFWdeXnw==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUlU5d3FFQllBa04xZk5l
            Q3dyQlg5MGx4RjNxa0dINmxkQitETlZtVlM0CnZrSDRZOHdJc3hOMmFwbkdLRjY0
            WUtzWWN1emZsaFlINjNNY2x1bjdTMWcKLS0tICtiWjc2V3BjNS9BTm1Da0N6aW5M
            ME5ra2dXcjgrNzI0RFQxWlQrb2p6QnMKzlcMtbCWmwNcIPR3Xljk1Tg6GeYF9P5N
            5bwhkE8o6IcLZZ/FcU4EcvWfpFOhCb9/7x3sDg6DlZYEI3DjPWYOxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T19:21:46Z"
    mac: ENC[AES256_GCM,data:L6a/nDIUpdh3fQYbZMPON2cBLaf96zoTgo9MHlz114HxX/7F8Hm4w3m3BUwGke8IynX2dIfdp8EcwIHzVDK3iG/EN+g1ZvAFaZ4KhR4et5Jhv8qcTUtEVvo4KbTsWX3L+gRRvIVWHqy+86C4hgMrO5velEz+rZfUq4SYodEk6yQ=,iv:k9kPq5Q3UGLzwYStsa08Pc/VM81yHjh1yYGQ5JShIKI=,tag:Ce5CmGxtJwU9utezIPwU2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
