apiVersion: v1
kind: Secret
metadata:
    name: litellm-tailscale-secret
    namespace: litellm
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:5RMIOBREDnGf/nDZ8cihSZAmA/payatLVm0uOUlgAewEVD4EFA7DKfbsE1ql6n68UeKY8vMBY/9m7Xj1htZLWANO/8c0pGjNcvlp7biVQDkbWYtWUBRdXA==,iv:KBqAoueCbWeGXsifokNk9xVOWeguX6y6iCPzZmcHlBs=,tag:2v21MKBbcxuMu/KRZBpGgg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRWk4T2szYVZzSHB3WnBZ
            VVFLcWFSdG9lWTlPL2Vib2xtSDdPQU1ZZWljCkRaQlplSk1sZGN5ZzM5QnhnVEZL
            K3I2ZHRBcEw3K0luMm5FQm92ZFpSVW8KLS0tIFdXaVRqUWU1aDVrQ01NdjBZeTBr
            ci9pcjBodUdZakxnQXREWEJRUjdQUTAKHH9VbNPepjSSBsv6bPn001+qK+HPLIhs
            0ioaHSWOlQJPyAtELPnr5X6N1U5AMxD88/GpSHRAWsV6BMI6KFjd3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T12:06:52Z"
    mac: ENC[AES256_GCM,data:MpQXpSueZmDcWYY8nGkzf/5DATj5K8gWUEMNkQVuWA6bip8+K6So3tshjMJD/CCECtrwOgoH30kKhewCeRIDa6O+QKbqLlccRrTv8wjSuGYaSvbvvwZCDnYCenUw0d+7mXEF2Q9EFTJz2Tb4Y1yvQNSnAR97FWyMa4Q5Mu1BnD0=,iv:9Wqo6gsXcDQOIV5qmxH4IbY8Tyo0/+s3zAap7eQJpCo=,tag:x6V4xN2cw4tHaoHgLcBeIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
