apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: my-http-route
spec:
  parentRefs:
    - name: cilium-staging-gateway
      namespace: gateway
  hostnames:
    - "minio.staging.maix.ovh"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /admin
      backendRefs:
        - name: minio
          port: 9090
