apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: object-storage
  resources:
    requests:
      storage: 100Gi
