apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  chart:
    spec:
      chart: minio
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: minio
  values:
    rootUser: "minio"
    rootPassword: "minio123"
    replicas: 3
    persistence:
      size: 100Gi
      storageClass: "snow-storage"
    resources:
      requests:
        memory: 4Gi
