apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
