apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
  namespace: minio
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
