apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webdav-route
  namespace: samba
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - "webdav.horus.maix.ovh"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: webdav-service
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webdav-route
  namespace: samba
spec:
  parentRefs:
    - name: cloudflare-gateway
      namespace: cloudflare-gateway
  hostnames:
    - "webdav.maix.ovh"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: webdav-service
          port: 80