apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-data
  namespace: samba
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-media
  namespace: samba
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: smb-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webdav-media
  namespace: samba
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: smb-storage
  resources:
    requests:
      storage: 100Mi