apiVersion: v1
kind: Secret
metadata:
    name: samba-secret
    namespace: samba
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:z67P+bYgJOsMfFImFM6eo3m+DBlVmFN278iF3eykM5ufuNDYadmhLUv+HZoDWnlh9sxyn84tX+T57zhqnXB7gnWNua8a2N74rTjgaWhL3Dr25JBOP+yBQ/B5wVgQat0W4pPkYKw6Bagp1Tmz3vsvQtXDwotN5S1VJKrvpIImfQPjKM+uXenJB/hYrgxAxGXe4712kib4/rjswpFxcx4qo6xYmAnLV+ma/wDHtDtmEZIGWhqtWkOGKOf3Hzm02JgugCfgNRi8LACUXNjII49zUUhBBNtHzvoUQq1/ltIQ4Hx7qWbiv7KTZ3C28WaVVVRZvStbVUZx86KcgL+PmVYWN1u9fytSENz2TSE4WI0FXaDUm4PGhPY4ANbukXtjjQFWnDtkVQe5/9OaAiZtTTZCHiOXGWGScz6k1HXRHi26amqCormR8D8gDux9ZeqGMHmw0hrcdLCKJZ/MqIubVCI/DA4B8g7dp2bguMW2hk6ycIkIAItn65rWq+Be06F/mHUQFnWYbcqKTVKFsyJQ9AFhYd95buXcGomDjBq7Vhi6nQcE4uhq0n/XRFwYBbaSYb0iP26BzowRGa+sddc2eX9uJkyV/OL7AxtTwxpLk9uQBDzLWzbMA+pyo16P01RWx6ul1m2mbinN+Qd4UIpAtAbJALkSZNSORO6Bfsg4AfrCho5QI8HY5ohcGgdur8ucWum0YLLE0OUwMSdkX83ZV5/rDG0XY0WpR067DCAVq7wAW8O7OjPUc0tImOFwY6W3oHK8mP/fTTirSiiTt58R/NF4KicSIBY2AthQAGGdTfvSq6PACeSGOAuGUIK1ojJJOgT0ReEJP8kEPWcfl72sfu3y5w54oKkd+Yd9GNkX1CQh43zxzoQDOx0RHvmYw1kXKcPjQcNuCNPTwq0SpbWnIvy3F+36zY7b3o9eScrranOVTXcRha0013oDGYADetIdkPnZzA30F6yffYw/SHB3M2kOzvl3Zn3cY+33nJ1qpzRb,iv:WQNR/Sx/D1LnKx1/bMd3DVqs1jBu5059F5g9UfM8UBo=,tag:XO0Cad3LY+P39JYMfWKmiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQitFNnFUTlIyQTF5MVpj
            SEFCbENrdnhvMktwNTluUURZZGo5OUNOQVZnCnp1cUxpSlN2Q0pQeDNrTXpKZmN3
            QlQvZXRVT3AvT2hyNjkvZ05mTUlhYjgKLS0tICtkZmdQSlJ6Z0JSRmtsaWxoMmFN
            ZjZIMUlJbWNVUXh1SWp3d3ZYaDNsQUEKDWfduiKLNxdi+MShPxvGovpdmYFNWmZK
            pzyi1hRc2T1KZlHzlFbi5pcZY9EdpqRNw08q4DR22IA7/MMlyOJ2FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T21:48:25Z"
    mac: ENC[AES256_GCM,data:9RfCFNR+mYFMHnapCS06EeaC7iorktQLgw22cOEh1hEX1FlZOjBmlp9dmdToHJ2gA7bYlh/3kotGzovFZbJcRPS0XwSiDHKfN15qm1VAr1KezOVEV6ym+DatC2pxqYZxJmnGkkAllSCcmPqjm4uak/8kO8+O4K95LPAQwXCcpE4=,iv:gtfm69su4B6Z8Y7u/JhsVxZMS8fdI5yxQSP2Qe7BQ1s=,tag:7YZhEJZVea5Yxk78+Ex/7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
