apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-downloads
  namespace: metube
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 5Gi
