apiVersion: v1
kind: Secret
metadata:
    name: nabu-secret
    namespace: nabu
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:kobqbQ==,iv:b+/YK1kmQi8bKOqZTEokiZQl/pe4nXp/V/tRc+cAcTI=,tag:AgeIRVieXGWUwH+dE7BkcQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:2XOPScflq77NQ1el4K+Jz9UhzN2JN3LRivswX8KOFOc7wvBY4AC4RGP2Dxs=,iv:iykRowcKLwuWJoipOSDyZrXJ4Ddbo7WYDPSso7iY1Ck=,tag:M6Kz2oRWR5aNV3LdRGZasg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:NiwQNw==,iv:F9omhMLyYdq89Ju03490ATAEZ46fYBn65dfidDs+COY=,tag:mluSa8r88uam4xsUSL9Y+A==,type:str]
    NABU_JWT_SECRET: ENC[AES256_GCM,data:LFxbZgt/SHI5FqriI7PPcT+jCNuV9pnpe3/1dRAI8Sxu+lJJhew4pEUZE/6tLex81Zdp/NREWk/6wUptph0xXg==,iv:wodOG04+1stfCY/qkZs6t/pLc/V77sp1yc+FwC5MApo=,tag:WIPRvqrsJ/IM1KE1RDhzdg==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:EEiMA6Nh8XbkS6eHcM04eSU7zZO88ssfrsiZEMtp,iv:aIL34ZNTOWOf8SjfDv8qZIST1WZDvMB7DWS4pATHxKI=,tag:eQ8/wgMSWlAnrmE4rLGlVA==,type:str]
    PUSHOVER_API_TOKEN: ENC[AES256_GCM,data:rfUkBoKYoOB4vTf2cV1d1qllo9ebizVV5QkIR81N,iv:r26rtu2oMOFO88hc4vu90D1QpSe6kV3RcyoohJZDhZk=,tag:SglLLrfskzocaT8XWmTvJg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z1VjWEJ2RmIvejNLd3d1
            NDJiaW82MTB2eXFkKzJlNzQ5aVA0U2l2M1Y4CmczdmNjeHAvWVR4NmRZdUh0eDZB
            cno1Vm5zL0toTjQzMUMwTmV0Um1jZWMKLS0tIHJwR2hOR1ZMM0V6Zi9PR1pnRHoz
            ZWorUzR3ZFdNeE1KSFNBeW9BSnJxb3cKoEq3KvT+irHUHhU20qVbcch7LvgNLFgQ
            aPJu6pdQXE/10aLxkkq+UiOrJdHa3OHIau1QrLz7rNH/OiwREJ8kww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T12:10:57Z"
    mac: ENC[AES256_GCM,data:wMdbMVlmrIijLNuSRgcQjvaBiS1aJDn0gGTbFFksfB1SQ90WwPWT+Pr0NY9/6osENySwItWNfBaBYc2K9mt0OKJrLErO1opXTGm/MwCUyCAHmy0YCcrezJVtm+Ax+sWVj5DQFCn653clpfPFdxwuAl7humk133wXPCxbJOQANkY=,iv:Z5qdd3EGA1qa43znQFjLDecL/d7U3R5mGQLL8Im9Nzw=,tag:o0X0sa96DjXpxzyHAqYyHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
