apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkit-cache
  namespace: buildkit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blizzard-storage
  resources:
    requests:
      storage: 50Gi
