apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vox-data
  namespace: vox
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 20Gi
