apiVersion: v1
kind: Secret
metadata:
    name: coturn-secret
    namespace: vox
type: Opaque
stringData:
    TURN_SECRET: ENC[AES256_GCM,data:pL3pX3sr7+NrmqAIupQJs4TvMRGHM4Kkjby1VMO1MY8Z3yWV6MVh9rGbycA=,iv:3khFkTgrLRQo3r2Q7GcNUKrALRdLW3I7Io6D2QCJ4X0=,tag:SFKL/kOAASPYvWr5WKZR0A==,type:str]
    VOX_API_KEY: ENC[AES256_GCM,data:/Rzyt1Z/wGQV04my82wQK/VMe8TDjSSYpv66aD2PLkF0+QFMC2s4Beqww7i0mnYL6+ls6cZjwmUQb4S7TjoBHQ==,iv:KL1MdVQxYcsDFqJfP94PIF+g7lNZVe9s0xGdVFnLbsI=,tag:zhUpedGPh2yzE/U4wOoqMQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSy9CMFhianF1dTluaFNZ
            U1ZDS3ZQRThiSFRPMUxSb1ZEUTR2VSthejJvClVVM3RDblo1YTZJMEs0c3JMM3pt
            aWNwT0h5UndCWjBYMm44Zi8vUXFEMzQKLS0tIHBJb2U0N1hjSGdqbGgreUVtY2pD
            S2RzU3NrOW9NWmNGWW05UTg3VmwvTzQKqpbuItaCByi+8kf+Gy6IQoTXGn5bjCLe
            HUxjy1Kj0JekBdUncGG7EgIlt5mB2AAfGiEinkxFZ23GYp1BDurpfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T22:29:18Z"
    mac: ENC[AES256_GCM,data:8/g/4XyJXj+pIlrsdIQdATIEjOZ8SeCG0GlyBTQAh52TED8moStQkxUHSR2ppTIEmoZ63RxArMj1esgLHTon5YAP+UWEeCbsA4YOWoS2Tj9u2H5fUZocALSe1D5lnMNOz0xtnYk/Mkn4n7s0sKSf67kZyRsVue1hbHq7aAaDvGY=,iv:XtICeKK9WKtChTjL1SSPfjJ3AmIkoIC7ihWyWR7JiQ8=,tag:AcfGEOmUG+FtUjmDuE+O6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
