apiVersion: v1
kind: Secret
metadata:
    name: mimir-secret
    namespace: mimir
type: Opaque
stringData:
    MIMIR_API_KEY: ENC[AES256_GCM,data:i93w9ewq61lpt5uMjQCAWIXMo1QdXb2awl24zzLO4Hc4S2+QNTl+RId7Fxps3L3Hz8CRAQ==,iv:z9+gg7tVxvOI8dXUAIO1POEZhp0ILptaAxH8+XCYeKI=,tag:KZhJyXIAoaCOCnYOddgWNw==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:cnn/sT3S1nFZ6HTdSSddN7Jp592p/7v5mw==,iv:bd2lgDG4BD9oyVQGVAxfahSf9MycSS5QByqovARf/Lo=,tag:V885G94IH5vye0/W6TF1kg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ2cwZ0RTbWJwN1d0Rmtt
            UGU1dmJIb1MzK2lwV0QwaHZiMi9ob04yVkg4ClBBSmUvVlNEc0s1Sm9ETDdOR1dl
            MWc0eTdUMGo4bWMrTVNUeDNjRmR5bm8KLS0tIFVsakRMVTFtWXNjK1FOTytEUzky
            dmdaYmdDNnVWL0t2VEJOSFdTMlJTbG8KLs70eHM57gRx8wFLNLMDC8rtkDwxnp+O
            9UxYUwI82L6pQqn3VXOf07oK+fcm9QggsRWmghZ8oO1NUXd1bpjLDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T07:29:49Z"
    mac: ENC[AES256_GCM,data:uo6iIWfQLiOsh9W1Zr33A15mQVloTapqDCUFqnKkMmmF2JusHJEaYxXPLerVyrNDWRrV1hHkOORFJOVfKHeWPKKMXBHd4YuudjFY+F4E+fhNPHihbGK2VoDJjArwmbdcXDzGlmv8cUEw0jYutIMWMQyOdRfREH5e9koXHSzErfQ=,iv:+kxsotGEwH/2jntzN9TftAh6g7Y/t3Zu8+Cl266gVEw=,tag:mMTbB2IB8c/zPFwZNaD2lQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
