apiVersion: v1
kind: Secret
metadata:
    name: registry-secret
    namespace: registry
type: Opaque
stringData:
    http-secret: ENC[AES256_GCM,data:SzQKL753M1DTdGQ5wdVvm4QoDqshzpXNR01SlD6OzOJuTg==,iv:mH7jhDvkJwX6zaDPobosko+SHihszkzWrjWpFiGVAIY=,tag:yyCJQEp1i3tUPj8r3/fgAg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Qkh4V21OTnZtd050bTA1
            eTVEalpCR3NCSmcrck5FN29PRHUxT0tnRlhvCjNzVnd3MEZVdmxuTFhXUkxWOUwz
            WXFJK1Baam85OWcrNzFsYUxtb3hBeGMKLS0tIFhFelZOS3F5clVEMFptelppUzhO
            MzROTThWQVZoZWRPbTlSZXdvRTNzM28KvQkRyK2qOUGH24k54En5/Oxkgh6Rs1gK
            gamp8FZRShcvts5aPPlLXELzE+BQVEvUG6T8j/1IGYSFyeK7aZXGEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-08T07:02:12Z"
    mac: ENC[AES256_GCM,data:u+8MZj4z97LN/cBuXJKcsD8orFByK/z19+TtAnbhFdra+upduCKxV5qPhC8SHtafiwnn0Qy0QO2Cg3LmIxH1sl7bBuTHnhGlDtOsoVFIaoyA8NZBztlpcuPaiGhRr5+hIVt64phMsZ6JZCmSIbXnauui28sU7R8gGoYPazBWSBw=,iv:zliU3kRZ9wpGPul9dez9mZUsURE9pHxXxA227B22YRo=,tag:9b+VGsW2PTbU9Ly/U5myYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
