apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
      - name: ui
        image: jc21/registry-ui:latest
        env:
        - name: NODE_ENV
          value: production
        - name: REGISTRY_HOST
          value: docker-registry:5000
        - name: REGISTRY_SSL
          value: "false"
        - name: REGISTRY_DOMAIN
          value: registry.horus.maix.ovh
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"