apiVersion: apps/v1
kind: Deployment
metadata:
  name: Plex
  labels:
    app: Plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Plex
  template:
    metadata:
      name: Plex
      labels:
        app: Plex
    spec:
      containers:
        - name: Plex
          image: lscr.io/linuxserver/plex:12.02.24
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 32400
              name: plex
            - containerPort: 32400
              name: plex-udp
              protocol: UDP
            - containerPort: 32469
              name: plex2
            - containerPort: 32469
              name: plex2-udp
              protocol: UDP
            - containerPort: 5353
              name: plex3-udp
              protocol: UDP
            - containerPort: 1900
              name: plex4-udp
              protocol: UDP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: VERSION
              value: "latest"
      restartPolicy: Always
      volumes:
        - name: plex
          persistentVolumeClaim:
            claimName: plex
