apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex-route
  namespace: plex
spec:
  parentRefs:
    - name: cilium-staging-gateway
      namespace: gateway
  hostnames:
    - "plex.staging.maix.ovh"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: plex-service
          port: 32400
