apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-retain
  resources:
    requests:
      storage: 10Gi
