apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: snow-storage
  resources:
    requests:
      storage: 1Ti
