apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: plex
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: plex-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

