apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: plex
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: plex-server
  ports:
    - port: 32400
      targetPort: 32400
      name: pms-web
      protocol: TCP
    - port: 32469
      targetPort: 32469
      name: dlna-tcp
      protocol: TCP

