apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: plex
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: plex-server
  ports:
    - name: plex
      port: 32400
      targetPort: 32400

