apiVersion: v1
kind: Secret
metadata:
    name: ferret-secrets
    namespace: ferret
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:t6Sdr8Qi4YcdXsPcrLLBJyWAGgEFQzWZBwwUPAss3U+zbUQKQrRcJRuRVUqF5DLH/Q+vuGmBvOSfTYRAbQkteQ==,iv:nd/gVpXpG5I1TVHF6NIOlqFP7AniAFD5HTcC9j5C7ns=,tag:GQjJAkUlWXl7G0kR4Dm9Zg==,type:str]
    OPENAI_COMPATIBLE_API_KEY: ENC[AES256_GCM,data:ukrfTpd9sZlDzVTSpBY6/ch8xtxB49TBow==,iv:gTqGgNe7Ysib5YGVQz46o41FQqNtkeIKFKni93aPmtE=,tag:9Be5lYWfExVQ+Juq6DE/eQ==,type:str]
    MIMIR_API_KEY: ENC[AES256_GCM,data:DqNWcHcblEVH3DNkgbbHPvkZ/onjf8d0Lze9ZUbLXCMyHGu2gEgvlqAr+EkRliqewds5hg==,iv:KlbhqmdTfbSrl3+z9y8dMuQm/4idT23beEaUeFdCjoU=,tag:sx0Pe5ip/Ws5xCYEUHwzLQ==,type:str]
    VOX_API_KEY: ENC[AES256_GCM,data:+8qsatX1s8RGxSPaSgZgt2BaMLg0UN875B2NzSByaWcL8UdeD+Z2b609O+/nwhiU2j0oLPg/ulWs4Dp1r9W69w==,iv:4F+qj7uSRCLAtLEDrLIn0liHM/J6L0y0X2MYY7VbvX8=,tag:PK72wMyuxYcjsZu94emf8A==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZkhDSG9XVWZLaHExL0hq
            YUJKaWRQTGZ6ZzlFb3N3Y0hlVjBjSDdQSXpRCmoyUVNpWitJOG05NVFTOUozZ3dO
            a0hkdjkwYnlINHVQTnlaMDJtbGF2SFEKLS0tIGlzNmt5TEZYaXZjV2x1Um9BYjZV
            blhXMTRzTTFyb2JNWXBSSmdrQ3dVT2sKKT0DCAJjFIoX97XtG6D7ZRPzuDzrZnVm
            K70WlgnikxkOgcRZ7O0GC1locAC7nCrV69E6h7/n+1AnIXMA5ImVjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T07:08:54Z"
    mac: ENC[AES256_GCM,data:f0sUOvJzGECuKKMrI3NfZwdI9glA20+jjtDubNCbotwZh3qvXmaPrmCaMLBj37PVo63+w7MSLhCq4VSL8wdB42KCI4VPDxxi1cdgS0ZOTcK5jOdyry2SzntgHMo/WnPObDRmsXRUhm9uRZ4q614uiz70qTjigeDL0rWoOi8VH6c=,iv:fcnCl6zGLfunzciqk0ed32j1jOe14Q2F6g927fsL+60=,tag:h/4DX/PBnjtvXbp095arFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
