apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: searxng
data:
  settings.yml: |
    use_default_settings:
      engines:
        keep_only:
          - google
          - google cse
          - bing
          - duckduckgo
          - startpage
          - mojeek
          - wikipedia
          - github
          - github code
          - stackoverflow
          - reddit
          - hackernews
          - arxiv
          - semantic scholar
          - mdn
          - arch linux wiki
          - docker hub
          - lib.rs
          - pkg.go.dev

    general:
      instance_name: "SearXNG"
      privacypolicy_url: false
      donation_url: false
      contact_url: false
      enable_metrics: false

    search:
      safe_search: 0
      autocomplete: "duckduckgo"
      default_lang: "en"
      ban_time_on_fail: 30
      max_ban_time_on_fail: 600
      formats:
        - html
        - json

    server:
      secret_key: "overridden-by-searxng-secret"
      limiter: false
      image_proxy: true
      http_protocol_version: "1.1"
      method: "GET"

    ui:
      static_use_hash: true
      default_theme: simple
      results_on_new_tab: false

    outgoing:
      request_timeout: 6.0
      max_request_timeout: 15.0
      useragent_suffix: ""
      pool_connections: 100
      pool_maxsize: 50
      enable_http2: true

    engines:
      - name: google
        disabled: false
        inactive: false
      - name: google cse
        disabled: false
      - name: bing
        disabled: false
      - name: duckduckgo
        disabled: false
      - name: startpage
        disabled: false
      - name: mojeek
        disabled: false
      - name: wikipedia
        disabled: false
      - name: arxiv
        disabled: false
      - name: github
        disabled: false
      - name: github code
        disabled: false
        inactive: false
      - name: stackoverflow
        disabled: false
      - name: reddit
        disabled: false
      - name: hackernews
        disabled: false
      - name: semantic scholar
        disabled: false
        inactive: false
      - name: mdn
        disabled: false
      - name: arch linux wiki
        disabled: false
      - name: docker hub
        disabled: false
      - name: lib.rs
        disabled: false
      - name: pkg.go.dev
        disabled: false
