apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - flaresolverr-adapter-configmap.yaml
  - flaresolverr-adapter-deployment.yaml
  - flaresolverr-adapter-service.yaml
  - deployment.yaml
  - service.yaml
  - httpRoute.yaml
