apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:ntkS3Mi4dUwE3Tgh5MeNnpd18GXWXVK9Z6jozbbgOzmQ3lQJtp0sCAxtAxwTsO1wvjuStMbr/h+gmGIoHjpWCw==,iv:2Cx+ATuX7CPasm+q9jvAh8Ujf9jvdbKrSGeSe63qT34=,tag:k1KrkdFnda/L5OKyf/5UgQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TGZPamMxZkx3amNQSW9V
            cVZzSVZVLzc1WUw5K0E2NzBYRktSMjJJb3djCnkzSDJHdXlNQ052MTJvdE1INVli
            VFQvUGdOTld0T1piY1FXd2lZam1OY0EKLS0tIERsL1NiU1JiN2FtMDdBVG9aMjly
            WkNpWHRyczFqVldRRW1IR0tTZ2lucmsKJOU+mp3DmC0K0qAedhGfxBksFNTmhUB8
            iQG6nueoC2cs3TZdhgA9wgRuLI7xyCt7vUr/pvt6vjZjVU2BgLPcIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T11:23:49Z"
    mac: ENC[AES256_GCM,data:oAnn7tSuiha+PTOSijkqQmnWODjT14+ZcEnlKbaAHwwJmCwBIVqvLpN8j69VvWgxbn9OCyocWUjpIsGIb0uf24i83Isbd1xsVzHk9tek7xA9butVqxtC+0p2g3Yjca7/vpsJxbLgsSKKretks1KBU31mk7Uy9dGk5Cs7g2OIRHI=,iv:bMVsUwLeMwIDm+EAn3oeZu6odUnhpcO3L7W40I/R19Y=,tag:DuKwB2NR7cs+bl7sal4U8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
