apiVersion: v1
kind: Secret
metadata:
    name: durable-streams-secret
    namespace: durable-streams
type: Opaque
stringData:
    DSTREAMS_TOKEN: ENC[AES256_GCM,data:9P0mbJHSL5w+D3QmNTOdHirDcbAiEgCYmaqQsyKiWxFzQmTruLAjbUeNgM0k+tcRSReGyrZtIbvsCvUYC1Gcyg==,iv:6tmlerwUkMqijihc4aP31gqbEfKpRPdR3G7XE+8S3/I=,tag:IbDhLQfh6QcQiJX3EdqqUw==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTEtNYzZPTVBtWG5TaVUz
            dnZpUXNuZDlrTC83VEJmVExTN0RyNFFCMWhZCmJWUjVQQ01SRDJyL1RCd0c4VzJ5
            YmhnZmpUTXpSRldZUllCVCtINklDeGsKLS0tIGpXR29QMDBTYUwvZGY1WXFjbHk3
            cGkvdHJqbXRkUE1wOVZyUGoyZDNFOVkKEBYpirTas+dS7lFjqAXYXUb6mW/n/j3V
            iz7ekIVRrsIuKCo/4Y+g7Q+MqrmSlRHPaDioF62ou5oDHs/eQsi7mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T11:57:12Z"
    mac: ENC[AES256_GCM,data:+FTRFsNFPiBn/z5bvls+hfrQparfwOkbLeADg3MlHYV8k6ZQSHSdKDJC97agVPd4NhQD40IXmRFSPHXdVTdOaryvxywwaMHJkPO6/pme+E0Sl1SFyaxS92Ojh9sIGTPDd8c+WFe31GgnEIugwXVJAb7/I+AHJsVhrCk3xaCwfUY=,iv:nYx0qoy/ukhALzzX9z7Dw3jQy3m/SSH8i6ADU+hHdzI=,tag:06ogsFCPh50k81auk236GA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
