apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-small
  namespace: rabbitmq-clusters
spec:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    storageClassName: "blizzard-storage"
    storage: 2Gi
  override:
    statefulSet:
      spec:
        template:
          spec:
            securityContext:
              fsGroup: 999
              runAsUser: 999
              runAsGroup: 999
            initContainers:
              - name: fix-nfs-permissions
                image: busybox:1.35
                command:
                  - sh
                  - -c
                  - |
                    echo "Fixing NFS permissions for RabbitMQ data directory..."
                    mkdir -p /var/lib/rabbitmq/mnesia
                    chown -R 999:999 /var/lib/rabbitmq
                    chmod -R 755 /var/lib/rabbitmq
                    ls -la /var/lib/rabbitmq
                volumeMounts:
                  - name: persistence
                    mountPath: /var/lib/rabbitmq
                securityContext:
                  runAsUser: 0
                  runAsGroup: 0
            containers: []  # This tells the operator to use default containers
  rabbitmq:
    additionalConfig: |
      vm_memory_high_watermark.relative = 0.6
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
      management.tcp.port = 15672
      log.console.level = info
      log.file.level = info