apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-small
  namespace: rabbitmq-clusters
spec:
  replicas: 1

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

  persistence:
    storageClassName: "blizzard-storage"
    storage: 2Gi

  rabbitmq:
    additionalConfig: |
      vm_memory_high_watermark.relative = 0.6
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
      management.tcp.port = 15672
      log.console.level = info
      log.file.level = info
