apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ada
resources:
  - namespace.yaml
  - secret.yaml
  - postgres.yaml
  - neo4j.yaml
  - qdrant.yaml
  - minio.yaml
  - minio-buckets.yaml
  - backup.yaml
  - service.yaml
  - deployment.yaml
  - httproute.yaml
