apiVersion: v1
kind: Secret
metadata:
  name: ada-secret
  namespace: ada
type: Opaque
stringData:
  ADA_BEAM_GRPC_AUTH_TOKEN: replace-me
  ADA_BEAM_LLM_API_KEY: replace-me
  ADA_BEAM_LLM_EMBED_API_KEY: replace-me
  POSTGRES_PASSWORD: replace-me
  NEO4J_PASSWORD: replace-me
  MINIO_ROOT_USER: replace-me
  MINIO_ROOT_PASSWORD: replace-me
