apiVersion: v1
kind: Secret
metadata:
    name: ada-secret
    namespace: ada
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:tUZN,iv:nFaZg71482QEiN3eL6Z8qEZLA7F6QUEu1AYWrqGQWko=,tag:rumexdIifrFVL3fNeC3rsQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:gbDEc4ppb6kVEqjWurT59EY0Hc9OaW7ZTqK+pFFn2zA=,iv:j4lYtp+vVc42lYxni4VSH3fJONgRjjAtvc2rh5Ls1pc=,tag:3CSqaikCHKQplJcCWZHVWw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:AbQ1,iv:RnLg83J9AURfrX0wVn/Ol9SUwPuSLp/uhK363yFwxqE=,tag:mt/OKQ3OYW/LBFdgWtcoRg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:yFqhWJd+Tmcp57AyGNazBEnI1tq6H4oZM9qGgyjasL/Ab9AsvaLCaRKxtpH2HvtEPH6o+Q0zzNoMEGImTXU1gi9JQJuSXzPups8hffQrQOa658YPOygceZFxfG+w0dw=,iv:bTFQxn1kyojOH6QVV2XjfcMDHqa7T9d9lY5+lCwwjmk=,tag:BEjlm/rnP+t5imEK7GZZ8Q==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:INSnhGjSvY4JdwMs4WcBvLB2CT+m9ui4QMheKjVFGxKv1WC5SHHGDAmkdgLj+3Sd2uTzTSk/T9F0ndW1pEPjp8Etn51/lHdo6w==,iv:YY2PkgqujLMro7lv/1qyhH/bhg37EOjBL/KFjuF6V3w=,tag:99ihbPVC5CTMbE9QT/4J5A==,type:str]
    GOOGLE_API_KEY: ENC[AES256_GCM,data:Iz91FWT9ZAmZiJVKwoVcI/DJkSGRBo8+XBpHR62EYGuDfIOftn8y,iv:CO73PvxCR61LHiPVB/oO59c6zTJOvNEYYQuTLbkujYA=,tag:0/z38SibirgFFjBeoBUM4w==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:+yZaqZrXqPfZMaCKKBV4Z+nHZefcOYfUbp2xDBjrYV6P1tk6we32SVZwUg2ZYrP2gyN6pVkIlCVLha45fdPqTMHKz/bTFXwys5bpr50gDYjqGziTXir+In3WNYiroByR16UjDMSGlBZNLXQk,iv:1euihOYpBy6bEuxspIP54fSAyVwiiVvYA1lSVNdPyhk=,tag:CtMuR4w1ie0O9WtfDCPM8A==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:e1y+dmcUdoba,iv:IWcq0MmURd10S4JTP06fdWe0NMWXs4kzavAf+yRx+2s=,tag:TW3h9i6SoKp+d432ly2DqQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:rmQjjY3qiLvzWZiPSaD8mWtOyUuJiMGYRnF1MX6PlZzDqfEzQs/BLMce9aE=,iv:AM5Hk7saKnzIX8BFQBQPhcb6DYi3dMP+9y6bzKocuhg=,tag:SYnoV3YOtA9OO+9p9tVjMQ==,type:str]
    NEO4J_PASSWORD: ENC[AES256_GCM,data:x5HpNrmzNXcuHTAR2MXBveB8RZc=,iv:E2KkhpiYvp9rEU8fcAO2w0YZX9reqMCXBa8SPsJtQjk=,tag:W0bolcpRbnPUEMD0RfVPdg==,type:str]
    SEED_TENANT_ID: ENC[AES256_GCM,data:LxBBg07p0g==,iv:88FeLHD649rbNquksiFx36kKMrF3vjX04NvGHgaHz2I=,tag:2MRNnWbyJdIdTINB+XASDw==,type:str]
    INTERNAL_AUTH_SECRET: ENC[AES256_GCM,data:N1SmjfPJZ9gW7GvQz/mnuQmVUwF8IUC11SnK2Nt+0jDQIIvQbS/UiaQSsEA=,iv:A7Wc71kd3EMN4owUMQCjHKEOl81Y9q/jzla+380fAro=,tag:eYXCXlAqioQ0UL/KWVJWJg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMmdYSUcvQjdXWWdqZXE1
            Umdyc0xYSzI1Z2svY3JZSlhoRHV6R3lxREFrClhUZUZOZmhGcGI4MDZtNDlQdkRU
            enUwWFNpaFpyNVQvejhQUGlGTmJva3cKLS0tIEppTnNUaVpjM1ZmOUJINTdYUml6
            clRuSEZvbC9NRVpmNzNxY05LRXVSS0EKsBlTRxLz03VwrS28pXPZWHYc8Kt99uw8
            J8F0lxVQ64lx0u9EKrBssGcoKlKgxHoYswHBaoXqx7KgFqo1QkCqFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T01:31:14Z"
    mac: ENC[AES256_GCM,data:TKL7F/qF5/6tg02JAGiGVuMZ4KdH77ik+pi2w795P02++vmfFnfiJP7mrvDpYdLTmfCkkoRX58VIj8KnJ9Gd5Shmq+4l+BaWitek+/mTUXGe0IkMG2giT/KHYM9yFcKP8wAsSX9znEALGC7R7vkdglX5GAZlNxr7n5z2VyoES1I=,iv:7WgD9PjQ1Up7km7wvG5sY7Sm+YNJuqutNGcjM9p09OI=,tag:KviAoXQU0EPkLZTdyozP3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
