apiVersion: v1
kind: Secret
metadata:
    name: ada-secret
    namespace: ada
type: Opaque
stringData:
    ADA_OSS_MASTER_KEY: ENC[AES256_GCM,data:sVz0tJBA1lZmthMu9/K42GpCg3PnAZ90xoqSbvkhI99qnSlXL2e117ZeyDuMcyCIJxVDfO1YJMObXYXVQeblKg==,iv:MMwOoaNymvxCwgJy5Sk3lerQveNmMn0aKPyHSOGaR4c=,tag:u/CQOQXq0pPlJ5zUPKq1Dg==,type:str]
    ADA_OSS_LLM_API_KEY: ENC[AES256_GCM,data:ZsV6d4hJyroCvo5a60bhG/i7CdiiJSmTUg==,iv:YGP8HqVxFTceIRjxTDBHrmvRoi6lVRm4PlCBmEzH3ps=,tag:STU5KOIk2xu8QS8mHoGpdA==,type:str]
    ADA_OSS_LLM_EMBED_API_KEY: ENC[AES256_GCM,data:Y3qOK0nCeROZgTyGBdiAdRyisQLUW9RnVA==,iv:ncd/S/Q9VkWe4sRy28B8ZoXgWPGyuKNhxgEpr/4cGgM=,tag:uDsYaAQmOCIduiMvF3xrMA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:RaKYWglszSZMqSvg6BDy4iyuQhQbNfxk56y/T7c4rsE=,iv:j3raSvs5/E63GF8VvZXkhtbL5anW19I6Gvim9ctxClE=,tag:g4pzo0y/oxx57s7W3Ytq0w==,type:str]
    NEO4J_PASSWORD: ENC[AES256_GCM,data:q5enKaCRxIuzDXCYQXxDegy0ocXbO5oghN/mpMm5t4M=,iv:wmnKdc3HDnlEKgE6VXbU2/lGiMLsB+G/J8TaUGqFzjg=,tag:e2f1kZ3EzU/WznOymzK0yQ==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:8UWEbUWi/tDwt/PP6x/Z,iv:R9Jh2bBuQmcbuq4VSDs3gBuzfRkHoDr4oOwWPJsPwuw=,tag:k0dvU+2CdHaV2PxTOA+Onw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:bTu4jHjr7+51B3R7u5Ph582CMTiwMOnOZxzu8VqCyvFdIvoHPYugOp+bq7JAjXaU,iv:bjjBV7L/v0h8Shx1eheIj/1CjUim41GSAw4rrBO3cDg=,tag:SfR98xKFHA90wB/33M6ZtQ==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WlZ5OHFlSkI2QnJMaE5a
            ZGJYcXdRUmlOci9HeWZVaFFyOWZSSlJ1L0ZJCitYd29MMnU5ZDhhZXZuOSt6L0Jt
            ZEJtamVTMDhIcElWOHNvYjFwdkJ5YkEKLS0tIHNuTFJJNWhrOE1YcXQrS1ZKNWtJ
            ZVBXOERPZ3pZODNoeFVTS25ybWY1MVkKPPm6Arwa1ILhpNC5hxsCNKroBGjoiXgP
            tEvcWwRoW1V4OPj4AX77T9W91QnDrx+COvAD24lkrCw7DKV2zHcZNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T09:23:28Z"
    mac: ENC[AES256_GCM,data:i54XSnEJCMxJl6yd0FgRfS4Yu9rIkDgYvzZ8ZrIw6NfmHKXe9IzaTQ4acx/bCW0or3YKt5+64Sh9EoUidX4cwpfiQN4fmV6lS9BweLjCZkZxlwPc/dTNXxGol/W0UhlWIUVN/yRZiJK3ZYWBbueV/ZxJdhfbcGglZ7S0Sbvk7M4=,iv:ozr6xWoChospnwSd6K2rAVO3dsK6Ny4pzFbtg95dzEc=,tag:rip0uqNyQJt7hESamLf4YA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
