apiVersion: v1
kind: Secret
metadata:
    name: ada-secret
    namespace: ada
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:1vAo,iv:QL4ub2JRfcHcXRd/3KBJ8PBNIwaAc4yKSMlOoEGUce4=,tag:CICELYjsWC7WB0vrHA07sQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:qzjABZIpRBC46fUVwscxAmEv48cyzc37LiTvTyYj2vQ=,iv:LJDl2ALtAGfDwB3InJoW3oLmYKJ7SLfCmcOilnbR3kE=,tag:S/AA5dTY3J0hPo4+Mxa0dw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:MD4l,iv:sB7e6Awhsmh6adozH7k1486lakA4jmGzNy2gLP2CHrw=,tag:+rSeamdYnizfI8nBxq0hYg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:obORpPkOPzMLw9mCd8TJY9I5TA9MOxH4pQOGvTVxP6mAvvrCyxt6VVFVnqlYuHaKlcbfFi4tsaVSLTUCss/KK4Nbn6eE8chjgg==,iv:/OJvJ9yB+olTfkOtbMrHP4YopUhqkwhAoIEMSvzc2wk=,tag:yjAekzY18ORXyTm5WAysUg==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:JbMZ0Erj0+Wf,iv:R3IVqC5L0PDNtsJfwfVojJ0M5T0PNMOX3Ew0Q/uVOJ0=,tag:9qgLC6QdiJu0tj40H25gsA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:S6GgDTuhSrMFvNrDXF42D6SZrM1lwxZtHT9f0Kl7KXrvfn3KDFF976lQ63A=,iv:8Y3P0X/iK83kaJUZCvM7y1NpIzsoMZIKnKInluGkzDA=,tag:LspiRc5ewgbQh8KIAYnETg==,type:str]
    NEO4J_PASSWORD: ENC[AES256_GCM,data:wDQjznjczM3E1FNLj04BFKrW2DI=,iv:+p/gT0V4AEioo/Zginw4t1rWpgQ9uxoiDzDfM3IROFg=,tag:msSkeGxRC1Ytdh3pyfkbpw==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4clNlcjRmSDNhYjNxUnha
            Z3cyakYxVHVkZ2xEeHAyUGNkc1owbUo5TlM0ClByb1BLMGxXU1MrOXAvTUdjaTVD
            RmNFMFdQZ2REemY5a2lrS1hTcmlmWWsKLS0tIGZoY1k1ZjJqZmNMa1hOdGhwU0Q2
            QjFFaXBkSlUyYmhMY2tXVEwxL1BEZUEKz7toYcZCzwQz7sudGod8uO+LaDy7SXjF
            Nji1HH3ggH9udScJGbgSVApcKz4Mv+gztp99ZjYcsu+8Giw8eMvUBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T16:41:38Z"
    mac: ENC[AES256_GCM,data:0o5WZTMQxM1FwSVwmpKYhErEuCLmqgHnL6g+dcnId2N/ZJKpgTg5342kOsGdx4QLU3FbU/c4iqG6B8mLq7bXisHCUr4/tgWVyciQPkG2U95+Q+V7RoUnTXOIKyxMdl0O/RLk+P8ofCi/bBVyoCQBNGzkQGaM4IAoqYlXlkmXJng=,iv:NZac9o6diSIR8/MMS72GyCh74Q6dK7aLwRJpODFegms=,tag:6mTvPGbtAAoOABx5STKXpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
