apiVersion: v1
data:
    ADA_BEAM_GRPC_AUTH_TOKEN: ENC[AES256_GCM,data:+x0++9H9/XIrJhnmJUclW6xziG0BExSFBQ9CLvWSNx5/aXv06yBDtLnEJuspxnUnu70t92Q6AdrapKlC8IsXPESoqmQj9mPTZCs9MLsY5VtnV8Upt3M5e6ZPgLgCn0/Frh1Zlx8U/D98uBgswy+03IS5JKHWKiNtcxSefj4Fvyo=,iv:bKzKMsDQB7LFNATheF8ltxC+nDZyzqS3jy2B7k10mH8=,tag:7sL0jbmxMWi0LgYN+x5jzQ==,type:str]
    ADA_BEAM_LLM_API_KEY: ENC[AES256_GCM,data:sCxD/0BtJHPyt1h+MA8clrvSwo6yOwrI/+kBFOyoieI2x2fE,iv:rziAb9u1U4D3uT4vDZJEQv8FmmwUri0E9wl70BJNHMY=,tag:JHFEowGxv50FcuW9Js2V3Q==,type:str]
    ADA_BEAM_LLM_EMBED_API_KEY: ENC[AES256_GCM,data:Gux0TZ8uGo74LfZ41PLNn2YqN6AgGotiOsWk9NTI+WC7RkU0,iv:glVH6iir/RpBnmYb4mftNGfu3N6HOBid74oLiWLjJY4=,tag:rMyk83jtcrE5YaUl9umseQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:DPzyjvdyBz7v5YFOAZImvmegr3uWcV7K4KQZNzIZ87icLvCh0dJotzs7DTFGeqUH03/Iv+VYB5FzYoI7gI+PrFChVVKABYoar0/0UOMLgJ0FArE8S14EWQ==,iv:252qzoUhbxD50Ecs6xUKidTW8dzXSYl40ErJsC1j7Pw=,tag:H9V6unNJKftYYI/cNcrSJA==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:iOjiva/AYXzQ4GucQg77mJf7cg94b1PKUIhhwA==,iv:fFH42X6YjtdmEW45wkaw3WpsZ8Nw9/LofErwVLFT8jQ=,tag:+eaHuE2Ci9WMMWpw+tXWtw==,type:str]
    NEO4J_PASSWORD: ENC[AES256_GCM,data:1JQmCyKxIfan420swQKNay/prcsCce/g8EB4fgtLv689BYY3S3M0/HS/DpFT4J5/DsRt0A/+IJfosOyeosZxkvOu2475wAhg3eayyqo3VGf2kakLHpIkXg==,iv:pD+P02iWzpZIGolDL8BCvEDFjwrDF3r4KxzrtPUoaoM=,tag:Hx2GoVkQwo/MjByz/SAOtQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:p/OUpIM07yr1T4d85pnj1o01qbO8fy43tZwKKuvNjdchkDwJikHKYLeJUZZgpG1OjrVRBMVtcnGcgixV26/w/wUZ2R+RsRCT7PUtruX2llwkRR5V6XhIuw==,iv:s4hjD8iYZVvC3+LJdc1HtssdKjPtOgwbTn2IEu4NqYk=,tag:22UZxaUSlhdsj1o+hFIetw==,type:str]
kind: Secret
metadata:
    name: ada-secret
    namespace: ada
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYmlGUlQ0U3d2VEthblR4
            cG16V1R1R05TOVhWVTFORk9ZczBlak9Fa1JNCkowbG03L2dxc2RqU0Y4KzRJbFBN
            Y3R4K0g3VHZyYVJFV3BTaE1MNWc0a2sKLS0tIDJ5T1NnRGlzeFFzMHZLOTJkelR0
            Vm9FbUgvV3lwVENVT0RJMXV0dXRpTUkKc+JWMzjbqVsW6SH2Y3bHYWiyf++oEB0g
            wQrxjV++4U5s1sk3EDTZI7Ma5nckMuycc9NqHW4IFXDPfWqyVgqToA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T07:19:50Z"
    mac: ENC[AES256_GCM,data:wcBmG+GkXMjCv+QLns3z7+y6JHY3zUdP5uOKhUA7KUSZZFlXrlzPpzkzxIZSpg42Otbq224gLiFhilf2WmL1GG3uMAYcSkWL2YyxG4OAfIPkZHbg2A4LXpoEmvV/0MbXUbJq783uEGrey5wHwSbpk4OwnOl4ZMzvhwjZiHvx0YE=,iv:1s4+9HKHn8b34tSrrx+0qJ/c3ndb0akvDpDIjS6X5hY=,tag:rgIXsq4GZdrVjD6PhXGpNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
