apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
  annotations:
    io.cilium.service/lb-ipam-ips: "172.198.1.10"
spec:
  selector:
    app: redis-deployment
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
      protocol: TCP
  type: LoadBalancer
