apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-microservices
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-microservices
  template:
    metadata:
      labels:
        app: immich-microservices
    spec:
      containers:
        - name: immich-microservices
          image: ghcr.io/immich-app/immich-server:v2.1.0
          command:
            - /bin/sh
            - ./start.sh
          args:
            - microservices
          env:
            - name: DB_HOSTNAME
              value: "immich-postgres"
            - name: DB_USERNAME
              value: "immich"
            - name: DB_PASSWORD
              value: "immich"
            - name: DB_DATABASE_NAME
              value: "immich"
            - name: REDIS_HOSTNAME
              value: "immich-redis"
            - name: IMMICH_MACHINE_LEARNING_URL
              value: "http://immich-machine-learning:3003"
            - name: TZ
              value: "Europe/Paris"
          volumeMounts:
            - name: library
              mountPath: /usr/src/app/upload
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich-library
