apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-db-init
  namespace: immich
data:
  init.sh: |
    #!/bin/sh
    set -e

    # Wait for PostgreSQL to be ready
    until pg_isready -h $PGHOST -p $PGPORT -U $PGUSER; do
      echo "Waiting for PostgreSQL..."
      sleep 2
    done

    # Create database if it doesn't exist
    psql -tc "SELECT 1 FROM pg_database WHERE datname = 'immich'" | grep -q 1 || \
      psql -c "CREATE DATABASE immich"

    # Create user if it doesn't exist
    psql -tc "SELECT 1 FROM pg_user WHERE usename = 'immich'" | grep -q 1 || \
      psql -c "CREATE USER immich WITH PASSWORD 'immich'"

    # Set ownership and privileges
    psql -c "ALTER DATABASE immich OWNER TO immich"
    psql -c "GRANT ALL PRIVILEGES ON DATABASE immich TO immich"

    # Connect to immich database and setup extensions
    psql -d immich -c "GRANT ALL ON SCHEMA public TO immich"
    psql -d immich -c "CREATE EXTENSION IF NOT EXISTS cube"
    psql -d immich -c "CREATE EXTENSION IF NOT EXISTS earthdistance"
    psql -d immich -c "CREATE EXTENSION IF NOT EXISTS vector"

    echo "Database initialization complete"
