apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - repo.yaml
  - release.yaml
  - httpRoute.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: immich-server
      spec:
        template:
          spec:
            initContainers:
              - name: init-db
                image: postgres:14
                env:
                  - name: POSTGRES_USER
                    valueFrom:
                      secretKeyRef:
                        name: postgres-secret
                        key: POSTGRES_USER
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: postgres-secret
                        key: POSTGRES_PASSWORD
                  - name: DB_NAME
                    value: immich
                  - name: POSTGRES_HOST
                    value: postgres-service.postgres.svc.cluster.local
                command:
                  - sh
                  - -c
                  - |
                    PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -d postgres -c "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'" | grep -q 1 || PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -d postgres -c "CREATE DATABASE $DB_NAME;"
    target:
      kind: Deployment
      name: immich-server
