apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - immich-server.yaml
  - immich-microservices.yaml
  - immich-machine-learning.yaml
  - service.yaml
  - httpRoute.yaml
