apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  storageClassName: media-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
