apiVersion: v1
kind: ServiceAccount
metadata:
  name: immich-sa
  namespace: immich
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-secret-reader
  namespace: postgres
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["postgres-secret"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: immich-read-postgres-secret
  namespace: postgres
subjects:
  - kind: ServiceAccount
    name: immich-sa
    namespace: immich
roleRef:
  kind: Role
  name: postgres-secret-reader
  apiGroup: rbac.authorization.k8s.io
