apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-release
  namespace: immich
spec:
  chart:
    spec:
      chart: immich
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: immich
  values:
    image:
      tag: v.110.0

    immich:
      persistence:
        library:
          enabled: true
          type: persistentVolumeClaim
          existingClaim: immich-library

    machine-learning:
      persistence:
        cache:
          storageClass: blizzard-storage
          type: pvc

    configuration:
      trash:
        enabled: true
        days: 30
      storageTemplate:
        enabled: true
        template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
      duplicateDetection:
        enabled: true
        maxDistance: 0.03

    env:
      REDIS_HOSTNAME: redis-service.redis.svc.cluster.local
      DB_HOSTNAME: postgres-service.postgres.svc.cluster.local
      DB_PORT: 5432
      DB_DATABASE_NAME: immich
      DB_VECTOR_EXTENSION: pgvector
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            key: POSTGRES_USER
            name: postgres-secret
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            key: POSTGRES_PASSWORD
            name: postgres-secret
