apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  releaseName: immich
  chart:
    spec:
      chart: immich
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      TZ: Europe/Paris

    image:
      tag: v2.1.0

    immich:
      persistence:
        library:
          existingClaim: immich-library

    server:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        tag: v2.1.0
      envFrom:
        - secretRef:
            name: immich-secret
      ingress:
        main:
          enabled: false

    microservices:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        tag: v2.1.0
      envFrom:
        - secretRef:
            name: immich-secret
      env:
        IMMICH_WORKERS_EXCLUDE: api

    machine-learning:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-machine-learning
        tag: v2.1.0
      env:
        TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          storageClass: app-storage
          size: 10Gi

    redis:
      enabled: false

    valkey:
      enabled: false

    postgresql:
      enabled: false
