apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  releaseName: immich
  chart:
    spec:
      chart: immich
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: immich-secret
      valuesKey: DB_HOSTNAME
      targetPath: controllers.main.containers.main.env.DB_HOSTNAME
    - kind: Secret
      name: immich-secret
      valuesKey: DB_PORT
      targetPath: controllers.main.containers.main.env.DB_PORT
    - kind: Secret
      name: immich-secret
      valuesKey: DB_USERNAME
      targetPath: controllers.main.containers.main.env.DB_USERNAME
    - kind: Secret
      name: immich-secret
      valuesKey: DB_PASSWORD
      targetPath: controllers.main.containers.main.env.DB_PASSWORD
    - kind: Secret
      name: immich-secret
      valuesKey: DB_DATABASE_NAME
      targetPath: controllers.main.containers.main.env.DB_DATABASE_NAME
    - kind: Secret
      name: immich-secret
      valuesKey: REDIS_HOSTNAME
      targetPath: controllers.main.containers.main.env.REDIS_HOSTNAME
    - kind: Secret
      name: immich-secret
      valuesKey: REDIS_PORT
      targetPath: controllers.main.containers.main.env.REDIS_PORT
  values:
    controllers:
      main:
        containers:
          main:
            env:
              TZ: Europe/Paris

    image:
      tag: v2.1.0

    immich:
      persistence:
        library:
          existingClaim: immich-library

    server:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        tag: v2.1.0
      ingress:
        main:
          enabled: false

    microservices:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        tag: v2.1.0
      env:
        IMMICH_WORKERS_EXCLUDE: api

    machine-learning:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-machine-learning
        tag: v2.1.0
      env:
        TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          storageClass: app-storage
          size: 10Gi
