apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  chart:
    spec:
      chart: immich
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  interval: 15m
  timeout: 10m
  releaseName: immich
  targetNamespace: immich
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Disable bundled PostgreSQL and Redis
    postgresql:
      enabled: false
    redis:
      enabled: false

    # Environment configuration for external services
    env:
      # Database configuration - using pgbouncer
      DB_HOSTNAME:
        value: pgbouncer-service.postgres.svc.cluster.local
      DB_PORT:
        value: "5432"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-secret
            key: DB_USERNAME
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-secret
            key: DB_PASSWORD
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-secret
            key: DB_DATABASE_NAME

      # Redis configuration
      REDIS_HOSTNAME:
        value: redis-service.redis.svc.cluster.local
      REDIS_PORT:
        value: "6379"

      # JWT Secret
      IMMICH_JWT_SECRET:
        valueFrom:
          secretKeyRef:
            name: immich-secret
            key: JWT_SECRET

    # Persistence configuration
    persistence:
      library:
        enabled: true
        storageClass: media-storage
        size: 500Gi
        accessMode: ReadWriteMany

    # Server configuration
    server:
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 2Gi
          cpu: 2000m

    # Machine Learning configuration
    machinelearning:
      enabled: true
      persistence:
        cache:
          enabled: true
          storageClass: app-storage
          size: 10Gi
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 4Gi
          cpu: 2000m

    # Microservices configuration
    microservices:
      enabled: true
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 2Gi
          cpu: 2000m
