apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-release
  namespace: immich
spec:
  chart:
    spec:
      chart: immich
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: immich
  values:
    immich:
      persistence:
        library:
          enabled: true
          type: persistentVolumeClaim
          existingClaim: immich-library
    machine-learning:
      persistence:
        cache:
          storageClass: media-storage
          type: pvc
    postgresql:
      enabled: true
      persistence:
        config:
          storageClass: app-storage
          type: pvc
      image:
        repository: tensorchord/pgvecto-rs
        tag: pg14-v0.2.0
      global:
        postgresql:
          auth:
            username: immich
            database: immich
            password: immich
      primary:
        initdb:
          scripts:
            create-extensions.sql: |
              CREATE EXTENSION cube;
              CREATE EXTENSION earthdistance;
              CREATE EXTENSION vectors;
    configuration:
      trash:
        enabled: true
        days: 30
      storageTemplate:
        enabled: true
        template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
      duplicateDetection:
        enabled: true
        maxDistance: 0.03
    env:
      REDIS_HOSTNAME: redis-service.redis.svc.cluster.local



