apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  chart:
    spec:
      chart: immich
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  interval: 15m
  timeout: 10m
  releaseName: immich
  targetNamespace: immich
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Image version
    image:
      tag: v2.0.0

    # Environment configuration for external services
    env:
      DB_HOSTNAME: pgbouncer-service.postgres.svc.cluster.local
      DB_PORT: "5432"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-secret
            key: DB_USERNAME
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-secret
            key: DB_PASSWORD
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-secret
            key: DB_DATABASE_NAME
      REDIS_HOSTNAME: redis-service.redis.svc.cluster.local
      REDIS_PORT: "6379"

    # Immich configuration
    immich:
      persistence:
        library:
          existingClaim: immich-library

    # Disable bundled services
    postgresql:
      enabled: false

    redis:
      enabled: false
