apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
stringData:
    DB_HOSTNAME: ENC[AES256_GCM,data:cHh/P1QGEsyKYw4KNEbz+r/pWpVjxqRCKl7gOiVdDbtrd4FGfiHxVEdVAA==,iv:VQh9SEt3ZG08uaCgwSnAkwYhfMhgxU82QxuEcQfMh7k=,tag:wUuzRSIGCA70g4oOc2u+NQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:eDdRvw==,iv:zVfj5aRIBcS7Jj8lA579EvuetxN2Sglzg5LqsgYGLHc=,tag:wgbjl54UA3WI3czlM18S1g==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:TbnZcTXE,iv:Zjl/jgbVya5ljmVPpTqz5WmJWT2IrUzkabFTcxvsqJ8=,tag:XOehG+A6/o6905DUeoAoCQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:3zfp7Vy7,iv:r83l6exuP7ebiocNc5ka+1ijNBx/ppHUdhgceAjFras=,tag:FGOjuiHfaSaN4EYRZtvFxw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:F8DTL2Es,iv:GI77dU685SKDpiafSnDTH1qrVPS+fmUNAKFzvqwjPes=,tag:Bi7f71eZP0/JOqHZYBlMbg==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:/xpgDqn1EW2vkEe/49qVxKaIFS1Z/hhKQvjwb7AgXUz63ToTvQ==,iv:be9zBbVbubZ52OXluF/rJGydY4U+gYFNo5T7i6JfpjY=,tag:/TENWwDluvBHLeDDvvROWA==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:zjNbwA==,iv:Djsl8sdEpshqIB3WRsIyjUkyB01ARtyRScOlR/p95H0=,tag:Bgl3Y9Xzf1Dp+pOXymkmQA==,type:str]
    PGUSER: ENC[AES256_GCM,data:ZbbTpi0z1L0=,iv:y6bQ3FjzPP0XRvVPvYpFzpwpHSS+HTCpi+iO83KvJdQ=,tag:p0SHD6KiuVFsLiPZNIxyTA==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:fH+clxM6pshyAw==,iv:USd2TetKvcW5mM5OkiDF0jf/2sij+NotBPLbGzb7VXE=,tag:oFzCxToOHcpyXlUV5Cg3Zg==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmN2w0anRQM3lJemJyeFhw
            MnRzU0NFQmg3VlpVenV1T0RIdXBLY3pPUm5FCm42ZURaWkZoWHBpQk4yeHVCSzh6
            L2o4Q1FEdW56UFUzUUZOVjBQS0JxeVEKLS0tIFIrYVVLYVJSUEhDcUdqM3hjVHZT
            WjZtSHpKdi9DK2lRUjBPSHF5TDlSSk0KZbBbvhQSIkzOjUG8/+gSFPwI0OrgS9+q
            IeCPykRpooJDpjuFP2S4udzCev7kXK6LTwOvhWgi0DencGKYj75GzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T08:25:11Z"
    mac: ENC[AES256_GCM,data:aqa8tCIks5aJd912l6VFbfU6ezyHTDIQqgF/EurG7IcZBJ5YKg+LpHh4yK3NXjGqiYnbESLBIEVnGp0p4h0uHoTrgxKWILHAFVK0wmPHeL8NMSC7mWJicrKx66pOSJvEuTyhTI6Wc0mKVqWy0EMXfV9O34+5oHxlpP3PYDTBx3U=,iv:ThHYed3obho2eJqdDStnAN6GvLz+05NZhrOnNwAZooM=,tag:cvW+xNcJzvDUZSHA3woRfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
