apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:ylhMq3sp8qQ=,iv:mxjDm6mLtIkb27xO2kEITPnoI/Ko+o1XvWtnF7703LA=,tag:3G3sFlnUBJh0DG/UpYr0bQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:L1i7ytSGHB1oU0kkmsNDVaYdHvm9yfOij961oYlGWhzj5QcTEAbEjmsc5BU=,iv:z8E7DOmDnAO4TN6YMkbFB5hm3MO7ZFGqx5N8QIxGk5w=,tag:fvjzSDXXsw8v6XikxIQfFA==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:pA0cq1f5,iv:HWccN+4c/EgCaENLsfhjfgHcx9J6zp8IsjPjqxeCVus=,tag:7MFH3Or6bHybYzJ5BER1EA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:+f3TwWYQL16MrjtpXUZNYHgTBTIfcQKgSr4Vdmpo+j5PMlEdGQTLev2SZUVng92LloWbGhipV8rSfyyFhqT8/A==,iv:o5kcOMCRP4RTCtwUbtm9qY76b6o2rvvDBqyi1Z0epvY=,tag:76XCRPoRtqL+rSYbI0KUMw==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MTdQbGtxKzlINkhRMVJz
            bHJtUXVSN1NxQXB0TkhZR2tqRWJKNEt4Mm5RCmRTRitKSHFOS0V5M2RXa1hzVjZG
            dmZxckxZYlBqWFVma1BMYTBRUWdvbncKLS0tIG9TV3lTTGVOTVBmeVd2Vi80YThJ
            U0hWUUsyNDJoWDdlWmdaZndKRUhoVkUKgljsr0qR+gLsl5JaqIcR1PbHu2LFseZx
            IlKSYDhWLu//PsBapKJKphKiO0b3UV762cWhmEx7h3sx/Nzj8wpMfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T09:46:23Z"
    mac: ENC[AES256_GCM,data:3gdcwTQ1BCOJmmLvbJ36tkuKAK+fbc5VBsRqmSMqYDtnkyCLCpPg/S/cI4u5Zzr66GKO7lcboMPxnI9h3+3WWznTS1daAguAwQpC5ix8uLgY/i8d3JJFQyTmW5yuvRgBYR7+zgpRABLDPkgLOtg/dkAtY3JpMi6+2nBJavolFq4=,iv:MVRaSjNuaOPFbG2QSmIOImILgqv5u54bgvI/0kJOP7w=,tag:F2/P/D9gIprdZBXrT2EqHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
