apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: immich
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:UGo8PvNJaDI=,iv:vGeBArV6mT4XlrNkcCY9jYVjv9iMdor54bDtwFLiLRM=,tag:VKEDtPclLu1rMquOL8lnzQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lqDr2YVvWdd73w==,iv:3qK0HWk9HVKY9ekXLmQLAU8UETqUqeFaTx1bDiyeKQE=,tag:/d7TZhy+W04nGNKIEVzhLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSlVINnZIaXRmaW9IRUl2
            d3BwMUtxdkdvQWRWQ3A5OUtzSkw3ZDZicDBFCmpWbzBLRXEyblpKdWhLMEdCOTJZ
            WU50U0lGTXpsZWtoNVJyaTE1RzVQZUEKLS0tIGpUUDZqTGJLMlRZeTdILzBLYlZN
            UXhsZDRvcVlhK3BvdXF5aWRWVjZaaFUKMOFN6T+KI0I4LSqt6t/4ENbeuGjYmPnN
            jfgsRuw2IzglWHYmT04iAGVZcOVhay2+OgAlImz4Q9dDkdzH/uvfzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-25T17:20:00Z"
    mac: ENC[AES256_GCM,data:PyEyIZsayxlC3y7v7WxnGB4A/C9SWZBL2+zikskvHY5Nk91rz9nK8cXIXFcy4jeOwtUwW0tNyXtZCa18txSkQq0T41XCQ9+tEkYln468knzzCg5Z5guvwawqtbtJq+7rPO5XJKjN2ucDGQW7sP+zYBuT6xCo+rM2T6uzhdtno4A=,iv:Wyzxgk5/dIDm+9HLa8njZY7teMrTisFQXdwghC3RXFE=,tag:xuqqnLEqb895IOUq3us3JA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
