apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:ekuWIAst54k=,iv:Pl6eZYEqGhRoOyAXnDCB9FGrgVSYnDU9+nS3aQ/u7Do=,tag:EsrkIxOlIziT0RwJrpnfpw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ofgWtUunEgDW2Q==,iv:fWeJyDqKjojucrvk3TMRr9YrmiLD2Xg7w7qwdCHQ6bE=,tag:tVQouZYzS5SnFdd7ylz6Kw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:5woCB1fx,iv:9+lINZbN1YK+p8gkNcynT8nOfAR6L4/d6gy5lBLJgXM=,tag:DfLFsuFK0jcirVyoRd8l3w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:g+wLVFUaOxQbNXJTg+ms/gdcrxG8vpLIlDTJ5zF6OfInTg+S1QozgOXDUaD06CPfYdL7yuw/UtUiImVppi/A5w==,iv:3QDN0OwZKaaL7AxIN43z/Z/3+Iae892IgHo9H2rJqSE=,tag:K81TbjGVwHzSMqpjdEmU9Q==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MkI3WlV6ai9KaDhod3dL
            TDdkcGN5RUIydzU1L2Q1aDlEZGdvS09yM1RJCk1EZE9pdmVMTzlYWFlEVVZ5eVNF
            eTBBZjJNaWJ0RE5YWnZBSWhkaUQ1cm8KLS0tIEk4NzR5cDJ0ZG9keWZsTXRjek9I
            eEoxK0hWWjN3MERybjhvVXpZd1lyekEK/ZQ4xwLjpkFEQadP8ftIr6oU7ePjkJqB
            CYa6yiz3uCtygeCKqb8XN5kLbkNHrIFruAeITyIczr398WnmSCK1Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T08:18:15Z"
    mac: ENC[AES256_GCM,data:5WJ94+c1nmZO6uj4HhKi3QISIPrQ5Tb3/RrAMyqaQSO0KTw3U/h5SOE6v+PrFOR7lceIoNMXVGC+ZkBf4laOrIree9gU6Xnze/EZWcWa2R2lmXMB5uBlqCUqa4nMoLYRX+rf9F3PCsDql4Wa5/ilLgo3auDo4fh1pWi35QtdOmo=,iv:wRqz85Re6E45/f7OiMi7ck8txA1/59kscEXN7T6CzHA=,tag:DWOb8htKpfIdGC33w1Q01Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
