apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
spec:
  selector:
    app: immich-server
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: http
  type: ClusterIP
