apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: email-engine-data
  namespace: email-engine
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: app-storage
  resources:
    requests:
      storage: 2Gi

