apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clio-data
  namespace: clio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: app-storage
  resources:
    requests:
      storage: 2Gi
