apiVersion: v1
kind: Secret
metadata:
    name: clio-secrets
    namespace: clio
type: Opaque
stringData:
    APP_PASSWORD: ENC[AES256_GCM,data:oadZjVmAtQR68OXX6NpDPoo8EMI=,iv:3gDD+ECS8iD/YblIyYfboUpCWaaiwSY1m1i3XsyMavg=,tag:MdROQNpol2U27fC5/TLwEg==,type:str]
    VOX_API_KEY: ENC[AES256_GCM,data:zv3Dqt1aLvE8zpJslU3MkfwQQYQj/GrXlrczeEUMfAXm7by1y8wcceM/JK6aBMaWtkOnBttzdQQCOquCPiIlSg==,iv:8AjZQpY389o05YVnbDDTxmYNEFHXh7qHG5/juTkwDH0=,tag:/QYU6sbJYYq5zx+yM9slJw==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:nMh5qPPP2IEnN9a/gzMFc9UEvOeijnoNUA==,iv:iJ1tRD9mEj+18TuipU9dXJyEvY6inymgSYVAje0vj0c=,tag:hiWeep+DyTxr4wZeeQ9Yhw==,type:str]
sops:
    age:
        - recipient: age1vltshxxpzdfl5jge57nwvmq77fmva0y9p9slmknfjwd97kz5m9asmndj0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMm9CbEJUTFo0bWhYNnlS
            djBSY04wTFBIVEFEWm03R3Nad2k4WGFnQjNrCjZQa3hqalN4NkovQi9HSHFLS1pF
            SDhxbVFtUXpHWi9qTHJNeHRlbW9uS1UKLS0tIDhxcCtiaTlSZEFITnJnb3N5Z0Ux
            NElsWkZCYklDem16LzV0OWkyWFRQVnMKWeJRgoFOkiQnnHhvhEDW3GhAGf4npKlR
            igvSETZ8RnlBrLi9kQScL2+XOWnVI0oidOIaLJDd7lQMzzIVBQ9F0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T22:25:51Z"
    mac: ENC[AES256_GCM,data:pjI0JTy7CT3/hL+1OviZ2X4mopgyLOJLTC93TjGgaHgnWSNVOp+89dmtBaIcfPT55vI60biufK4Cz/l7NryYIPOl0nLS2S3MtDCRpce4bEDF3T3Md4gbr0NV0anAGaLSsIIwKzz+Y/Kp5vh4Htz7stuKo5H3ptjXCCL9LFDP+Tg=,iv:Gv/6QE5vEOxX7C/y7pKAj1JooUTdOaFJxp24WWHPod4=,tag:HF/wf61j4I1F7GVPcTlcUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
